/**
 * @file FishDatabase.ts
 * @description 어종 데이터베이스 스키마 및 초기 데이터
 *
 * 한국 바다 낚시 대상어 데이터.
 * 실제 어류 생태 정보를 바탕으로 입질 확률 계산에 활용됩니다.
 */

import type { BaitCategory } from '../types/Gear.js';
import type { SpotType } from '../types/Environment.js';

// ─────────────────────────────────────────────
// 어종 스키마
// ─────────────────────────────────────────────
export interface FishSpecies {
  id: string;
  /** 한국 이름 */
  nameKo: string;
  /** 영문 이름 */
  nameEn: string;
  /** 학명 */
  scientificName: string;
  /** 도트 스프라이트 키 */
  spriteKey: string;
  /** 최소 법정 포획 크기 (cm, 0=제한 없음) */
  minLegalSizeCm: number;
  /** 평균 크기 범위 (cm) */
  avgSizeRangeCm: [number, number];
  /** 최대 크기 기록 (cm) — 기네스급 */
  maxRecordCm: number;
  /** 평균 무게 범위 (g) */
  avgWeightRangeG: [number, number];
  /** 적정 수심 범위 (m) */
  preferredDepthM: [number, number];
  /** 적정 수온 범위 (°C) */
  preferredTempC: [number, number];
  /** 주요 먹이 (선호 미끼) */
  preferredBaits: BaitCategory[];
  /** 주요 서식 스팟 유형 */
  habitatSpotTypes: SpotType[];
  /** 제철 (월, 1~12) */
  peakSeasonMonths: number[];
  /** 주로 활동하는 물때 (1~15, 비어있으면 무관) */
  activeTidePhases?: number[];
  /** 야행성 여부 */
  isNocturnal: boolean;
  /** 야간 활동 보너스 (%) */
  nightBiteBonus: number;
  /** 희귀도 (일반적일수록 높은 출현율) */
  rarity: FishRarity;
  /** 난이도 (잡기 어려울수록 높음) */
  difficulty: 1 | 2 | 3 | 4 | 5;
  /** 횟값 (kg당 원, 근처 횟집 손질비 계산 기준) */
  sashimiValuePerKg: number;
  /** 서식 수층 */
  swimmingLayer: 'surface' | 'mid' | 'bottom';
  /** 보일링 발생 어종 여부 */
  isBoilingSpecies?: boolean;
  /** 설명 */
  description: string;
}

export type FishRarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';

// ─────────────────────────────────────────────
// 초기 어종 데이터 (한국 바다 낚시 주요 대상어)
// ─────────────────────────────────────────────
export const FISH_DATABASE: FishSpecies[] = [
  {
    id: 'dark_banded_rockfish',
    nameKo: '볼락',
    nameEn: 'Black Rockfish',
    scientificName: 'Sebastes inermis',
    spriteKey: 'fish_dark_banded_rockfish',
    minLegalSizeCm: 15,
    avgSizeRangeCm: [15, 30],
    maxRecordCm: 42,
    avgWeightRangeG: [150, 600],
    preferredDepthM: [3, 30],
    preferredTempC: [12, 22],
    preferredBaits: ['sandworm', 'prawn', 'artificial_worm'],
    habitatSpotTypes: ['rocky_shore', 'breakwater'],
    peakSeasonMonths: [11, 12, 1, 2, 3],
    isNocturnal: true,
    nightBiteBonus: 60,
    rarity: 'common',
    difficulty: 1,
    sashimiValuePerKg: 25000,
    swimmingLayer: 'surface',
    isBoilingSpecies: true,
    description: '방파제와 갯바위 근처 수중여에 서식하는 대표적인 야행성 어종. 집어등에 잘 반응하며, 밤이 되면 상층으로 피딩하러 올라와 끓어오르는 보일링을 형성하기도 한다.',
  },
  {
    id: 'largescale_blackfish',
    nameKo: '벵에돔',
    nameEn: 'Largescale Blackfish',
    scientificName: 'Girella punctata',
    spriteKey: 'fish_largescale_blackfish',
    minLegalSizeCm: 0,   // 금지체장 없음 — 20~23cm 미만 자율 방생 권장
    avgSizeRangeCm: [25, 35],
    maxRecordCm: 55,
    avgWeightRangeG: [500, 1500],
    preferredDepthM: [3, 15],
    preferredTempC: [18, 28],
    preferredBaits: ['bread', 'prawn', 'sandworm'],
    habitatSpotTypes: ['rocky_shore', 'breakwater'],
    peakSeasonMonths: [6, 7, 8, 9, 10],
    activeTidePhases: [6, 7, 8, 9, 10],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'uncommon',
    difficulty: 4,
    sashimiValuePerKg: 45000,
    swimmingLayer: 'mid',
    isBoilingSpecies: false,
    description: '한국 찌낚시의 꽃. 해조류 무성한 내만성 갯바위의 잡식성 — 빵가루 경단에 반응이 좋다. 수온·소음에 극도로 예민해 이물감이 느껴지면 바로 뱉는 약은 입질의 대명사.',
  },
  {
    id: 'longtail_blackfish',
    nameKo: '긴꼬리벵에돔',
    nameEn: 'Japanese Largescale Blackfish',
    scientificName: 'Girella leonina',
    spriteKey: 'fish_longtail_blackfish',
    minLegalSizeCm: 0,   // 금지체장 없음 — 22~25cm 미만 자율 방생
    avgSizeRangeCm: [30, 45],
    maxRecordCm: 60,
    avgWeightRangeG: [800, 2000],
    preferredDepthM: [10, 30],
    preferredTempC: [19, 28],
    preferredBaits: ['prawn', 'bread', 'sandworm'],
    habitatSpotTypes: ['rocky_shore'],
    peakSeasonMonths: [6, 7, 8, 9, 10, 11],
    activeTidePhases: [6, 7, 8, 9, 10],
    isNocturnal: false,
    nightBiteBonus: 10,
    rarity: 'rare',
    difficulty: 5,
    sashimiValuePerKg: 55000,
    swimmingLayer: 'mid',
    isBoilingSpecies: false,
    description: '아가미 테두리의 검은 띠와 제비꼬리가 특징인 외양성 벵에돔. 난류를 좋아해 제주/남해 먼바다 섬에 분포. 육식 성향이 강해 크릴에 압도적으로 반응하며 이빨이 날카로워 목줄을 잘 끊는다.',
  },
  {
    id: 'black_seabream',
    nameKo: '감성돔',
    nameEn: 'Black Seabream',
    scientificName: 'Acanthopagrus schlegelii',
    spriteKey: 'fish_black_seabream',
    minLegalSizeCm: 25,
    avgSizeRangeCm: [25, 50],
    maxRecordCm: 73,
    avgWeightRangeG: [500, 3500],
    preferredDepthM: [2, 25],
    preferredTempC: [14, 25],
    preferredBaits: ['crab', 'mussel', 'barnacle', 'sandworm', 'earthworm'],
    habitatSpotTypes: ['breakwater', 'rocky_shore', 'beach'],
    peakSeasonMonths: [10, 11, 12, 1, 2, 3],
    activeTidePhases: [7, 8, 9, 10, 11],
    isNocturnal: true,
    nightBiteBonus: 40,
    rarity: 'uncommon',
    difficulty: 4,
    sashimiValuePerKg: 50000,
    swimmingLayer: 'bottom',
    isBoilingSpecies: false,
    description: '바다낚시 입문자부터 고수까지 모두 노리는 대상어. 조류가 강한 사리 전후로 대물이 나온다.',
  },
  {
    id: 'hairtail',
    nameKo: '갈치',
    nameEn: 'Hairtail',
    scientificName: 'Trichiurus japonicus',
    spriteKey: 'fish_hairtail',
    minLegalSizeCm: 47,   // 법정 기준 항문장 18cm → 전장 환산값 (게임은 전장으로 판정)
    avgSizeRangeCm: [40, 100],
    maxRecordCm: 230,
    avgWeightRangeG: [776, 2000],
    preferredDepthM: [20, 150],
    preferredTempC: [20, 30],
    preferredBaits: ['sandworm', 'squid', 'fish_strip', 'artificial_lure'],
    habitatSpotTypes: ['boat_fishing', 'breakwater'],
    peakSeasonMonths: [7, 8, 9, 10],
    isNocturnal: true,
    nightBiteBonus: 100,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 18000,
    swimmingLayer: 'surface',
    isBoilingSpecies: true,
    description: '집어등을 이용한 야간 방파제/선상 낚시의 핵심. 진흙·모래 바닥 위를 회유하며 여름엔 50~100m, 겨울엔 70~120m에 머문다. 4~6월 제주/서해, 7~10월 서해/남해로 회유. 법정 금지체장은 항문장 18cm(전장 약 47cm)이며 금어기는 7월 한 달.',
  },
  {
    id: 'yellowtail',
    nameKo: '방어',
    nameEn: 'Yellowtail',
    scientificName: 'Seriola quinqueradiata',
    spriteKey: 'fish_yellowtail',
    minLegalSizeCm: 30,
    avgSizeRangeCm: [40, 100],
    maxRecordCm: 150,
    avgWeightRangeG: [2000, 12000],
    preferredDepthM: [10, 60],
    preferredTempC: [18, 26],
    preferredBaits: ['artificial_lure', 'squid', 'fish_strip'],
    habitatSpotTypes: ['boat_fishing', 'rocky_shore'],
    peakSeasonMonths: [11, 12, 1],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'uncommon',
    difficulty: 3,
    sashimiValuePerKg: 35000,
    swimmingLayer: 'surface',
    isBoilingSpecies: true,
    description: '겨울철 대표 선상 지깅 대상어. 메탈지그로 공략하며 표층에서 집단으로 베이트피시를 몰고 다녀 화려한 보일링을 형성한다.',
  },
  {
    id: 'amberjack',
    nameKo: '부시리',
    nameEn: 'Japanese Amberjack',
    scientificName: 'Seriola lalandi',
    spriteKey: 'fish_amberjack',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [60, 120],
    maxRecordCm: 190,
    avgWeightRangeG: [5000, 20000],
    preferredDepthM: [5, 50],
    preferredTempC: [20, 28],
    preferredBaits: ['artificial_lure', 'fish_strip'],
    habitatSpotTypes: ['rocky_shore', 'boat_fishing'],
    peakSeasonMonths: [7, 8, 9, 10],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'rare',
    difficulty: 4,
    sashimiValuePerKg: 40000,
    swimmingLayer: 'surface',
    isBoilingSpecies: true,
    description: '방어보다 더 강한 파이팅의 대형 어종. 갯바위나 연안 표층을 빠른 속도로 헤엄쳐 다녀 큰 파장을 일으킨다.',
  },
  {
    id: 'rainbow_wrasse',
    nameKo: '용치놀래기',
    nameEn: 'Lyretail Wrasse',
    scientificName: 'Halichoeres poecilopterus',
    spriteKey: 'fish_wrasse',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [15, 35],
    maxRecordCm: 40,
    avgWeightRangeG: [100, 500],
    preferredDepthM: [2, 15],
    preferredTempC: [18, 28],
    preferredBaits: ['sandworm', 'earthworm', 'mussel'],
    habitatSpotTypes: ['rocky_shore', 'breakwater'],
    peakSeasonMonths: [5, 6, 7, 8, 9, 10],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'common',
    difficulty: 1,
    sashimiValuePerKg: 8000,
    swimmingLayer: 'mid',
    isBoilingSpecies: false,
    description: '방파제 입문 낚시의 단골 손님. 낚아도 먹기 껄끄러운 잡어지만 어린 낚시꾼들의 첫 물고기.',
  },
  {
    id: 'black_rockfish',
    nameKo: '조피볼락(우럭)',
    nameEn: 'Korean Rockfish',
    scientificName: 'Sebastes schlegeli',
    spriteKey: 'fish_black_rockfish',
    minLegalSizeCm: 23,
    avgSizeRangeCm: [20, 45],
    maxRecordCm: 65,
    avgWeightRangeG: [300, 2000],
    preferredDepthM: [5, 40],
    preferredTempC: [10, 20],
    preferredBaits: ['sandworm', 'prawn', 'fish_strip', 'artificial_worm'],
    habitatSpotTypes: ['rocky_shore', 'breakwater'],
    peakSeasonMonths: [11, 12, 1, 2, 3, 4, 5],
    isNocturnal: true,
    nightBiteBonus: 50,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 30000,
    swimmingLayer: 'bottom',
    isBoilingSpecies: false,
    description: '일명 우럭. 연안의 바위틈이나 방파제 테트라포드 주위에 서식하는 대표적인 락피시. 밤에 매우 활발히 먹이활동을 한다.',
  },
  {
    id: 'golden_rockfish',
    nameKo: '황볼락',
    nameEn: 'Yellow Rockfish',
    scientificName: 'Sebastes trivittatus',
    spriteKey: 'fish_golden_rockfish',
    minLegalSizeCm: 15,
    avgSizeRangeCm: [15, 25],
    maxRecordCm: 35,
    avgWeightRangeG: [100, 400],
    preferredDepthM: [5, 25],
    preferredTempC: [11, 19],
    preferredBaits: ['sandworm', 'prawn', 'artificial_worm'],
    habitatSpotTypes: ['rocky_shore'],
    peakSeasonMonths: [10, 11, 12, 1, 2, 3],
    isNocturnal: true,
    nightBiteBonus: 40,
    rarity: 'uncommon',
    difficulty: 2,
    sashimiValuePerKg: 28000,
    swimmingLayer: 'mid',
    isBoilingSpecies: false,
    description: '몸에 황갈색 세로띠가 있는 볼락류. 주로 갯바위 수중여와 암초 지대에 서식하며 야간 찌낚시에 반응이 좋다.',
  },
  {
    id: 'red_snapper_rockfish',
    nameKo: '열기(불볼락)',
    nameEn: 'Longspine Thornyhead',
    scientificName: 'Sebastes thompsoni',
    spriteKey: 'fish_red_snapper_rockfish',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [15, 30],
    maxRecordCm: 38,
    avgWeightRangeG: [100, 600],
    preferredDepthM: [15, 80],
    preferredTempC: [12, 18],
    preferredBaits: ['fish_strip', 'sandworm', 'squid'],
    habitatSpotTypes: ['boat_fishing', 'rocky_shore'],
    peakSeasonMonths: [12, 1, 2, 3, 4],
    isNocturnal: true,
    nightBiteBonus: 60,
    rarity: 'uncommon',
    difficulty: 2,
    sashimiValuePerKg: 22000,
    swimmingLayer: 'bottom',
    isBoilingSpecies: false,
    description: '표준명 불볼락. 무리를 지어 생활하는 습성이 있어 야간 선상 카드채비나 수중여 주변에서 다수 낚인다.',
  },
  {
    id: 'night_seabream',
    nameKo: '참돔 (야간)',
    nameEn: 'Red Sea Bream (Night)',
    scientificName: 'Pagrus major',
    spriteKey: 'fish_night_seabream',
    minLegalSizeCm: 24,
    avgSizeRangeCm: [20, 40],
    maxRecordCm: 55,
    avgWeightRangeG: [300, 1500],
    preferredDepthM: [5, 30],
    preferredTempC: [15, 23],
    preferredBaits: ['sandworm', 'prawn', 'crab', 'mussel'],
    habitatSpotTypes: ['breakwater', 'rocky_shore'],
    peakSeasonMonths: [5, 6, 7, 8, 9, 10, 11],
    isNocturnal: true,
    nightBiteBonus: 40,
    rarity: 'rare',
    difficulty: 3,
    sashimiValuePerKg: 35000,
    swimmingLayer: 'bottom',
    isBoilingSpecies: false,
    description: '밤에 경계심이 풀려 갯바위나 방파제 가장자리로 접근하는 참돔 소물. 밤낚시 찌낚시의 짜릿한 불청객.',
  },

  // ═══════════════════════════════════════════════════════════
  // 어종 마스터 21종 통합 추가분 (2026-07-16 — FishSpawningOracle과 ID 일치)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'stone_beakperch',
    nameKo: '돌돔',
    nameEn: 'Striped Beakperch',
    scientificName: 'Oplegnathus fasciatus',
    spriteKey: 'fish_stone_beakperch',
    minLegalSizeCm: 24,
    avgSizeRangeCm: [40, 60],
    maxRecordCm: 80,
    avgWeightRangeG: [1500, 4000],
    preferredDepthM: [5, 30],
    preferredTempC: [16, 26],
    preferredBaits: ['crab', 'sandworm', 'mussel', 'barnacle'],
    habitatSpotTypes: ['rocky_shore'],
    peakSeasonMonths: [6, 7, 8, 9, 10],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'rare',
    difficulty: 5,
    sashimiValuePerKg: 90000,
    swimmingLayer: 'bottom',
    description: '거친 여 밭의 제왕. 단단한 이빨로 성게 껍질째 깨부수는 갯바위 최고급 대상어. 수컷 성어는 주둥이가 검게 변한다(강구).',
  },
  {
    id: 'spotted_knifejaw',
    nameKo: '강담돔',
    nameEn: 'Spotted Knifejaw',
    scientificName: 'Oplegnathus punctatus',
    spriteKey: 'fish_spotted_knifejaw',
    minLegalSizeCm: 24,
    avgSizeRangeCm: [45, 65],
    maxRecordCm: 90,
    avgWeightRangeG: [1800, 5000],
    preferredDepthM: [10, 40],
    preferredTempC: [18, 27],
    preferredBaits: ['crab', 'sandworm', 'mussel'],
    habitatSpotTypes: ['rocky_shore'],
    peakSeasonMonths: [6, 7, 8, 9],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'epic',
    difficulty: 5,
    sashimiValuePerKg: 100000,
    swimmingLayer: 'bottom',
    description: '표범 무늬의 난류성 대물. 같은 체장의 돌돔보다 무겁다. 수컷 성어는 주둥이가 하얗게 변한다(백화).',
  },
  {
    id: 'red_seabream',
    nameKo: '참돔',
    nameEn: 'Red Seabream',
    scientificName: 'Pagrus major',
    spriteKey: 'fish_red_seabream',
    minLegalSizeCm: 25,
    avgSizeRangeCm: [40, 70],
    maxRecordCm: 100,
    avgWeightRangeG: [1200, 4500],
    preferredDepthM: [20, 100],
    preferredTempC: [15, 24],
    preferredBaits: ['sandworm', 'prawn', 'mussel', 'artificial_lure'],
    habitatSpotTypes: ['rocky_shore', 'boat_fishing'],
    peakSeasonMonths: [4, 5, 6, 9, 10, 11],
    activeTidePhases: [6, 7, 8, 9, 10],
    isNocturnal: false,
    nightBiteBonus: 20,
    rarity: 'uncommon',
    difficulty: 4,
    sashimiValuePerKg: 40000,
    swimmingLayer: 'mid',
    description: '바다의 왕. 암초와 모래가 섞인 깊은 수심의 회유어. 이마가 튀어나온 개체는 수컷 성어.',
  },
  {
    id: 'chub_mackerel',
    nameKo: '고등어',
    nameEn: 'Chub Mackerel',
    scientificName: 'Scomber japonicus',
    spriteKey: 'fish_chub_mackerel',
    minLegalSizeCm: 21,
    avgSizeRangeCm: [25, 40],
    maxRecordCm: 60,
    avgWeightRangeG: [400, 1000],
    preferredDepthM: [0, 300],
    preferredTempC: [14, 24],
    preferredBaits: ['prawn', 'sandworm', 'artificial_lure'],
    habitatSpotTypes: ['breakwater', 'boat_fishing'],
    peakSeasonMonths: [9, 10, 11],
    isNocturnal: false,
    nightBiteBonus: 20,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 15000,
    swimmingLayer: 'surface',
    isBoilingSpecies: true,
    description: '무리 지어 맹렬히 회유하는 등푸른 생선. 찌를 사방으로 끌고 다니는 방정맞은 입질이 특징. 7~12월 제주>전라>서해, 4~12월 제주>남해>일본으로 회유하며 금어기는 4~6월.',
  },
  {
    id: 'fine_puffer',
    nameKo: '졸복어',
    nameEn: 'Finepatterned Puffer',
    scientificName: 'Takifugu poecilonotus',
    spriteKey: 'fish_fine_puffer',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [8, 12],
    maxRecordCm: 15,
    avgWeightRangeG: [30, 80],
    preferredDepthM: [1, 10],
    preferredTempC: [12, 24],
    preferredBaits: ['prawn', 'sandworm', 'mussel'],
    habitatSpotTypes: ['breakwater', 'pier'],
    peakSeasonMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'common',
    difficulty: 1,
    sashimiValuePerKg: 0,
    swimmingLayer: 'bottom',
    description: '테트로도톡신 맹독을 지닌 미끼 도둑. 날카로운 이빨로 바늘과 목줄을 갉아 끊는다. 식용 불가.',
  },
  {
    id: 'tiger_puffer',
    nameKo: '참복어(자주복)',
    nameEn: 'Tiger Puffer',
    scientificName: 'Takifugu rubripes',
    spriteKey: 'fish_tiger_puffer',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [30, 50],
    maxRecordCm: 75,
    avgWeightRangeG: [1000, 3000],
    preferredDepthM: [10, 50],
    preferredTempC: [12, 22],
    preferredBaits: ['mussel', 'sandworm', 'prawn', 'fish_strip'],
    habitatSpotTypes: ['boat_fishing', 'breakwater'],
    peakSeasonMonths: [11, 12, 1, 2, 3],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'rare',
    difficulty: 3,
    sashimiValuePerKg: 120000,
    swimmingLayer: 'bottom',
    description: '고급 식재료지만 전신에 치명적인 맹독. 이빨 힘이 강해 와이어가 아니면 채비를 끊는다. 전문 조리 자격 필요.',
  },
  {
    id: 'conger_eel',
    nameKo: '붕장어',
    nameEn: 'Conger Eel',
    scientificName: 'Conger myriaster',
    spriteKey: 'fish_conger_eel',
    minLegalSizeCm: 35,
    avgSizeRangeCm: [40, 70],
    maxRecordCm: 100,
    avgWeightRangeG: [300, 1200],
    preferredDepthM: [5, 100],
    preferredTempC: [12, 24],
    preferredBaits: ['sandworm', 'fish_strip', 'squid'],
    habitatSpotTypes: ['beach', 'breakwater', 'boat_fishing'],
    peakSeasonMonths: [6, 7, 8, 9, 10],
    isNocturnal: true,
    nightBiteBonus: 90,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 30000,
    swimmingLayer: 'bottom',
    description: '야간 원투 낚시의 제왕(아나고). 60cm 넘는 용가리급은 99% 암컷. 잡히면 원줄을 몸으로 배배 꼬아버린다.',
  },
  {
    id: 'yellowfin_goby',
    nameKo: '문절망둑',
    nameEn: 'Yellowfin Goby',
    scientificName: 'Acanthogobius flavimanus',
    spriteKey: 'fish_yellowfin_goby',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [12, 18],
    maxRecordCm: 25,
    avgWeightRangeG: [40, 100],
    preferredDepthM: [0.5, 5],
    preferredTempC: [10, 26],
    preferredBaits: ['sandworm', 'earthworm', 'prawn'],
    habitatSpotTypes: ['tidal_flat', 'pier'],
    peakSeasonMonths: [9, 10, 11],
    isNocturnal: false,
    nightBiteBonus: 10,
    rarity: 'common',
    difficulty: 1,
    sashimiValuePerKg: 8000,
    swimmingLayer: 'bottom',
    description: '기수역·하구 진흙 바닥의 1년생 어종. 식탐이 엄청나 미끼를 넣자마자 삼킨다. 가을 생활낚시의 스타.',
  },
  {
    id: 'surfperch',
    nameKo: '망상어',
    nameEn: 'Surfperch',
    scientificName: 'Ditrema temminckii',
    spriteKey: 'fish_surfperch',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [18, 25],
    maxRecordCm: 30,
    avgWeightRangeG: [150, 350],
    preferredDepthM: [2, 10],
    preferredTempC: [10, 20],
    preferredBaits: ['prawn', 'sandworm'],
    habitatSpotTypes: ['breakwater', 'rocky_shore'],
    peakSeasonMonths: [11, 12, 1, 2, 3, 4],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'common',
    difficulty: 1,
    sashimiValuePerKg: 12000,
    swimmingLayer: 'mid',
    description: '태생(새끼를 낳는) 희귀 생태의 겨울 방파제 단골. 봄에 완전히 자란 새끼 수십 마리를 직접 출산한다.',
  },
  {
    id: 'scorpionfish',
    nameKo: '쏨뱅이',
    nameEn: 'False Kelpfish',
    scientificName: 'Sebastiscus marmoratus',
    spriteKey: 'fish_scorpionfish',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [15, 25],
    maxRecordCm: 35,
    avgWeightRangeG: [150, 450],
    preferredDepthM: [5, 40],
    preferredTempC: [13, 24],
    preferredBaits: ['fish_strip', 'sandworm', 'prawn'],
    habitatSpotTypes: ['rocky_shore', 'breakwater'],
    peakSeasonMonths: [11, 12, 1, 2, 3],
    isNocturnal: true,
    nightBiteBonus: 50,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 35000,
    swimmingLayer: 'bottom',
    description: '바위 틈에 도사리다 눈앞의 미끼를 순간 낚아채 틈새로 파고드는 여박기의 명수. 죽어도 맛있다는 남해 별미.',
  },
  {
    id: 'fat_greenling',
    nameKo: '쥐노래미',
    nameEn: 'Fat Greenling',
    scientificName: 'Hexagrammos otakii',
    spriteKey: 'fish_fat_greenling',
    minLegalSizeCm: 20,
    avgSizeRangeCm: [25, 45],
    maxRecordCm: 65,
    avgWeightRangeG: [200, 1200],
    preferredDepthM: [2, 30],
    preferredTempC: [10, 22],
    preferredBaits: ['sandworm', 'prawn', 'crab'],
    habitatSpotTypes: ['rocky_shore', 'breakwater'],
    peakSeasonMonths: [4, 5, 6, 9, 10],
    isNocturnal: false,
    nightBiteBonus: 10,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 30000,
    swimmingLayer: 'bottom',
    description: '해조류 여 밭의 터줏대감. 산란기 수컷은 황금색 혼인색으로 변해 알을 지킨다. 금어기 11~12월.',
  },
  {
    id: 'greenling',
    nameKo: '노래미',
    nameEn: 'Spotty Belly Greenling',
    scientificName: 'Hexagrammos agrammus',
    spriteKey: 'fish_greenling',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [15, 22],
    maxRecordCm: 30,
    avgWeightRangeG: [100, 250],
    preferredDepthM: [1, 15],
    preferredTempC: [10, 22],
    preferredBaits: ['sandworm', 'prawn', 'mussel'],
    habitatSpotTypes: ['rocky_shore', 'breakwater', 'pier'],
    peakSeasonMonths: [3, 4, 5, 10, 11],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'common',
    difficulty: 1,
    sashimiValuePerKg: 20000,
    swimmingLayer: 'bottom',
    description: '얕은 연안 돌바닥의 친근한 손님. 쥐노래미와 달리 측선이 1개뿐이고 꼬리 끝이 둥근 부채꼴.',
  },
  {
    id: 'blue_rockfish',
    nameKo: '청볼락',
    nameEn: 'Blue Rockfish',
    scientificName: 'Sebastes ventricosus',
    spriteKey: 'fish_blue_rockfish',
    minLegalSizeCm: 15,
    avgSizeRangeCm: [15, 22],
    maxRecordCm: 30,
    avgWeightRangeG: [120, 300],
    preferredDepthM: [2, 15],
    preferredTempC: [12, 20],
    preferredBaits: ['prawn', 'artificial_worm', 'sandworm'],
    habitatSpotTypes: ['rocky_shore', 'breakwater'],
    peakSeasonMonths: [12, 1, 2, 3, 4],
    activeTidePhases: [6, 7, 8, 9, 10],
    isNocturnal: true,
    nightBiteBonus: 40,
    rarity: 'uncommon',
    difficulty: 2,
    sashimiValuePerKg: 28000,
    swimmingLayer: 'mid',
    isBoilingSpecies: true,
    description: '바닥에 붙지 않고 중층에 무리 지어 피어올라 조류를 타는 회유성 볼락. 찌낚시의 주 타겟.',
  },
  {
    id: 'flatfish',
    nameKo: '광어(넙치)',
    nameEn: 'Olive Flounder',
    scientificName: 'Paralichthys olivaceus',
    spriteKey: 'fish_flatfish',
    minLegalSizeCm: 35,
    avgSizeRangeCm: [40, 60],
    maxRecordCm: 120,
    avgWeightRangeG: [760, 3000],
    preferredDepthM: [10, 200],
    preferredTempC: [10, 24],
    preferredBaits: ['fish_strip', 'artificial_lure', 'artificial_worm', 'sandworm'],
    habitatSpotTypes: ['beach', 'boat_fishing', 'breakwater'],
    peakSeasonMonths: [10, 11, 12, 1, 2],
    isNocturnal: false,
    nightBiteBonus: 10,
    rarity: 'uncommon',
    difficulty: 3,
    sashimiValuePerKg: 35000,
    swimmingLayer: 'bottom',
    description: '모래 속에 몸을 숨기고 있다가 미끼가 위를 지날 때 폭발적으로 솟구치는 국민 횟감. 두 눈이 왼쪽. 7~12월 제주>서해>제주, 4~6월 제주>남해>동해로 회유. 금지체장 35cm.',
  },
  {
    id: 'flounder',
    nameKo: '참도다리(문치가자미)',
    nameEn: 'Marbled Flounder',
    scientificName: 'Pseudopleuronectes yokohamae',
    spriteKey: 'fish_flounder',
    minLegalSizeCm: 20,
    avgSizeRangeCm: [25, 35],
    maxRecordCm: 50,
    avgWeightRangeG: [300, 1900],
    preferredDepthM: [10, 100],
    preferredTempC: [8, 20],
    preferredBaits: ['sandworm', 'earthworm'],
    habitatSpotTypes: ['beach', 'boat_fishing', 'tidal_flat'],
    peakSeasonMonths: [3, 4, 5, 6],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 30000,
    swimmingLayer: 'bottom',
    description: '봄 도다리 쑥국의 주인공. 광어와 반대로 두 눈이 오른쪽. 입이 작고 예민해 소형 바늘 원투에 잘 잡힌다. 모래·뻘 10~100m의 대한민국 전 해역에 분포하며 시장에서 흔히 도다리로 유통된다. 금어기 12~1월.',
  },
  {
    id: 'sea_bass',
    nameKo: '농어',
    nameEn: 'Japanese Seabass',
    scientificName: 'Lateolabrax japonicus',
    spriteKey: 'fish_sea_bass',
    minLegalSizeCm: 30,
    avgSizeRangeCm: [40, 80],
    maxRecordCm: 110,
    avgWeightRangeG: [800, 5000],
    preferredDepthM: [1, 30],
    preferredTempC: [14, 26],
    preferredBaits: ['artificial_lure', 'fish_strip', 'prawn'],
    habitatSpotTypes: ['rocky_shore', 'breakwater', 'beach'],
    peakSeasonMonths: [6, 7, 8, 9, 10],
    isNocturnal: true,
    nightBiteBonus: 50,
    rarity: 'uncommon',
    difficulty: 4,
    sashimiValuePerKg: 30000,
    swimmingLayer: 'mid',
    isBoilingSpecies: true,
    description: '루어 낚시의 제왕. 여름밤 연안으로 붙어 베이트를 사냥하며 화려한 에라 세척(점프 바늘털이)을 보여준다.',
  },
  {
    id: 'striped_mullet',
    nameKo: '참숭어(숭어)',
    nameEn: 'Flathead Grey Mullet',
    scientificName: 'Mugil cephalus',
    spriteKey: 'fish_striped_mullet',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [40, 60],
    maxRecordCm: 80,
    avgWeightRangeG: [1500, 3000],
    preferredDepthM: [0.5, 10],
    preferredTempC: [8, 26],
    preferredBaits: ['sandworm', 'prawn', 'bread'],
    habitatSpotTypes: ['rocky_shore', 'breakwater', 'tidal_flat'],
    peakSeasonMonths: [3, 4, 5],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 15000,
    swimmingLayer: 'surface',
    isBoilingSpecies: true,
    description: '눈동자가 검고 꼬리가 V자로 깊게 갈라진 표층 회유어(방언: 개숭어). 보리 익을 무렵(3~5월)이 제철이라 보리숭어라 불린다. 겨울엔 눈에 기름눈꺼풀(백태)이 낀다.',
  },
  {
    id: 'redlip_mullet',
    nameKo: '가숭어(밀치)',
    nameEn: 'Redlip Mullet',
    scientificName: 'Chelon haematocheilus',
    spriteKey: 'fish_redlip_mullet',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [50, 80],
    maxRecordCm: 100,
    avgWeightRangeG: [2000, 5000],
    preferredDepthM: [1, 15],
    preferredTempC: [6, 24],
    preferredBaits: ['sandworm', 'prawn', 'bread'],
    habitatSpotTypes: ['tidal_flat', 'pier', 'breakwater'],
    peakSeasonMonths: [11, 12, 1, 2],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'common',
    difficulty: 3,
    sashimiValuePerKg: 20000,
    swimmingLayer: 'surface',
    isBoilingSpecies: true,
    description: '눈 테두리가 선명한 노란색인 숭어류 최대종(방언: 참숭어). 진흙 섞인 연안과 강 하구에 무리 짓는다. 산란기 5~6월, 겨울(11~2월) 기름 오른 밀치회가 별미.',
  },

  // ═══════════════════════════════════════════════════════════
  // 신규 어종 12종 (2026-07-16 사용자 제공 실측 데이터)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'frog_flounder',
    nameKo: '도다리',
    nameEn: 'Frog Flounder',
    scientificName: 'Pleuronichthys cornutus',
    spriteKey: 'fish_frog_flounder',
    minLegalSizeCm: 20,
    avgSizeRangeCm: [25, 30],
    maxRecordCm: 40,
    avgWeightRangeG: [300, 1000],
    preferredDepthM: [50, 100],
    preferredTempC: [8, 20],
    preferredBaits: ['sandworm', 'earthworm'],
    habitatSpotTypes: ['boat_fishing', 'beach'],
    peakSeasonMonths: [3, 4, 5, 6],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'uncommon',
    difficulty: 2,
    sashimiValuePerKg: 32000,
    swimmingLayer: 'bottom',
    description: '눈 사이에 가시가 솟은 표준명 도다리. 문치가자미와 달리 군산·목포·여수·마산·진해·부산 등 남해 서부에 국지 분포한다. 모래·뻘 50~100m.',
  },
  {
    id: 'starry_flounder',
    nameKo: '강도다리',
    nameEn: 'Starry Flounder',
    scientificName: 'Platichthys stellatus',
    spriteKey: 'fish_starry_flounder',
    minLegalSizeCm: 0,   // 금지체장 없음 — 14cm 미만 자율 방생 권장
    avgSizeRangeCm: [20, 60],
    maxRecordCm: 100,
    avgWeightRangeG: [300, 9000],
    preferredDepthM: [20, 250],
    preferredTempC: [4, 16],
    preferredBaits: ['sandworm', 'earthworm', 'prawn'],
    habitatSpotTypes: ['beach', 'boat_fishing', 'tidal_flat'],
    peakSeasonMonths: [11, 12, 1, 2, 3],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'uncommon',
    difficulty: 2,
    sashimiValuePerKg: 26000,
    swimmingLayer: 'bottom',
    description: '지느러미의 검은 줄무늬가 선명한 냉수성 가자미. 20~40cm급은 전 해역의 기수지역(주로 울산 강 하구)에 붙는다. 모래·뻘 20~250m.',
  },
  {
    id: 'tonguefish',
    nameKo: '개서대',
    nameEn: 'Robust Tonguefish',
    scientificName: 'Cynoglossus robustus',
    spriteKey: 'fish_tonguefish',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [25, 40],
    maxRecordCm: 60,
    avgWeightRangeG: [300, 1000],
    preferredDepthM: [20, 100],
    preferredTempC: [10, 24],
    preferredBaits: ['sandworm', 'earthworm', 'mussel'],
    habitatSpotTypes: ['beach', 'boat_fishing', 'tidal_flat'],
    peakSeasonMonths: [4, 5, 6, 7, 8, 9, 10],
    isNocturnal: true,
    nightBiteBonus: 60,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 24000,
    swimmingLayer: 'bottom',
    description: '혓바닥처럼 길쭉한 서대류. 진흙·갯벌·모래 20~100m에 붙으며 입이 작아 미끼를 빨아들이듯 삼킨다. 4~6월 제주/서해, 7~10월 서해/남해로 회유.',
  },
  {
    id: 'pike_conger',
    nameKo: '갯장어',
    nameEn: 'Daggertooth Pike Conger',
    scientificName: 'Muraenesox cinereus',
    spriteKey: 'fish_pike_conger',
    minLegalSizeCm: 40,
    avgSizeRangeCm: [60, 80],
    maxRecordCm: 200,
    avgWeightRangeG: [150, 200],
    preferredDepthM: [20, 50],
    preferredTempC: [16, 27],
    preferredBaits: ['fish_strip', 'squid', 'live_fish'],
    habitatSpotTypes: ['boat_fishing', 'rocky_shore'],
    peakSeasonMonths: [5, 6, 7, 8],
    isNocturnal: true,
    nightBiteBonus: 50,
    rarity: 'rare',
    difficulty: 4,
    sashimiValuePerKg: 70000,
    swimmingLayer: 'bottom',
    description: '여름 남해의 최고급 별미 하모. 단검 같은 이빨로 목줄을 단숨에 끊고 손까지 물어뜯는 난폭한 장어. 모래·암초 20~50m. 4~7월 제주>서해, 10~12월 서해>제주 회유하며 남해/동해에도 소규모 분포.',
  },
  {
    id: 'pacific_saury',
    nameKo: '꽁치',
    nameEn: 'Pacific Saury',
    scientificName: 'Cololabis saira',
    spriteKey: 'fish_pacific_saury',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [30, 40],
    maxRecordCm: 50,
    avgWeightRangeG: [100, 140],
    preferredDepthM: [0, 50],
    preferredTempC: [10, 20],
    preferredBaits: ['prawn', 'artificial_lure', 'sandworm'],
    habitatSpotTypes: ['boat_fishing', 'breakwater'],
    peakSeasonMonths: [4, 5, 6, 9, 10, 11],
    isNocturnal: true,
    nightBiteBonus: 70,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 12000,
    swimmingLayer: 'surface',
    isBoilingSpecies: true,
    description: '표층·중층 0~50m를 빠르게 스치는 가늘고 긴 등푸른 회유어. 집어등 불빛에 몰린다. 4~7월 제주>남해>동해>북한, 9~12월 동해>남해>제주>일본으로 회유.',
  },
  {
    id: 'blackthroat_seaperch',
    nameKo: '눈볼대(금태)',
    nameEn: 'Blackthroat Seaperch',
    scientificName: 'Doederleinia berycoides',
    spriteKey: 'fish_blackthroat_seaperch',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [25, 30],
    maxRecordCm: 50,
    avgWeightRangeG: [300, 1000],
    preferredDepthM: [100, 400],
    preferredTempC: [10, 20],
    preferredBaits: ['fish_strip', 'squid', 'live_fish', 'artificial_lure'],
    habitatSpotTypes: ['boat_fishing'],
    peakSeasonMonths: [10, 11, 12, 1, 2],
    isNocturnal: true,
    nightBiteBonus: 50,
    rarity: 'rare',
    difficulty: 3,
    sashimiValuePerKg: 80000,
    swimmingLayer: 'bottom',
    description: '아카무츠라 불리는 심해 고급어. 목구멍이 검고 눈이 크며 기름기가 풍부해 최고급 횟감으로 친다. 모래·진흙 저층 100~400m(10~20°C). 7~8월 제주, 8~6월 제주>남해>일본 회유.',
  },
  {
    id: 'round_herring',
    nameKo: '눈퉁멸',
    nameEn: 'Round Herring',
    scientificName: 'Etrumeus micropus',
    spriteKey: 'fish_round_herring',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [15, 20],
    maxRecordCm: 30,
    avgWeightRangeG: [30, 100],
    preferredDepthM: [50, 150],
    preferredTempC: [12, 24],
    preferredBaits: ['prawn', 'artificial_lure', 'sandworm'],
    habitatSpotTypes: ['boat_fishing', 'breakwater'],
    peakSeasonMonths: [1, 2, 3, 4, 5, 6],
    isNocturnal: true,
    nightBiteBonus: 60,
    rarity: 'common',
    difficulty: 1,
    sashimiValuePerKg: 6000,
    swimmingLayer: 'surface',
    isBoilingSpecies: true,
    description: '눈이 유난히 큰 소형 청어류. 표층·중층 50~150m에 대군을 이루며 대형어의 주 먹이(베이트피시)라 생미끼로도 쓰인다. 12월 제주/남해, 1~8월 일본>남해>제주 회유.',
  },
  {
    id: 'pacific_cod',
    nameKo: '대구',
    nameEn: 'Pacific Cod',
    scientificName: 'Gadus macrocephalus',
    spriteKey: 'fish_pacific_cod',
    minLegalSizeCm: 35,
    avgSizeRangeCm: [40, 60],
    maxRecordCm: 120,
    avgWeightRangeG: [2500, 5000],
    preferredDepthM: [45, 450],
    preferredTempC: [2, 12],
    preferredBaits: ['live_fish', 'fish_strip', 'artificial_lure', 'squid'],
    habitatSpotTypes: ['boat_fishing'],
    peakSeasonMonths: [12, 1, 2],
    isNocturnal: false,
    nightBiteBonus: 20,
    rarity: 'uncommon',
    difficulty: 4,
    sashimiValuePerKg: 20000,
    swimmingLayer: 'bottom',
    description: '입이 머리만큼 큰 한류성 대형 저서어. 겨울 거제·진해 대구탕의 주인공으로 주로 남해에 분포한다. 45~450m. 12월 제주/남해, 1~8월 일본>남해>제주 회유. 금어기 1/16~2/15.',
  },
  {
    id: 'korean_pomfret',
    nameKo: '덕대',
    nameEn: 'Korean Pomfret',
    scientificName: 'Pampus echinogaster',
    spriteKey: 'fish_korean_pomfret',
    minLegalSizeCm: 0,   // 금지체장 없음 — 14cm 미만 자율 방생 권장
    avgSizeRangeCm: [14, 20],
    maxRecordCm: 40,
    avgWeightRangeG: [200, 450],
    preferredDepthM: [0, 100],
    preferredTempC: [14, 26],
    preferredBaits: ['prawn', 'sandworm', 'mussel'],
    habitatSpotTypes: ['boat_fishing', 'beach'],
    peakSeasonMonths: [6, 7, 8, 9],
    isNocturnal: false,
    nightBiteBonus: 10,
    rarity: 'uncommon',
    difficulty: 3,
    sashimiValuePerKg: 30000,
    swimmingLayer: 'mid',
    description: '병어와 쏙 닮은 소형종. 입이 아주 작아 큰 바늘에는 걸리지 않는다. 모래·뻘 0~100m의 남해/서해에 6~9월 분포.',
  },
  {
    id: 'silver_pomfret',
    nameKo: '병어',
    nameEn: 'Silver Pomfret',
    scientificName: 'Pampus argenteus',
    spriteKey: 'fish_silver_pomfret',
    minLegalSizeCm: 0,   // 금지체장 없음 — 14.6cm 미만 자율 방생 권장
    avgSizeRangeCm: [20, 30],
    maxRecordCm: 60,
    avgWeightRangeG: [240, 1000],
    preferredDepthM: [0, 100],
    preferredTempC: [14, 26],
    preferredBaits: ['prawn', 'sandworm', 'mussel'],
    habitatSpotTypes: ['boat_fishing', 'beach'],
    peakSeasonMonths: [6, 7, 8, 9],
    isNocturnal: false,
    nightBiteBonus: 10,
    rarity: 'common',
    difficulty: 3,
    sashimiValuePerKg: 35000,
    swimmingLayer: 'mid',
    description: '납작한 마름모꼴 은빛 몸통에 뼈가 연해 통째로 썰어 먹는 여름 별미. 모래·뻘 0~100m의 남해/서해에 6~9월 분포 및 회유.',
  },
  {
    id: 'sandfish',
    nameKo: '도루묵',
    nameEn: 'Japanese Sandfish',
    scientificName: 'Arctoscopus japonicus',
    spriteKey: 'fish_sandfish',
    minLegalSizeCm: 11,
    avgSizeRangeCm: [15, 20],
    maxRecordCm: 30,
    avgWeightRangeG: [50, 100],
    preferredDepthM: [2, 150],
    preferredTempC: [2, 12],
    preferredBaits: ['prawn', 'sandworm', 'artificial_worm'],
    habitatSpotTypes: ['breakwater', 'beach', 'boat_fishing'],
    peakSeasonMonths: [11, 12],
    isNocturnal: true,
    nightBiteBonus: 40,
    rarity: 'common',
    difficulty: 1,
    sashimiValuePerKg: 10000,
    swimmingLayer: 'bottom',
    description: '평소 모래·진흙 140~150m에 살다가 10~12월 산란을 위해 동해 연안 2~10m 해조류로 몰려든다. 알이 가득 찬 암컷이 별미.',
  },
  {
    id: 'black_scraper',
    nameKo: '말쥐치',
    nameEn: 'Black Scraper',
    scientificName: 'Thamnaconus modestus',
    spriteKey: 'fish_black_scraper',
    minLegalSizeCm: 18,
    avgSizeRangeCm: [20, 25],
    maxRecordCm: 36,
    avgWeightRangeG: [200, 250],
    preferredDepthM: [20, 100],
    preferredTempC: [12, 24],
    preferredBaits: ['mussel', 'prawn', 'sandworm'],
    habitatSpotTypes: ['rocky_shore', 'breakwater', 'boat_fishing'],
    peakSeasonMonths: [10, 11, 12, 1, 2],
    isNocturnal: false,
    nightBiteBonus: 10,
    rarity: 'common',
    difficulty: 3,
    sashimiValuePerKg: 18000,
    swimmingLayer: 'mid',
    description: '쥐치보다 크고 길쭉한 쥐포의 주 원료. 작은 입으로 미끼만 갉아먹는 악명 높은 미끼 도둑. 내만·암초·해조류 70~100m. 1~3월 제주, 4~11월 남해>동해, 6~10월 제주>서해 회유. 금어기 5~7월.',
  },

  // ═══════════════════════════════════════════════════════════
  // 오라클 미등록분 해소 2종 (2026-07-16 사용자 제공)
  // — 기존에 FishSpawningOracle에만 있어 도감 조회가 불가했던 어종
  // ═══════════════════════════════════════════════════════════
  {
    id: 'horse_mackerel',
    nameKo: '전갱이',
    nameEn: 'Japanese Horse Mackerel',
    scientificName: 'Trachurus japonicus',
    spriteKey: 'fish_horse_mackerel',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [15, 30],
    maxRecordCm: 50,
    avgWeightRangeG: [80, 400],
    preferredDepthM: [5, 50],
    preferredTempC: [16, 25],
    // 원 데이터의 'krill'은 BaitCategory에 없어 냉동 크릴(krill_frozen)로 매핑
    preferredBaits: ['krill_frozen', 'prawn', 'artificial_worm'],
    // 원 데이터의 'boat'는 SpotType에 없어 boat_fishing으로 매핑
    habitatSpotTypes: ['breakwater', 'boat_fishing'],
    peakSeasonMonths: [6, 7, 8, 9, 10, 11],
    isNocturnal: true,
    nightBiteBonus: 40,
    rarity: 'common',
    difficulty: 1,
    sashimiValuePerKg: 16000,
    swimmingLayer: 'mid',
    isBoilingSpecies: false,
    description: '연안을 회유하는 대표적인 등푸른 생선. 무리를 지어 다니며 방파제나 선상에서 카고·사비키 채비로 노린다. 야간 집어등 불빛에 강하게 반응해 밤낚시 대상어로 인기가 높다.',
  },
  {
    id: 'filefish',
    nameKo: '쥐치',
    nameEn: 'Thread-sail Filefish',
    scientificName: 'Stephanolepis cirrhifer',
    spriteKey: 'fish_filefish',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [10, 25],
    maxRecordCm: 30,
    avgWeightRangeG: [50, 300],
    preferredDepthM: [5, 30],
    preferredTempC: [15, 25],
    preferredBaits: ['sandworm', 'prawn', 'krill_frozen'],
    habitatSpotTypes: ['rocky_shore', 'breakwater'],
    peakSeasonMonths: [7, 8, 9, 10, 11],
    isNocturnal: false,
    nightBiteBonus: 0,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 20000,
    swimmingLayer: 'mid',
    isBoilingSpecies: false,
    description: '작고 오므린 입으로 미끼만 톡톡 따먹어 "미끼 도둑"으로 불리는 어종. 여름~가을 방파제와 갯바위 수중여 주변에 흔하다. 입질 파악이 까다로워 예민한 채비가 필요하며, 살과 간이 별미로 회·조림 대상어로 친다.',
  },

  // ── 루어/지깅 중대형 + 두족류 (2026-07 리서치 — 오라클 표준 id) ──
  {
    id: 'greater_amberjack',
    nameKo: '잿방어',
    nameEn: 'Greater Amberjack',
    scientificName: 'Seriola dumerili',
    spriteKey: 'fish_greater_amberjack',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [60, 120],
    maxRecordCm: 200,
    avgWeightRangeG: [5000, 25000],
    preferredDepthM: [30, 150],
    preferredTempC: [18, 26],
    preferredBaits: ['artificial_lure', 'live_fish'],
    habitatSpotTypes: ['boat_fishing'],
    peakSeasonMonths: [6, 7, 8, 9, 10],
    isNocturnal: false,
    nightBiteBonus: 5,
    rarity: 'rare',
    difficulty: 5,
    sashimiValuePerKg: 22000,
    swimmingLayer: 'mid',
    isBoilingSpecies: true,
    description: "'바다의 폭군'. 방어·부시리보다 힘이 세고 최대 2m·40kg급까지 자라는 심해 지깅 대물. 여름~가을 남해·제주 급심에서 대형 메탈지그에 반응한다. 이마가 각지고 눈을 가로지르는 사선 줄무늬로 방어와 구분한다.",
  },
  {
    id: 'spanish_mackerel',
    nameKo: '삼치',
    nameEn: 'Japanese Spanish Mackerel',
    scientificName: 'Scomberomorus niphonius',
    spriteKey: 'fish_spanish_mackerel',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [50, 80],
    maxRecordCm: 100,
    avgWeightRangeG: [1000, 5000],
    preferredDepthM: [0, 50],
    preferredTempC: [16, 24],
    preferredBaits: ['artificial_lure', 'chilled_fish_strip'],
    habitatSpotTypes: ['boat_fishing', 'breakwater'],
    peakSeasonMonths: [9, 10, 11],
    isNocturnal: false,
    nightBiteBonus: 15,
    rarity: 'uncommon',
    difficulty: 3,
    sashimiValuePerKg: 20000,
    swimmingLayer: 'surface',
    isBoilingSpecies: true,
    description: '표층을 고속 회유하는 이빨 포식자. 메탈지그·스푼 고속 릴링에 반응하며 해뜰녘·해질녘 1~2시간에 입질이 집중된다. 5월 금어기. 이빨에 목줄이 쓸리기 쉬워 굵은 쇼크리더가 필수다.',
  },
  {
    id: 'cuttlefish',
    nameKo: '갑오징어',
    nameEn: 'Cuttlefish',
    scientificName: 'Sepia esculenta',
    spriteKey: 'fish_cuttlefish',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [10, 20],
    maxRecordCm: 30,
    avgWeightRangeG: [200, 1500],
    preferredDepthM: [5, 50],
    preferredTempC: [12, 24],
    preferredBaits: ['artificial_lure'],
    habitatSpotTypes: ['breakwater', 'beach'],
    peakSeasonMonths: [4, 5, 9, 10, 11],
    isNocturnal: false,
    nightBiteBonus: 20,
    rarity: 'common',
    difficulty: 2,
    sashimiValuePerKg: 22000,
    swimmingLayer: 'bottom',
    isBoilingSpecies: false,
    description: '바닥에서 20~50cm 단차로 붙는 연안 에깅 대상. 봄·가을 시즌에 에기 2.5~3.5호로 얕은 연안에서도 잘 낚인다. 주야 무관하게 먹는 에깅 입문 어종.',
  },
  {
    id: 'squid',
    nameKo: '무늬오징어',
    nameEn: 'Bigfin Reef Squid',
    scientificName: 'Sepioteuthis lessoniana',
    spriteKey: 'fish_bigfin_squid',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [15, 30],
    maxRecordCm: 45,
    avgWeightRangeG: [300, 3000],
    preferredDepthM: [1, 30],
    preferredTempC: [15, 24],
    preferredBaits: ['artificial_lure'],
    habitatSpotTypes: ['rocky_shore', 'breakwater'],
    peakSeasonMonths: [9, 10, 11, 12],
    isNocturnal: true,
    nightBiteBonus: 50,
    rarity: 'uncommon',
    difficulty: 3,
    sashimiValuePerKg: 25000,
    swimmingLayer: 'mid',
    isBoilingSpecies: false,
    description: '에깅의 꽃. 가을 연안 시즌과 봄 대형 산란기가 최성기다. 밤이면 얕은 곳으로 붙으며 에기 폴링에 달려든다. 제주권에서는 3kg 오버 대형도 나온다.',
  },
  {
    id: 'octopus',
    nameKo: '문어',
    nameEn: 'Common Octopus',
    scientificName: 'Octopus vulgaris',
    spriteKey: 'fish_octopus',
    minLegalSizeCm: 0,
    avgSizeRangeCm: [25, 60],
    maxRecordCm: 100,
    avgWeightRangeG: [500, 5000],
    preferredDepthM: [2, 25],
    preferredTempC: [12, 22],
    preferredBaits: ['artificial_lure', 'crab'],
    habitatSpotTypes: ['rocky_shore', 'breakwater'],
    peakSeasonMonths: [5, 6, 10, 11],
    isNocturnal: true,
    nightBiteBonus: 40,
    rarity: 'uncommon',
    difficulty: 3,
    sashimiValuePerKg: 28000,
    swimmingLayer: 'bottom',
    isBoilingSpecies: false,
    description: '암초·구조물 바닥에 붙는 두족류. 에기·문어볼로 바닥을 노리며, 붙는 힘이 강해 초반에 바닥에서 띄우는 것이 관건이다. 밤에 은신처를 벗어나 사냥한다.',
  },
];

export function getFishById(id: string): FishSpecies | undefined {
  return FISH_DATABASE.find((f) => f.id === id);
}

export function getFishBySpotType(spotType: SpotType): FishSpecies[] {
  return FISH_DATABASE.filter((f) => f.habitatSpotTypes.includes(spotType));
}

export function getFishByMonth(month: number): FishSpecies[] {
  return FISH_DATABASE.filter((f) => f.peakSeasonMonths.includes(month));
}
