/**
 * @file StoryChoicesEn.ts
 * @description 퀘스트 선택지 영문 원고 — `StoryNarrative.ts`의 짝 파일 (152차)
 *
 * 151차가 나레이션 186편을 영문화하면서 **선택지는 `labelEn = labelKo` 폴백으로 남겼다**.
 * 이 파일이 그 빚을 갚는다. 구조는 나레이션과 같다 — 한국어 원고는 한 글자도 건드리지 않고,
 * 같은 키를 쓰는 짝 파일의 영문을 `mergedNarrative()`가 `labelEn`/`replyEn`에 얹는다.
 *
 * 키 = `"<퀘스트 id>/<선택지 id>"`. 값 = `[영문 라벨, 영문 응답]`.
 * 없는 키는 그대로 한국어가 남는다(미수록 규칙) — 표준 선택지(`StoryChoices.ts`)는 처음부터 영문을 갖고 있다.
 *
 * 번역 규칙 (151차 `StoryNarrativeEn.ts` §번역 규칙과 동일)
 *  - 선택지 라벨 = 플레이어가 **입으로 하는 말**. 1인칭 현재형, 짧게. 괄호 지문은 괄호 그대로.
 *  - 응답 = NPC의 말투를 지킨다(고만석은 짧고 무뚝뚝, 도현수는 날 세운 반말, 하늬는 다정).
 *  - 고유명사는 로마자(Sokcho, Yeonggeumjeong, Do Hyeonsu) · 단위는 원문 그대로(cm, kg, 원).
 */

export const STORY_CHOICES_EN: Record<string, [string, string]> = {
  'N20-2/c/lesson': ['I\'d like to learn framing too.', 'Sun on the left, the person on the right. (How I look at people shifts a little.)'],
  'N20-3/c/keep_cut': ['Keep that cut in.', 'Yes! That cut is the thumbnail! (I heard later that the stall grandmother saw herself in it and laughed.)'],
  'N20-3/c/pay': ['I\'ll take the collab fee.', 'This time there really is one! Over a thousand subscribers! (For once the envelope is a proper envelope.)'],
  'N20-3/c/lesson': ['I\'d like to learn where you look when you film people.', 'The hands. Not the face. (I get an eye for people\'s hands.)'],
  'N20-4/c/explain': ['I gave the reason on camera. That\'s broadcasting.', '…That\'s broadcasting. I\'ve learned that. (That video stayed up longest on her channel.)'],
  'N20-4/c/lesson': ['Let\'s work out together how to show a closed-season fish on camera.', 'Film the rule with it. The numbers. (Measurement broadcasts become a thing.)'],
  'N20-4/c/pay': ['I\'ll take it as an appearance fee.', 'Yes… this video\'s revenue. The release video earned the most, oddly. (The envelope is thick.)'],
  'N20-5/c/offline': ['Nothing to upload, but something left over. You\'re right about that.', '…That\'s the next video\'s title. No — I won\'t upload it. (One subscriber knows my name.)'],
  'N20-5/c/lesson': ['You taught your subscribers to hold a rod better than I could.', 'I\'m a YouTuber. Explaining is the job. (I get a little better at teaching.)'],
  'N20-5/c/pay': ['I\'ll take the guiding fee for the meetup.', 'Yes! The subscribers chipped in! (It\'s an envelope many hands filled.)'],
  'N20-6/c/zero': ['Zero viewers. It was still a broadcast.', '…It was. (She gives me the recording. The only copy, she says.)'],
  'N20-6/c/lesson': ['Talking when nobody\'s watching — I couldn\'t. How do you do it?', 'I picture one person past the lens. Always one. (Fishing alone feels less lonely.)'],
  'N20-6/c/pay': ['Full rate for the Dokdo guiding.', 'Full rate! All of the last ad revenue! (The envelope feels like a last one.)'],
  'N20-7/c/cut': ['The moment with zero viewers. That\'s the cut.', '…That was my cut too. (She gives me the tripod. The one from her first stream. She\'ll buy a new one at the new harbour.)'],
  'N20-7/c/next_port': ['Tell me the next harbour when you\'ve picked it. I\'ll come by boat.', '…Really? Then I\'ll tell you. When I\'ve picked it. (Postcards come from every harbour after that.)'],
  'N20-7/c/pay': ['A fee for picking the cut… I\'m joking.', 'I\'ll pay it! Last video\'s revenue! The one with no subtitles earned most! (The envelope feels like a last one.)'],
  'N22-1/c/lesson': ['I\'d like to learn how to finish it smooth.', 'It\'s the sanding direction. With the grain. (My hands begin to read grain.)'],
  'N22-1/c/pay': ['I paid for the materials, so I\'ll take the wage.', 'Right. Labour is labour. (It goes on the first line of the workshop ledger.)'],
  'N22-1/c/decline': ['I learned something. That\'s enough.', '…No workshop customer has said that before. (A space on the bench becomes mine.)'],
  'N22-2/c/lesson': ['I\'d like to learn why the furniture belongs where you put it.', 'It\'s the light. What comes through the window. (I get an eye for rooms.)'],
  'N22-2/c/pay': ['Shouldn\'t advice be paid for? Do I owe you?', 'No — I learned something. I always learn from other people\'s rooms. (She gives me a piece of wood instead.)'],
  'N22-2/c/decline': ['The room looked different. That\'s enough.', '…That\'s exactly what I wanted to hear. (A sketch of my room goes up in the workshop guest book.)'],
  'N22-3/c/lesson': ['I\'d like to learn where to strike to get it out.', 'The grain. Stone has grain too. (I get an eye for where to quarry.)'],
  'N22-3/c/pay': ['I dug the stone, so I\'ll sell it to the workshop.', 'I\'ll buy it. As materials. (The workshop ledger\'s first purchase.)'],
  'N22-3/c/decline': ['It saved me the price of sinkers. That\'s enough.', 'It did. That\'s where it starts. (A slot on the materials shelf becomes mine.)'],
  'N22-4/c/lesson': ['So farming has tides too. I\'d like to learn more.', 'Sun and water. Same as the sea. (A feel for farming appears for the first time.)'],
  'N22-4/c/pay': ['I paid for the seed, so I\'ll take the labour.', 'Right. Labour is labour. (The ledger records \'garden labour\'.)'],
  'N22-4/c/decline': ['I\'ve got a season\'s groundbait out of it. That\'s enough.', '…I like people who count it that way. (One row of the back garden becomes mine.)'],
  'N22-5/c/empty': ['An empty tank felt oddly good.', '…I\'ve waited a long time to hear that. (She gives me a filter. A quiet one.)'],
  'N22-5/c/lesson': ['Is keeping this water different from a live tank?', 'It is. You aren\'t selling them, so take it slow. (Tank keeping settles into my hands.)'],
  'N22-5/c/pay': ['The setup advice… do I owe you for that?', 'No. I got to see an empty tank. That\'s the payment. (She gives me a handful of plants instead.)'],
  'N22-6/c/lesson': ['I\'d like an eye for picking what\'s usable in a worked-out quarry.', 'It\'s the colour. Not grey — black-grey. (A feel for mining appears.)'],
  'N22-6/c/pay': ['I\'ll sell my half to the workshop.', 'I\'ll buy it. Materials. (The ledger\'s second purchase.)'],
  'N22-6/c/decline': ['Half each is fine. Even without a seam.', '…Said like that, it sounds like a seam. (Two slots on the materials shelf become mine.)'],
  'N22-7/c/promise': ['I\'ll come even if nothing sprouts.', '…That sentence is the harvest. (She gives me a workshop key. Come any time.)'],
  'N22-7/c/lesson': ['Planting without knowing what the seed is — is that something you learn too?', 'That\'s farming. Same as the sea. You cast without knowing what will take it. (My feel for farming rises a step.)'],
  'N22-7/c/pay': ['I should pay for the seed.', 'No. Pay me in harvest. And nothing if nothing comes. (She won\'t take money. She gives me a pot instead.)'],
  'N22-8/c/home': ['Somewhere to come back to. I understand that now.', '…Took twenty-two years. No — I wouldn\'t know. That\'s just what I heard. (Hanui gives me a nameplate. She carved it. I\'m to cut the name myself.)'],
  'N22-8/c/lesson': ['I should teach the order of finishing a house to the next person.', 'Chairs first. It isn\'t a home until there\'s somewhere to sit. (My feel for living rises, last of all.)'],
  'N22-8/c/pay': ['I hear it\'s rude to accept housewarming gifts.', 'Accept them. Manners next time. (The gifts pile up. Mostly food.)'],
  'N21-4/o/decline': ['Ten of them is beyond me right now. Another time.', '…Right. I\'ll ask someone else. (She calls again next summer.)'],
  'N21-4/c/bounty': ['I\'ll take the cull rate.', 'By the rules. And the pen keeper pays separately. (Two envelopes.)'],
  'N21-4/c/data': ['I\'d like to learn to predict jellyfish drift. Then we clear them early.', 'Water temperature and wind. You predict from those two. (I get an eye for jellyfish drift.)'],
  'N21-4/c/volunteer': ['The farm survived. That\'s enough.', '…I knew you\'d say that. (The Geoje farm people know me.)'],
  'N21-5/o/go': ['A hundred kilos is still one animal. I\'ll do it.', 'Two pairs of gloves. Please.'],
  'N21-5/o/decline': ['That one is beyond my strength.', '…Thank you for being honest. We\'ll take it by boat next season.'],
  'N21-5/c/bounty': ['I\'ll take the rate. A hundred kilos.', 'Per kilo, so… that\'s real money. By the rules. (The figure on the receipt is long.)'],
  'N21-5/c/data': ['I want to know where the Nomura come from.', 'The south. Along the current. Look at this table. (I get an eye for large jellyfish drift.)'],
  'N21-5/c/volunteer': ['Keep the rate. Nobody got stung. That\'s enough.', '…We need people like you. Genuinely. (First on the Jeju monitor list.)'],
  'N21-6/o/go': ['One at a time will do. I\'m going.', 'Thank you. Two pairs of gloves.'],
  'N21-6/o/decline': ['A swarm needs a boat. Alone I can\'t.', '…You\'re right. I\'ll call when a boat\'s ready.'],
  'N21-6/c/bounty': ['I\'ll take the rate.', 'By the kilo. Three of them is… real money. (The figure on the receipt is long.)'],
  'N21-6/c/data': ['How do you count the ones still out there?', 'Only what\'s visible from the boat. This way. (I learn how to estimate numbers at sea.)'],
  'N21-6/c/volunteer': ['Three is three. Keep the rate.', '…That sentence is the first line of my report. (The Ulleung fishermen know me.)'],
  'N21-7/c/next': ['The next person. I\'ll take it.', '…Thank you. (She gives me fifteen years of records and a monitor\'s gloves. Two pairs.)'],
  'N21-7/c/data': ['I\'ll start by learning how to read fifteen years of it.', 'Read only the first line of each year. The first line is that year. (Reading long-run data settles into my body.)'],
  'N21-7/c/bounty': ['I\'ll take the last rate. By the rules.', 'By the rules. The last receipt. (There\'s a monitor\'s signature on the back.)'],
  'N23-1/o/go': ['After a typhoon is when you count, then. I\'ll do it.', 'Exactly. Now\'s the time.'],
  'N23-1/o/decline': ['I can\'t right now. Call me after the next typhoon.', '…Right. Typhoons come round again.'],
  'N23-1/c/data': ['I\'d like to learn more about telling farmed from wild.', 'Fins, condition, and the eye. (How I read the detail view changes.)'],
  'N23-1/c/pay': ['Is there a survey cooperation fee?', 'There is. By the rules. (The receipt says \'survey cooperation\'.)'],
  'N23-1/c/volunteer': ['Keep the fee. Call me for the next survey too.', '…I will. Genuinely. (My name goes first in the cooperator column.)'],
  'N23-2/c/data': ['Teach me how to turn a tide and a spot into a record.', 'There\'s an order on the sheet. Spot, tide, specimen, then date. (Fishing that keeps records begins.)'],
  'N23-2/c/pay': ['I\'ll take the cooperation fee.', 'By the rules. (The receipt is exact.)'],
  'N23-2/c/volunteer': ['Keep the fee. Call me if a white one turns up.', '…You\'ll be the first I call. (First in the cooperator list.)'],
  'N23-3/c/data': ['I\'d like to learn why the grades split, with a manager\'s eye.', 'The colour of the blood line. And the time of the ikejime. (My sashimi grade steadies.)'],
  'N23-3/c/pay': ['I\'ll take the price of the proof.', 'By the rules. Survey cooperation. (The receipt reads: top-grade sashimi, one plate.)'],
  'N23-3/c/volunteer': ['The plate said it. That\'s enough.', '…I think the plate said that too. (First in the Yeosu cooperator list.)'],
  'N23-4/c/data': ['I\'d like to know what release records are used for.', 'Stock estimates. Your five lines set next year\'s closed season. (Measurement records settle into my body.)'],
  'N23-4/c/pay': ['I\'ll take the cooperation fee.', 'By the rules. Five entries. (Five lines on the receipt.)'],
  'N23-4/c/volunteer': ['The fish lived. That\'s enough.', '…I can\'t put that on the sheet, but I\'ll remember it. (My standing at sea rises quietly.)'],
  'N23-5/c/data': ['I\'d like a manager\'s eye for counting species.', 'Fin counts. And the shape of the mouth. (Identifying species gets faster.)'],
  'N23-5/c/pay': ['I\'ll take the price of the survey sheet.', 'By the rules. Forty species rates highly. (The figure on the receipt is long.)'],
  'N23-5/c/volunteer': ['The species are still there. That\'s enough.', '…Your codex is the survey sheet. Genuinely. (First in the Incheon cooperator list.)'],
  'N23-6/c/empty_page': ['I\'ll leave the last page blank. It belongs to the next person.', '…That\'s why I gave it to you. (With the sheet she gives me a manager\'s stamp. Not cooperator — surveyor.)'],
  'N23-6/c/lesson': ['What makes a plate worth recording?', 'One you want to eat. That\'s the record. (Cooking and record-keeping join up.)'],
  'N23-6/c/pay': ['I\'ll take the last cooperation fee.', 'By the rules. Top grade, since it\'s the last. (The longest figure on any receipt.)'],
  'N20-1/o/go': ['One fish, maybe. Film the hands only.', 'Yes! Hands only! Thank you!'],
  'N20-1/o/decline': ['I\'ll pass on being filmed.', '…Ah. Right. Sorry. (She folds the tripod. She went to another harbour the next day.)'],
  'N20-1/c/encourage': ['Twelve people are still people watching. Keep going.', '…Could you say that on the stream? No — never mind. I\'ll remember it. (The first cut of the edit is my strike.)'],
  'N20-1/c/pay': ['If there\'s an appearance fee, I\'ll take it.', 'There is… ad revenue… four thousand won this month. (She splits it in half, seriously.)'],
  'N20-1/c/lesson': ['How did you stop your hands freezing in front of a camera?', 'Mine freeze too. I just think of the lens as a fish. (Oddly, my casting gets easier.)'],
  'N20-2/c/watch': ['Watching the sea without fishing was a first for me too.', 'Right? That\'s why I film. (The video\'s title stops being about fishing and becomes about people.)'],
  'N20-2/c/pay': ['I\'ll take the appearance fee.', 'This month\'s ad revenue… eight thousand won! Doubled! (She gives me half, seriously.)'],
  'N12-3/c/lesson': ['Umi\'s camper cooking at night — I\'ll use it aboard as it is.', 'Three dishes on one burner. There\'s an order to it. (Cooking afloat gets faster.)'],
  'N12-3/c/pay': ['I\'ll take the night guiding fee.', '…Yes. At the staff rate. (She pays, smiling.)'],
  'N18-6/c/lesson': ['Teach me the order you read labels in. For the inspector\'s exam.', '…You\'re sitting it? No you\'re not. I\'ll teach you anyway. (I get an eye for distribution.)'],
  'N18-6/c/proud': ['Inspector. I think it suits you.', '…First time anyone\'s said that. Even grandfather. (He shows me the application form.)'],
  'N18-6/c/compete': ['If I\'m a skipper and you\'re an inspector, what do we compete at next?', '…I\'ll think about it. There\'ll be something. (He laughs. A rivalry that lasts.)'],
  'N19-5/c/open_door': ['I only opened the door. He walked in himself.', '…You still opened it. (He starts on a fourth rest. For the hospital room, he says.)'],
  'N19-5/c/wait': ['I waited ten minutes in the corridor. It was a long ten minutes.', 'Longer than fifty years, I\'d think. (Instead of a wage he gives me a length of bamboo. Left over from the first rest.)'],
  'N19-5/c/pay': ['Cover my fare to the hospital.', '…I will. (His hand shakes handing it over. Relief.)'],
  'N03-7/c/grown': ['I wanted to hear \'all grown up\' from you.', '…Lad. (The chairman raises retirement for the first time. A trailer for Part Seven.)'],
  'N03-7/c/lesson': ['Point out what I got wrong in my explanation.', 'Nothing wrong. Only the order. Work backwards from the consumer and it\'s clearer. (My grasp of distribution rises a step.)'],
  'N03-7/c/pay': ['I\'ll take a lecture fee for Incheon.', 'A lecture fee! Ha. Out of the chairman\'s own pocket. (The envelope is thick.)'],
  'N10-4/c/lesson': ['A silent cast. It\'s the wrist, not the shoulder.', 'You saw. It\'s the wrist. And the moment you let go. (My casting distance rises a step.)'],
  'N10-4/c/sound': ['What stayed with me is that it\'s all right to make a sound.', 'I made one too, twenty years ago. Nobody said that to me. (He holds up his own rod. There\'s a name engraved on it.)'],
  'N10-4/c/pay': ['You\'ll pay me for the last shift, won\'t you.', 'Out of the store. Last day\'s wage. (There\'s a storeroom key in the envelope. A keepsake, he says.)'],
  'N17-3/c/lesson': ['I learned how to hand out twelve rigs in fifteen minutes.', 'Tie them beforehand. That\'s ten years as a section chief. (Preparing group outings settles into my body.)'],
  'N17-3/c/pay': ['The company covers the dinner, doesn\'t it.', 'Of course. Corporate card! (The guide fee goes on the corporate card. The receipt is immaculate.)'],
  'N17-3/c/decline': ['The team got rods in their hands. That\'s enough.', '…I told them that and now they want the next dinner to be fishing too. (My name is on the Incheon after-work list.)'],
  'N18-7/c/we': ['\'We\'. That word weighed more than a hundred chairs.', '…Shut up. (He sits. The two of us side by side. Neither of us says \'rival\' any more.)'],
  'N18-7/c/lesson': ['There\'s a trick even to carrying chairs. You were faster.', 'Two at a time. Legs, not back. My grandmother taught me. (Carrying loads settles into my body.)'],
  'N18-7/c/compete': ['Next contest is the reopening tournament. Judge: Namgung Hyeon.', '…Good. The last one. (He laughs. Like the day we met. But differently.)'],
  'N19-6/c/pretend': ['I pretended not to see. Fifty years, after all.', '…You\'re a good lad. (She gives me the shop key. The stall is mine now, she says. Well — apart from two seats.)'],
  'N19-6/c/saw': ['I saw. You holding his hand.', '…You saw? Fine, look. It\'s fifty years. (She laughs. So does he.)'],
  'N19-6/c/pay': ['I\'ll take a matchmaker\'s fee. Fifty years\' worth.', 'Matchmaker… all right, take it. Fifty years\' worth. (Not an envelope — the key to the stall drawer.)'],
  'N04-6/c/forever': ['Adult member forever. Understood.', 'Yes! (The three of them give me another badge. Adult members only, in gold.)'],
  'N04-6/c/jinju': ['Jinju. Let\'s fish off your boat one day.', '…Yes. My boat. (Jinju smiles for the first time. Bae Nuri takes a photo.)'],
  'N04-6/c/pay': ['Club funds pay for hanging the flag, don\'t they.', 'Funds… we haven\'t any. We graduated. (The three of them empty their pockets. Ramyeon money. I take it.)'],
  'N16-4/c/same': ['You taught it exactly as I taught you.', '…You learned it from somebody too, right? (I tell him about the stall grandmother. He listens a long time.)'],
  'N16-4/c/lesson': ['Watching you teach taught me something. How to teach.', 'How to teach? You just stand beside them. (I learn again how to stand beside someone.)'],
  'N16-4/c/pay': ['The teacher takes the tuition. That\'s your share.', 'Tuition! From you? …Ice cream. (The survey team pays instead. He buys for his student.)'],
  'N14-5/c/stayed': ['All three stayed, each in a different way. That\'s the ending.', 'It isn\'t an ending! It\'s the start! (A second photo of the three of them. This time I\'m in it.)'],
  'N14-5/c/lesson': ['I want to use how you organise a tournament for the reopening one.', 'Start with where the measuring table goes! In the shade! (Running events settles into my hands.)'],
  'N14-5/c/pay': ['The organisers cover a guest\'s travel, don\'t they.', 'Yes! Out of the operating budget! First time I\'ve used it! (The amount is exact. Very organiser.)'],
  'N21-1/c/bounty': ['I\'ll take the cull rate.', 'By the rules. Here. (She pays, with a receipt written out per kilo.)'],
  'N21-1/c/data': ['I\'d like to see the population records with you.', 'You\'ve got an eye. Look at this table. It rises every year. (She teaches me how to read it — and where to look first.)'],
  'N21-1/c/volunteer': ['Keep the rate. Call me next time as well.', '…That\'s the kind of person we needed. (My number goes on the monitor list.)'],
  'N21-2/o/go': ['Inside the bay in summer, now\'s the time. I\'ll do it.', 'Thank you. Wear gloves.'],
  'N21-2/o/decline': ['I\'ve other things on this summer. Next time.', 'Right — summer comes round again. (She calls again the next season.)'],
  'N21-2/c/bounty': ['I\'ll take the cull rate.', 'By the rules. Per kilo. (She writes the receipt out carefully.)'],
  'N21-2/c/data': ['I\'d like to see the records on why the jellyfish are increasing.', 'It\'s water temperature. Look at the table. (I learn to read the drift direction of jellyfish.)'],
  'N21-2/c/volunteer': ['Keep the rate. Call me every summer.', '…Nobody\'s said that before. (I\'m first on the summer monitor list.)'],
  'N21-3/c/bounty': ['I\'ll take the rate.', 'By the rules. Per kilo. (The counter receipt is immaculate.)'],
  'N21-3/c/data': ['I\'d like to see the starfish growth curve.', 'Look at this table. Three years of it. (I learn to read seabed population density.)'],
  'N21-3/c/volunteer': ['Keep the rate. Call me at the next counter too.', '…There you go again. Thank you. (They know my name at the Ulsan counter.)'],
  'N21-4/o/go': ['Before it blocks the intake, then. I\'m going.', 'Thank you. Gloves!'],
  'N02-6/c/pay': ['You should be paid for the test fishing.', '…Money? I\'ve only got pocket money. (He takes out a thousand-won note, seriously. I can\'t refuse it.)'],
  'N18-3/c/lesson': ['Teach me how you draw the old ones out.', '…You listen. Without cutting in. (Listening to people turns out to be useful elsewhere too.)'],
  'N18-3/c/compete': ['Next time I take more notes than you.', 'Fix your handwriting first. (He laughs. It\'s the first time we\'ve laughed over the same old man.)'],
  'N18-3/c/thanks': ['Thanks for coming along.', '…I didn\'t come along, I told you. (He asks about the next recording date first, all the same.)'],
  'N03-6/c/listen': ['I won\'t ask about the boat\'s name.', '…I knew you\'d say that. (The two old men sit me in their own places. In Bangeojin and Sokcho both.)'],
  'N03-6/c/lesson': ['I still can\'t read what you two say with your hands. Teach me.', 'It takes thirty years for hands to talk. There\'s a way to watch, though. (I get an eye for people\'s hands aboard.)'],
  'N03-6/c/pay': ['Cover my fare to Ulsan.', 'I will. Out of the chairman\'s travel budget. (The envelope carries the co-op stamp.)'],
  'N19-3/c/relay': ['She set it down beside the first one.', '…Beside it. (A long while later he starts cutting a third.)'],
  'N19-3/c/lesson': ['I can see the grain of the rests now. Let me cut one.', 'Cut one. Crooked is fine. (Mine stayed in the corner of the workshop.)'],
  'N19-3/c/pay': ['I\'ll take the errand money.', '…Right. An old man\'s errand money. (He hands it over. His hands are a little slow.)'],
  'N05-7/c/lesson': ['I\'d like to learn how you keep the shop tank.', '…The tank? I\'m still learning that myself. Let\'s look together. (I get an eye for reading live fish.)'],
  'N05-7/c/pay': ['I\'ll take the price of the slicing.', '…Yes. It\'s my first sale. (My name goes on the first line of the ledger.)'],
  'N05-7/c/decline': ['Call me the shop\'s first customer. No charge.', '…First customer. (Harang took a photo in the end. Three at the counter.)'],
  'N08-3/c/lesson': ['Haena, your course changes are better than mine. Teach me.', 'Really? Then maybe I could skipper after all. (My feel for reading the boat changes.)'],
  'N08-3/c/photo': ['I\'ll show your father the photo the passenger took.', '…No. No — yes. Show him. (The skipper looked at it a long time. He said nothing.)'],
  'N08-3/c/pay': ['I\'ll take the fare for coming along.', 'Ah… right. (She pays out of her pocket money.)'],
  'N18-4/c/team': ['Two pairs of eyes did it. Exactly as you said.', '…Right. (He says he\'ll call me first the next time he looks at a boat too.)'],
  'N18-4/c/lesson': ['Teach me how to read an estimate.', '…Once only. Start with the labour line. (I get an eye for reading boat estimates.)'],
  'N18-4/c/compete': ['Next boat, I price it too.', 'Try it. Check the hull properly first. (He laughs.)'],
  'N04-5/c/listen': ['It\'s your decision. Either way, a captain is a captain.', '…Yes. (She applies to the fisheries school. For the first time she says \'hyeong\' easily.)'],
  'N04-5/c/advise': ['I think fisheries school is right. Your eyes look at the sea.', '…You\'re the first adult to say that. (She applies. But it sits a little heavy, as if I decided it.)'],
  'N04-5/c/pay': ['I should charge a consultation fee. Joking.', '…Adults\' jokes are really not funny. (She laughs anyway. She pays for ramyeon.)'],
  'N19-4/c/quiet': ['Neither of them said a word for ten minutes. It looked better that way.', '…You notice far too much. (That evening there was one more ice crate on the stall. Old Tak\'s.)'],
  'N19-4/c/lesson': ['Pretending to carry ice so someone will sit down — I learned that from you.', 'From me? I never taught you that. (She laughs. The wage envelope is a little thicker.)'],
  'N19-4/c/pay': ['I\'ll take a matchmaker\'s fee.', 'Matchmaker, indeed. …Take it. (She glares while handing it over. She hands it over.)'],
  'N09-4/c/lesson': ['Your father\'s knife weighs differently from mine. Teach me to use it.', 'It\'s a heavy knife. You have to take the strength out. (My butchery grade rises. With that knife.)'],
  'N09-4/c/pay': ['I\'ll take the price of the opening-day butchery.', '…Yes. Our first outgoing. (She writes \'butchery\' on the ledger\'s first line.)'],
  'N09-4/c/decline': ['Call it an opening gift.', '…Bom\'s crying. So am I, a little. (My name goes on the restaurant wall. First customer.)'],
  'N11-4/c/praise': ['He wasn\'t scatterbrained. He was a skipper.', '…Hyeong. (Pado folds the tip envelope in half and holds it out. His face won\'t let me refuse.)'],
  'N11-4/c/lesson': ['You seat passengers better than I do. I should learn that.', 'Me? The skipper taught me. Put the bad sailors amidships! (Handling passengers settles into my hands.)'],
  'N11-4/c/decline': ['All I did was stand there. It\'s fine.', 'You\'re allowed to just stand there, hyeong. Really. (Everyone in Jisepo knows Pado calls me hyeong.)'],
  'N18-5/c/thanks': ['Thanks for bringing the papers.', '…I didn\'t bring them, I told you. (He raised his hand on the same side in the vote all the same.)'],
  'N18-5/c/lesson': ['You read documents faster than I do. Teach me.', 'Read the conclusion first. Grounds afterwards. (How I read documents changes.)'],
  'N18-5/c/compete': ['If you vote against me, that means I won.', '…Try it. (In the vote he looked my way. I can\'t tell if I won or lost.)'],
  'N06-4/c/honor': ['An honorary member\'s share. I\'ll use it well.', 'Use it. It\'s given to be cast. (There\'s a Seabusters sticker inside the lure box.)'],
  'N06-4/c/lesson': ['Show me that madness of yours one last time.', 'Madness? …This. Picking colour in dirty water. (Lure colour choice settles into my body.)'],
  'N06-4/c/pay': ['Is there prize money for the graduation match?', 'There is. Everything left in the dues. (Mostly coins. But all of it.)'],
  'N08-4/c/haena': ['You should tell Haena first.', '…I know. I called you because I thought I could say it with you here. (That evening the three of us sat in the wheelhouse.)'],
  'N08-4/c/lesson': ['I want to learn how you look at a boat. Before you sell her.', '…You don\'t look at a boat with your eyes. You look with your feet. (A feel for reading boats settles in.)'],
  'N08-4/c/pay': ['I\'ll take my share of today\'s catch.', 'You will. Best haul of the year, so it\'s a big share. (The envelope is thick.)'],
  'N13-3/c/lesson': ['You picked up stove repair by watching, didn\'t you. Teach me.', 'I fix anything on a boat. Except manuscripts. (Machine repair settles into my hands.)'],
  'N13-3/c/pay': ['I\'ll take parts and labour.', 'Yes. The manuscript fee came through, finally. (This time the envelope is a proper envelope.)'],
  'N13-3/c/decline': ['You made him a place to sit. That\'s enough.', '…I\'ve got a place there too. Beside him. (In front of the old man\'s photo there are three places.)'],
  'N12-3/c/stay': ['The camper can stay there. Both of you are here.', '…Say that to Umi. No — I\'ll say it. (A camper bay appears in the hotel car park.)'],
  'N16-1/c/pay': ['I\'ll take the reel, and I\'ll pay the prize myself.', 'Prize money! Ice cream! (I hand over ice cream money. He buys three.)'],
  'N16-2/c/deliver': ['I delivered the letter. Your grandfather stood there a long while.', '…A long while? (The boy looks toward the lighthouse. That evening he climbed up to it.)'],
  'N16-2/c/ask': ['Tell me now why you won\'t go yourself.', '…Grandad hates my fishing. Says study. (The letter, they say, only read: three rockfish.)'],
  'N16-2/c/pay': ['An errand should be paid.', 'Pocket money… I haven\'t got any. Have a rockfish. (One rockfish. I take it.)'],
  'N16-3/c/first': ['The first \'well done\' you\'ve heard. Don\'t forget it.', 'I won\'t. (He gives me his measuring rule. His grandfather\'s, he says. He uses his own now.)'],
  'N16-3/c/lesson': ['You lay the rule more accurately than the survey team. Where did you learn?', 'From grandad. Logging the weather. Reading the marks. (My measuring gets accurate.)'],
  'N16-3/c/pay': ['Survey assistant pay goes to the grown-up, doesn\'t it.', 'Grown-up? You? …Ice cream, then. (The survey team pays for ice cream. He buys five.)'],
  'N17-1/o/go': ['Twenty minutes I can manage. Let\'s go.', 'That\'s the spirit. Come on.'],
  'N17-1/o/decline': ['I haven\'t got time today.', '…Next time you\'re heading home, then. Everyone heads home eventually.'],
  'N17-1/c/habit': ['A twenty-minute habit. I\'ll make one of my own.', 'Make one. It\'ll last ten years. (The restaurant owner keeps a seat for me too.)'],
  'N17-1/c/lesson': ['A rig that puts one on the bank inside twenty minutes — that\'s what I want.', 'It has to be simple. One rig. One spot. (Short-session fishing settles into my body.)'],
  'N17-1/c/pay': ['Dinner\'s on you, isn\'t it.', 'Of course. Company card… no, mine. (With the meal comes an envelope. What\'s left of the team dinner fund, he says.)'],
  'N17-2/c/accept': ['Play at the reopening, please.', 'Yes! (From the cello case she takes out a sheet of music. The piece is called \'Sea\'.)'],
  'N17-2/c/lesson': ['Fishing to loosen your hands before a performance. There must be a way to loosen them before a fight, too.', 'There is. Turn the reel handle slowly. Three turns. (The early part of a fight steadies.)'],
  'N17-2/c/pay': ['Are there dues for the catch party?', 'There are! Out of an orchestra salary! (It isn\'t much, but it\'s an orchestra salary.)'],
  'N18-1/c/compete': ['Next time I land the bigger one.', '…Right. That\'s what makes it interesting. (At the word \'bet\' his eyes change. It means there\'s a next time.)'],
  'N18-1/c/concede': ['You were better. I\'ll admit it.', 'Drinks on me. I\'m not underage any more. (The shop bag is heavy.)'],
  'N18-1/c/ask_tip': ['That strike just now — how did you do it?', '…I\'ll show you once. You don\'t count after the float goes under. Your hand has to be moving before it does.'],
  'N19-1/c/relay_true': ['She held the bamboo section for a long while.', '……She did? I see. (He says nothing for a time. That evening a new rest appeared on her stall.)'],
  'N19-1/c/relay_soft': ['She didn\'t say much.', '…Of course not. What would she say. (He goes back to shaping. The sound is a little rougher.)'],
  'N19-1/c/lesson': ['May I watch you cut the rests?', 'If you stay quiet. (I learn to tell the sound of the saw from the sound of the cane.)'],
  'N04-3/c/teach': ['Would you mind if I kept an eye on that one a while longer?', 'Club-coaching adult member! Then we learn too. (Teaching tidies up my own casting.)'],
  'N04-3/c/pay': ['Does the club budget run to a wage?', 'Budget… about the price of ramyeon. (She makes up an envelope, seriously.)'],
  'N04-3/c/decline': ['The club surviving is enough for me.', '…The captain\'s crying. Long live the adult member. (Students greet me when I pass the school.)'],
  'N03-5/c/lesson': ['You were tying too. Your hands were faster than mine.', '…An old man with time on his hands, that\'s all. I\'ll teach you another knot next time. (He tips his spare swivels into my tackle box.)'],
  'N03-5/c/pay': ['I was your practice partner. I\'ll take the wage.', 'Do. A price is a price. (The hand counting money is quick again.)'],
  'N03-5/c/decline': ['It\'s a neighbour\'s business. What wage? (It\'s fine.)', '…I\'ll remember that a long time. (The harbour people start calling me the chairman\'s teacher.)'],
  'N02-5/c/why': ['I thought even sections take the load evenly.', 'That\'s it. A rod lives by its sections. So does a man. (He hands me that culm. Not a rod yet, but it will do as material.)'],
  'N02-5/c/luck': ['Honestly, it was luck.', 'Luck comes after your hands have touched it. Next time choose knowing why. (Instead of a wage he cuts me a length of bamboo.)'],
  'N02-5/c/point': ['If you\'ve written down how you choose, show me.', '…There\'s no note. It\'s here. (He taps his head. Then he tears off a sheet and writes it out.)'],
  'N18-2/c/lesson': ['Teach me how you read the auctioneer\'s hands.', '…You\'re asking me to teach you? Fine. Once. (I get an ear for the sound of the auction hall.)'],
  'N18-2/c/compete': ['Next time I call more of them right.', 'Try it. (He laughs too. It\'s the moment the word \'rival\' fits best.)'],
  'N18-2/c/pay': ['Split what you made off my help today.', '…A broker\'s cut, is it. Half. (The hand counting the money is a grown man\'s.)'],
  'N19-2/c/deliver': ['I handed the container over as it was. I heard coughing.', '…Thank you. Don\'t ask. (A few days later another bamboo rest came out of the workshop.)'],
  'N19-2/c/read_first': ['…I did open the lid. I wanted to know what she\'d packed.', 'You. (He glares for a while, then laughs. He never mentions it again.)'],
  'N19-2/c/refuse_read': ['I didn\'t open it. It\'s between the two of you.', '…A clever lad. (I get a seat at the stall.)'],
  'N04-4/c/lesson': ['I watched Jinju\'s casting from behind. Captain, make her stance the club manual.', 'A manual! Yes! Jinju will hate it, though… (Copying her stance tidies mine as well.)'],
  'N04-4/c/pay': ['I\'ll take a chaperone fee.', 'There is one! What\'s left of club funds… minus the gimbap. (It isn\'t much.)'],
  'N04-4/c/decline': ['The students enjoyed it. That\'s enough.', 'Best adult member! (The trip photo goes up on the school board. I\'m standing at the back.)'],
  'N05-6/c/lesson': ['I watched Gibeom butcher from behind. His angle off the bone is different from mine.', 'Oppa, he was watching! (For the first time Na Gibeom turns round and shows me how to hold the knife.)'],
  'N05-6/c/pay': ['I\'ll take it as an appearance fee.', 'Yes… five viewers\' worth… (She works it out, seriously.)'],
  'N05-6/c/decline': ['If the channel grew at all, that\'s enough.', 'Five! Up by two! (My butchery makes the next video\'s title.)'],
  'N02-6/c/praise': ['The tip is alive. It isn\'t thin, it\'s sensitive.', '…Sensitive. Will you say that to grandad? (The next day he started cutting another blank.)'],
  'N02-6/c/lesson': ['Teach me how you chose the sections.', 'Me? Teach you? …All right. You choose sections by sound. (There\'s no shame in learning from a twelve-year-old.)'],
  'N11-2/c/pay': ['I should take a wage for the dawn shift.', 'Ah… right. Of course. (He gives me what\'s left of his first pay packet, looking sorry about it.)'],
  'N11-3/c/lesson': ['Teach me exactly what you say when you turn someone down.', 'The sea said no. Say only that. (After this, my accident rate visibly drops.)'],
  'N11-3/c/pay': ['Cover a little of the sailing I gave up.', '…That\'s fair too. A boat costs money standing still. (She gives me a little. Her face is complicated.)'],
  'N11-3/c/decline': ['The boat coming back is the payment.', '…Skippers who say that last a long time. (I have a seat among the Jisepo skippers.)'],
  'N12-1/o/stay': ['I\'ll sit. Until sundown.', '…Thank you.'],
  'N12-1/o/decline': ['I\'ve somewhere else to be today.', '…Right. That happens. (She watched the sun go down alone. That day doesn\'t come back.)'],
  'N12-1/c/stay': ['I\'ll sit with you any time.', '…Even if we argue again? Joking. (A staff discount voucher arrives quietly.)'],
  'N12-1/c/ask': ['May I ask what the argument was about?', '…The camper van. Jeong Umi. I\'ll introduce you sometime. (The next chapter opens.)'],
  'N12-1/c/nothing': ['Some days the catch is zero. That\'s allowed.', 'It is. Today was one. (She laughs. First time.)'],
  'N12-2/c/lesson': ['Umi\'s camper-van housekeeping would work on a boat as it is.', 'Right? Living small is the same everywhere. (Stowage aboard changes.)'],
  'N12-2/c/pay': ['I\'ll take the guiding fee.', 'Of course. The couple paid. (The envelope is thick. There\'s a tip in it.)'],
  'N12-2/c/decline': ['A calm night was enough.', '…I like that. The camper door is always open. (I have a place on the Yeosu night water.)'],
  'N13-1/o/go': ['Get aboard. The cuttlefish boat is sailing.', 'Saved! Thank you!'],
  'N13-1/o/decline': ['I can\'t help you run from a deadline.', '…Right. My editor caught me. I made the deadline, though. (That boat didn\'t sail that day.)'],
  'N13-1/c/pay': ['I\'ll take a getaway fee.', 'Of course! Out of the manuscript fee! (She hasn\'t been paid yet, so it\'s half for now.)'],
  'N13-1/c/lesson': ['I\'d like to learn how you concentrate on a boat.', 'Drawing on a moving deck makes my hand shake less. Strange, isn\'t it. (My hands shake less during a fight.)'],
  'N13-1/c/decline': ['You made your deadline. That\'s enough.', '…No editor has ever said that to me. (My name goes on the first page of the book.)'],
  'N13-2/c/share': ['I have a family photo too. I\'m four in it.', '…Show me. (The old man looks a long time. Then he sets it beside his own.)'],
  'N13-2/c/lesson': ['I\'d like to learn how you made a home out of a scrapped boat.', 'A boat can be abandoned and still be a house. (Living aboard settles into my hands.)'],
  'N13-2/c/pay': ['I\'ll take the finder\'s price.', '…Do. An old man\'s money. (He counts it out down to the coins.)'],
  'N14-1/c/real_smile': ['That was a real smile. Not a broadcast one.', '…How did you know. (She pays me an appearance fee. Out of her own share.)'],
  'N14-1/c/lesson': ['Teach me framing, with a broadcaster\'s eye.', 'Rule of thirds. People on the left. (I get a feel for photographs and broadcasting.)'],
  'N14-1/c/decline': ['You laughed for the first time in a while. That\'s enough.', '…Can I put that on air? No — I won\'t. I\'ll keep it. (The Jeju broadcast people know me.)'],
  'N14-2/c/give_egi': ['Here\'s the egi. Mara left it behind.', '…(Serin looks at it a long time. Then she gives it back to me. To return to Mara next time.)'],
  'N14-2/c/lesson': ['I watched Mara\'s egging from a distance. Her fall is different.', 'Mara\'s a genius. I\'m effort. (Imitating her fall makes me a little better.)'],
  'N14-2/c/pay': ['I\'ll take a finder\'s fee.', '…Yes. Out of the prize money. (There\'s no prize money yet. It\'s pocket money.)'],
  'N14-3/c/rhythm': ['The rhythm came together on the third. That\'s enough.', 'It did! (She gives me a team shirt. Number 3.)'],
  'N14-3/c/lesson': ['Serin, your jerking rhythm is tournament grade. Teach me.', 'Me? Teach you? …All right. On this beat. (The jigging rhythm settles into my body.)'],
  'N14-3/c/pay': ['I should be paid as training coach.', 'Coach… Yuria is the manager, though. (Yuria pays instead. With broadcaster money.)'],
  'N14-4/c/finish': ['Finishing was the goal. All three of us finished.', 'Yes! (She gives me a photo of the three of us. Yuria took it.)'],
  'N14-4/c/lesson': ['Serin\'s squid lighting pattern was the fastest in the final. Teach me.', 'It\'s the lamp angle. Fifteen degrees down. (Drawing squid gets faster.)'],
  'N14-4/c/pay': ['Team prize money gets split.', 'Split it! A third each! (It isn\'t much, but it\'s money split three ways.)'],
  'N15-1/o/agree': ['I\'ll keep my distance. Let\'s compete.', 'Good. A hundred metres.'],
  'N15-1/o/decline': ['If you prefer to be alone, I\'ll fish alone too.', '…Right. (She never offered to compete again.)'],
  'N15-1/c/distance': ['A courtesy distance. That felt closer.', '…Nobody\'s put it that way before. (Fifty metres next time, she says. A little closer.)'],
  'N15-1/c/lesson': ['Your popping looked different even from a hundred metres. What\'s the difference?', 'The pause. I pause longer. (My popping rhythm changes.)'],
  'N15-1/c/pay': ['It was a bet. The loser owes something.', '…Ramyeon. Shop ramyeon. (With the ramyeon comes an envelope. The shop owner\'s share, she says.)'],
  'N15-2/c/lesson': ['Taeo, that pause you said came from your teacher — teach me.', '…My teacher doesn\'t talk. I talk a little. You pause here. (Night popping settles into my hands.)'],
  'N15-2/c/tell_sera': ['I\'ll tell Sera. You can just go together.', '…Then you tell her. (The next day Sera suggested all three of us go. No courtesy distance.)'],
  'N15-2/c/pay': ['An accomplice should be paid.', 'Accomplice… right. (He splits his shop wages.)'],
  'N16-1/o/accept': ['All right. I\'ll show you how a mainlander does it.', 'Big talk!'],
  'N16-1/o/decline': ['I don\'t compete against kids.', '…Coward. (He never came up to me again. Nor did the lighthouse story.)'],
  'N16-1/c/lesson': ['What did you use for bait? Teach me.', 'Under the rocks. You dig it by hand. (Gathering local bait settles into my hands.)'],
  'N16-1/c/rematch': ['Next time I win.', 'Try it, mainlander. (The boy grins. He brings up his grandfather\'s lighthouse.)'],
  'N06-3/c/vest': ['I\'ll put the vest to good use. Call me for the next typhoon too.', 'You don\'t call a typhoon. It comes. See you then. (There\'s a lure in the vest pocket.)'],
  'N06-3/c/lesson': ['Working it together — how did you know when to put the net in?', 'Watch the bass\'s eye. There\'s a moment it turns. (Landing big fish settles into my hands.)'],
  'N06-3/c/pay': ['I hear there\'s prize money for the club match.', 'There is. I\'ll open the weekly job board for you. This one\'s on me. (The envelope is thick.)'],
  'N07-1/c/ask_who': ['Who was the craftsman?', '…Later. I\'ll tell you at the fourth place. (He folds a copy of the plan and gives it to me.)'],
  'N07-1/c/lesson': ['That lure action — the secret was in the fall, I think.', 'You\'ve got an eye. It is the fall. (He shows me the fall angle of the last lure.)'],
  'N07-1/c/pay': ['I came all the way to Sokcho. Cover my travel.', 'I should. I\'m the one who dragged you here. (The travel money is generous.)'],
  'N07-2/c/lesson': ['What were you measuring? Tell me.', 'Rhythm. The gap between his rhythm and yours. (He shows me the weight distribution of the last jig.)'],
  'N07-2/c/pay': ['There\'ll be something for the measuring help.', 'There is. A man who searched thirty years shouldn\'t be stingy. (The travel money is generous.)'],
  'N07-2/c/ask': ['Why don\'t you cast it yourself?', '…My hands aren\'t his hands. Yours are closer. (He says it, then looks out at the sea for a long time.)'],
  'N07-3/c/brother': ['I\'d like to hear more about your brother.', '…On Jeju. When all four are together. (He gives me a minnow. The third copy of the last works.)'],
  'N07-3/c/lesson': ['I\'d like my surf minnow retrieve corrected by your eye.', 'It\'s wave timing. Wind as it rolls in. (The surf retrieve settles into my body.)'],
  'N07-3/c/pay': ['Cover the third trip as well.', 'I will. (He gives me the money. The money of a man who searched thirty years.)'],
  'N07-4/c/throw': ['I\'ll cast all of them. I won\'t put them behind glass.', 'Right. That\'s the answer. (He hands over all four. His brother\'s name is engraved on them.)'],
  'N07-4/c/one_back': ['Keep one for yourself.', '…No. It has to be four. He made four. (Still, he stood there a long time after I said it.)'],
  'N07-4/c/pay': ['Cover the fourth trip too.', 'I will. The last one. (With the money come the four lures. Money is money and his brother\'s work is his brother\'s work, he says.)'],
  'N08-1/c/lesson': ['I see now why shipboard rigs are short and heavy.', 'Because the boat rolls. A long rod takes the roll twice over. (Tying shipboard rigs settles into my hands.)'],
  'N08-1/c/pay': ['Is there a rate for standing on the bow?', 'There is. An officer is an officer. (He refunds my fare and adds a day\'s wage.)'],
  'N08-1/c/decline': ['The ride was enough.', '…Say that and the next trip is free. (I\'ve got a place aboard the Goraemaru.)'],
  'N08-2/c/lesson': ['Haena, I think I should be learning your knife work.', 'From me? Then I don\'t need cooking school after all? Joking. (The angle of my slicing changes.)'],
  'N08-2/c/support': ['Go to school. Your father had two bowls.', '…Thank you. Would you say that in front of him? No — I\'ll say it. (The skipper\'s regard rises quietly.)'],
  'N08-2/c/pay': ['I\'ll take the price of the yellowtail.', 'Ah, right. Of course. (She takes it out of her pocket money, looking sorry about it.)'],
  'N09-1/c/lesson': ['I need to relearn how to place my feet on the rocks. Bom too.', 'Yes! Let\'s learn together! (I get an eye for reading slick rock.)'],
  'N09-1/c/pay': ['It\'s odd to charge for catching someone, but give me something.', '…Tteok! I made it! (The tteok is good. It isn\'t money.)'],
  'N09-1/c/decline': ['I caught a person. It\'s fine.', '…My sister likes people like that. (I have a seat at the Guryongpo sisters\' table.)'],
  'N09-2/c/lesson': ['Watching Bom cook showed me what to leave on when I butcher.', 'Yes! You have to leave the belly meat! (My butchery grade rises.)'],
  'N09-2/c/pay': ['I\'ll take the price of the butchery.', 'It isn\'t even a restaurant… but you\'re right. (Suyeon takes out her purse without a word.)'],
  'N09-2/c/decline': ['Call it even for the meal.', '…My sister smiled. Just now. Did you see? (Lee Suyeon\'s regard moves for the first time.)'],
  'N09-3/c/share': ['I talked about my parents too. First time.', '…I heard. Thank you. (Suyeon gives me a fly. Her father\'s.)'],
  'N09-3/c/lesson': ['I\'d like to learn fly tying properly.', 'It\'s my father\'s way. I\'ll teach you. (The fly patterns settle into my hands.)'],
  'N09-3/c/pay': ['I\'ll take the price of restoring the flies.', '…Yes. Of course. (She holds out an envelope. Her face stiffens a little.)'],
  'N10-1/c/pretend': ['I didn\'t see anything.', '…Good. (He adds something to the day\'s wage. He says nothing.)'],
  'N10-1/c/ask': ['That cast — how did you do it?', '…So you saw. I\'m not teaching it. Not yet. (He fixes one wrist angle for me anyway.)'],
  'N10-1/c/pay': ['The day\'s wage is enough.', 'Right. That\'s the job. (The hand counting the money isn\'t a storeman\'s hand.)'],
  'N10-2/c/ask_20': ['Tell me about twenty years ago.', '…I took a side. A friend\'s. So I left. (He shows me his judge\'s badge. An old one.)'],
  'N10-2/c/lesson': ['I\'d like to learn to read the rules with a judge\'s eye.', 'Rules exist for people. Forget that and the rules start catching people. (Measurement regulations settle into my body.)'],
  'N10-2/c/pay': ['Is there a witness fee?', 'There is. It\'s in the tournament rules. (He pays it by the rules.)'],
  'N10-3/c/badge': ['That badge is an old one.', 'Twenty years old. I never threw it away. (He unpins it and gives it to me. Next tournament you judge, he says.)'],
  'N10-3/c/lesson': ['Look over the rules I\'ve drafted, with a judge\'s eye.', 'Cut three lines. Those are the ones that catch people. (The tournament rules get tidied.)'],
  'N10-3/c/pay': ['I\'ll pay the judge\'s fee out of the tournament budget.', 'By the rules. (He takes the fee and puts it straight back into the prize fund.)'],
  'N11-1/c/lesson': ['I\'d like to learn more about reading a course. I\'ll keep doing the cooking.', 'Deal. (My feel at the helm changes. The boat begins to read the current.)'],
  'N11-1/c/pay': ['I\'ll take the price of the meal.', 'Right. Meals afloat are chargeable. (The skipper\'s wallet is thick.)'],
  'N11-1/c/decline': ['I got a lesson out of it. It\'s fine.', '…Say that and I\'ll have you cooking again. (My name goes round the Jisepo skippers.)'],
  'N11-2/c/take': ['Thanks. I\'ll use it.', 'Yes! Hyeong! (Pado\'s name is written on the dry bag in marker.)'],
  'N11-2/c/lesson': ['You pull traps faster than I do. Teach me the trick.', 'Me? Teach you? It\'s the wrist — the wrist! (My trap hauling gets faster.)'],
  'N03-1/c/pay': ['The wage will do.', 'Right you are. Payment for teaching an old man. (His wallet is thick.)'],
  'N03-1/c/point': ['You\'ve written down what you learned, haven\'t you? Let me see it.', '…Ha. You\'ve picked up an eye as well. Take it. (One page at the back of the notebook is unusually neat.)'],
  'N03-2/c/teach_on': ['Guild chairman or not, on the breakwater you\'re my student.', '…Ha. I\'ve been wanting to hear that. (Word goes round the harbour that the co-op chairman is learning rigs from me.)'],
  'N03-2/c/distance': ['You deceived me, and that\'s that. I\'ll keep my distance.', '…Fair enough. We\'ll still say hello on the breakwater. (We say hello. Nothing more yet.)'],
  'N03-2/c/joke': ['Your beginner act was flawless. You could go on the stage.', 'Ha. Pretending I couldn\'t undo a knot was the hardest part. (He bursts out laughing, then writes me a letter of introduction.)'],
  'N03-3/c/respect': ['A stamp that doesn\'t interfere. That weighed more.', 'It ought to. (He hands me the stamp. Unused. A keepsake, he says.)'],
  'N03-3/c/lesson': ['I\'d like to learn how a chairman looks at a fishing guild.', 'From a distance. Go close and it becomes interference. (My eye for the economy widens a step.)'],
  'N03-3/c/pay': ['I\'ll take a teacher\'s fee.', 'Do. Out of the chairman\'s own pocket. (The envelope is thick. It isn\'t co-op money.)'],
  'N03-4/c/number_one': ['Number one on the roll. That\'s heavy.', 'It ought to be. It was heavy for me too. (My name goes down as member number one. Not chairman — member number one.)'],
  'N03-4/c/lesson': ['Undoing a tangled rig. I taught you that the day we met, and today I learned it back.', 'The one teaching learns more. Always does. (He teaches me one more knot. The chairman\'s knot, he calls it.)'],
  'N03-4/c/pay': ['I\'ll take the last lesson fee.', 'Ha. Do. Out of the retirement money. (The envelope is thick. He hands it over smiling.)'],
  'N04-1/c/join': ['I\'ll join.', 'Catch it, eat it! Welcome! (She writes my name on the roll and gives me a club badge. From now on fishing together is worth double experience.)'],
  'N04-1/c/decline_join': ['A school club is a bit… I\'m twenty-two.', 'Then just eat with us. Adult member! (She presses two tins of mackerel into my hands.)'],
  'N04-1/c/later': ['Let me think about it.', 'Take your time! The breakwater isn\'t going anywhere.'],
  'N04-2/o/go': ['If it\'s a winter dawn, it\'s now. Let\'s go.', 'Knew it! Bring a hat — dawn is properly cold.'],
  'N04-2/o/decline': ['A winter dawn is beyond me too. Let\'s skip this one.', '…Ah. Next winter, then. Jinju isn\'t going anywhere. Probably.'],
  'N04-2/c/silent': ['I just fished beside her without talking. That seems to have worked.', 'Knew it. Jinju connects through fishing, not words. (She gives me an envelope — club funds, she says.)'],
  'N04-2/c/lesson': ['Jinju\'s surfcasting taught me more than I taught her. I\'d like to learn from her.', 'Jinju\'s going to teach you? Her? …Then learn it in the club. Jinju, surfcasting officer!'],
  'N04-2/c/decline': ['It\'s students\' business. Keep the wage.', 'Best adult member ever… Jinju said the same thing. (My name goes round the breakwater club.)'],
  'N05-1/o/go': ['First time on a boat. I\'ll come.', 'Great! Bring seasickness tablets!'],
  'N05-1/o/decline': ['I\'ll pass on being filmed. Take someone else.', '…Oh. Right. Understood. (She lowers the camera and looks for someone else. That boat sailed that day.)'],
  'N05-1/c/lesson': ['I\'d like to learn more from Gibeom about keeping rigs tidy.', 'Oppa! He wants to be your apprentice! (Na Gibeom nods without a word. Rig-keeping settles into my hands.)'],
  'N05-1/c/pay': ['Is there such a thing as an appearance fee?', 'There is! A hundred won per hundred views… ah, I\'ll cover it myself for now. (She takes out her purse.)'],
  'N05-1/c/decline': ['Getting a ride on the boat is enough.', 'Really? I\'ll take you out again! (One in three of her subscribers is me.)'],
  'N05-2/c/rule': ['From now on, ask before you film. That\'s all.', 'Yes. Promise. (She writes my name on the first line of the consent form. After that, people are easier in Harang\'s videos.)'],
  'N05-2/c/pay': ['I\'ll take it as a likeness fee, then.', 'Ah… right. Yes. That\'s the rule. (She transfers it from her account. Her face stiffens a little.)'],
  'N05-2/c/lesson': ['Your fishing was better with the camera off. Teach me that retrieve.', '…Really? Then I\'ll teach it. First time, though! (The action settles into my hands.)'],
  'N05-3/c/support': ['You can live off fishing. With that knife of yours.', '…Hyeong. (Harang heard it and picked the camera up again. To film Gibeom this time.)'],
  'N05-3/c/caution': ['Can you live off a shop with no customers? Think it over once more.', '…I have thought. A thousand times. (He smiles anyway. Because somebody tried to stop him.)'],
  'N05-3/c/lesson': ['A man who\'s decided has different eyes. Show me one more cut with that knife.', '…Sure. Call it a resignation special. (The angle of my slicing changes once more.)'],
  'N05-4/c/glad': ['A boring video brought in customers. Because it was real.', '…I\'ll pass that on to him. (She shows me a photo of the shop. Three customers at the counter.)'],
  'N05-4/c/lesson': ['Your night rockfish rig is different from the first time I saw it. Teach me.', 'It\'s my second winter, after all. (My night rig gets tidied up.)'],
  'N05-4/c/pay': ['A reunion appearance fee… there wasn\'t a camera, though.', 'There wasn\'t! I\'ll pay you anyway. Congratulations on the Incheon posting! (She splits her own congratulation money.)'],
  'N05-5/c/full': ['I charged the full rate. Because they\'re friends.', 'That\'s right. (The two of them write the first review. Five stars.)'],
  'N05-5/c/lesson': ['I watched Gibeom cut on the boat. That angle, on a moving deck.', 'Cutting afloat takes a different angle. You match the swell. (Shipboard butchery settles into my body.)'],
  'N05-5/c/pay': ['Full rate and a tip on top.', 'A tip! Of course! (Harang adds a tip to the envelope. First customers, after all.)'],
  'N06-1/c/lesson': ['Hosu, you\'ve got a good eye for reading the seniors\' action. Mind if I watch alongside?', 'You? From me? Yes! (Lure action looks new again through a beginner\'s eyes.)'],
  'N06-1/c/pay': ['Is there such a thing as club expenses?', 'There is! Dues… enough for ramyeon, anyway. (He gathers up coins for me.)'],
  'N06-1/c/decline': ['Seeing his face when he landed that sea bass is enough.', 'Hyeong… you\'re an honorary member of our club now! (I\'ve become an adult people greet outside the maritime college.)'],
  'N06-2/c/lesson': ['I\'d like a copy of your lure selection chart.', '…Chart? It\'s in my head. I\'ll write it out. (Choosing colour by turbidity settles into my hands.)'],
  'N06-2/c/pay': ['Is there a fee for measuring help?', 'There is. A senior buying for a junior. (In money, not drink.)'],
  'N06-2/c/decline': ['Seeing Haneul\'s eyes change is enough.', '…You\'ve got the madness too. Good. (One more honorary Seabusters card.)'],
  'N06-3/o/go': ['Sea bass in dirty water — it\'s now. I\'m in.', 'That\'s the look. Bring the net.'],
  'N06-3/o/decline': ['Straight after a typhoon is dangerous. I\'ll sit this one out.', '…Fair point. See you at the next typhoon. The big feeders come back.'],
  'M7-04/c/knew': ['You knew from the start.', '…I knew. I didn\'t say. I thought you\'d run if I did. (She doesn\'t give the photo back. She puts it under her pillow.)'],
  'M7-04/c/thanks': ['Thank you for putting me on the ice.', 'Is that something to thank me for? …Fine. Be thankful. (She laughs. The room is bright.)'],
  'M7-05/c/hyeonsu_first': ['Do Hyeonsu put his in first.', 'That\'s the lad. Never says a word. (The chief shows me the first line of the donor roll. Do Hyeonsu. I\'m on the second.)'],
  'M7-05/c/giver': ['The one who gives. I remember that.', 'Then it\'s done. Your name won\'t go on the second floor. The guild\'s will. (I thought that was right.)'],
  'M7-06/c/scissors': ['My hand shook putting the scissors in hers. So did hers.', 'If you both shook, it was right. (From the wheelchair she takes my hand. For a long time.)'],
  'M7-06/c/all': ['This room belongs to everyone.', 'The ones who say that last. You were like that from the start. (Behind me, old Tak nods.)'],
  'M7-07/c/yours': ['It\'s your rod. You\'re the one who finished it.', '…No. It\'s your father\'s rod. I only finished it. (The boy holds out a last rod and reel. He made them. That one\'s mine, he says.)'],
  'M7-07/c/ours': ['It\'s our rod. My father started it, the old man watched over it, and you finished it.', '…Our rod. I like that. (The boy carves Saebyeok small into the blank. And my name beside it.)'],
  'M7-08/c/say_it': ['If you\'re going to cry, carry the ice first, then cry.', '(The kid lifts the crate. With his back. I\'ll have to tell him to lift with his legs.)'],
  'M7-08/c/sit': ['Sit down. This is a long story.', '(The kid sits. I open the first page of the logbook. A photo from twenty-two years ago is tucked inside.)'],
  'N01-1/c/blueprint': ['I\'ll take the plan. I\'ll make it myself.', 'Handiness is learned with hands. Come back if you can\'t manage it. (He shows me how to fold the plan as well as unfold it.)'],
  'N01-1/c/cash': ['I need the wages more than the plan.', '…Right, that\'s an answer too. It\'s an age when money\'s urgent. (He pulls notes from his pocket and hands them over without counting.)'],
  'N01-1/c/gift_fish': ['I gave the flounder for nothing. It\'s for a birthday table.', 'The wind blew the right way. Every harbour needs one of you. (Not only the plan — the stall grandmother speaks to me first now.)'],
  'N01-2/c/lesson': ['I watched how you talk to a child.', 'I didn\'t talk to him. I sat beside him. That\'s all. (I begin to understand what it means to learn how to sit beside someone.)'],
  'N01-2/c/pay': ['Pay me the wage, please.', 'I will. The money\'s in the cart. (He takes notes from the cart drawer.)'],
  'N01-2/c/decline': ['All I did was make a kid smile. It\'s fine.', '…The wind blew the right way. (People around Busan harbour start recognising me.)'],
  'N01-3/c/lesson': ['I learned how to dry them. That you can dry things other than herring.', 'That\'s it. That\'s what changing is. (The yard owner writes down the curing temperature for me.)'],
  'N01-3/c/pay': ['I\'ll take the price of the lifting.', 'Right. In the cart. (Baram says nothing at all about money.)'],
  'N01-3/c/decline': ['Lifting a few crates isn\'t work. It\'s fine.', '…The wind blew the right way. (The people at the Pohang drying yards know me now.)'],
  'N01-4/c/lesson': ['I learned how to place my feet on the rocks from him. The one who had the accident knows it best.', 'That\'s it. The one who\'s lost something knows best. (Rock safety settles into my body.)'],
  'N01-4/c/pay': ['Cover my fare out to Haegeumgang.', 'In the cart. (The money is always in the cart.)'],
  'N01-4/c/decline': ['I saw his hand on the net. That\'s enough.', '…The wind, the right way. (The rock anglers of Geoje know me now.)'],
  'N01-5/c/lesson': ['I watched her mother dive. Her breathing was different.', 'That\'s a haenyeo\'s breath. You can\'t learn it. You can watch it, though. (My time underwater lengthens a little.)'],
  'N01-5/c/pay': ['Cover my fare out to Jeju.', 'The cart. (The Jeju cart came over by ferry.)'],
  'N01-5/c/decline': ['The daughter made her choice. That\'s enough.', '…The wind, the right way. (The haenyeo of Jeju know me. As one of the water people.)'],
  'N01-6/c/why_less': ['Why is it all right to carry less?', '…I\'ll tell you at the next harbour. Sokcho. (In the bag\'s inner pocket there\'s a name tag with no name on it.)'],
  'N01-6/c/lesson': ['I should learn packing from the man with the cart.', 'Heavy at the bottom. What you use often at the top. That\'s all of it. (Load management settles into my hands.)'],
  'N01-6/c/decline': ['I\'ll take the bag. Keep the price of the night.', '…The wind, the right way. (The people of Ulleung know me.)'],
  'N01-7/c/name': ['Your name. I\'ll write it in the logbook.', '…Write it. First time it\'s been written anywhere in thirty years. (He gives me the cart key. He won\'t be pulling it any more.)'],
  'N01-7/c/lesson': ['Teach me how to walk the harbours. All thirty years of it.', 'One day per harbour. Faces first. (A map of every harbour in the country forms in my head.)'],
  'N01-7/c/decline': ['I saw you sit down. That\'s enough.', '…The wind, the right way. That\'s the last time I say it. (Around the country, my name goes round instead of Baram\'s.)'],
  'N02-1/c/lesson': ['Show me how to mend a rod.', 'It starts with the eye. Come here. (He taps the sections with a fingertip and has me listen. A living section and a dead one don\'t sound alike.)'],
  'N02-1/c/take_rod': ['If you\'ve a spare rod, give me one. For hole fishing.', 'It\'s cheap. A rod\'s a rod, though. Bring it back if it breaks. (From a corner he pulls out a short rod.)'],
  'N02-1/c/pay': ['Pay me the wage, please.', 'I will. An old man\'s errand money. (The hand that counts the notes is not the hand that touched the rod.)'],
  'N02-2/c/lesson': ['I watched Saebyeok pick the big culms. He chose by sound.', 'I taught him that. …All right, he hears it better than I do. (I get an ear for choosing culms.)'],
  'N02-2/c/pay': ['I\'ll take the fare to Taean and back.', 'You will. An old man\'s errand money. (His hand shakes counting the notes. Relief.)'],
  'N02-2/c/decline': ['I brought a child home. It\'s fine.', '…Thank you. First time I\'ve said that. (Saebyeok\'s regard rises quietly.)'],
  'N02-3/c/praise': ['Your rod beat a cod. I\'ll tell your grandfather myself.', 'You will? …Yeah. Please. (He gives me a length of bamboo. From his first rod, he says.)'],
  'N02-3/c/lesson': ['You called the drag timing right from beside me. Teach me more.', 'That\'s grandfather\'s— no. I know it too. When you can hear the bottom. (Drag control settles into my hands.)'],
  'N02-3/c/pay': ['You should be paid for the test fishing.', '…I\'ll give you all my pocket money. (He\'s serious. I have to take it.)'],
  'N02-4/c/both': ['Both your hands are in this rod.', '…Yeah. Grandfather\'s and mine. And your father\'s. (In the corner the old man smiles for the first time.)'],
  'N02-4/c/lesson': ['Teach me the last of it — how to lose the joint.', 'Match the grain. Section to section. (The last of the rod-building know-how settles into my hands.)'],
  'N02-4/c/pay': ['You should be paid for the rod. You\'re a craftsman.', '…Craftsman. Me? (He names a price, seriously. The old man shakes his head in the corner. Half, he says.)'],
  'N03-1/c/knot_lesson': ['I think I need to learn that knot. Show me again.', 'There are days a teacher learns from a student. Here — like this. (Her hands move far too fast.)'],
  'M4-10/c/together': ['Going together. Strange how easy that sounds.', '…Same. Don\'t say it out loud. (He hands me the fuel calculations. His handwriting is neat.)'],
  'M4-10/c/rival': ['See you at the Jeju tournament. We\'re rivals there.', 'Obviously. We\'re only on the same side aboard. (He laughs. I haven\'t seen that laugh in a long time.)'],
  'M5-01/c/dialect': ['I had to ask him to repeat the dialect three times. He laughed once.', 'If he laughed, it\'s fine. Get angry and the harbour fees go up. (In the congratulations envelope he\'s written out a few dialect phrases.)'],
  'M5-01/c/wind': ['The Jeju wind is salty. Different from the East Sea.', 'Get used to that wind and you can take Jeju passengers. (Handing over the envelope, he tucks in a passenger register form.)'],
  'M5-02/c/bow': ['I greeted the haenyeo. She didn\'t answer.', 'No answer is the answer. Greet her again next time. (Baram gives me a diving tool. Her own.)'],
  'M5-02/c/unsure': ['I can\'t tell whether that look was permission or a warning.', 'It\'s both. Another man\'s sea is always both. (He stubs out his cigarette and takes up the handcart.)'],
  'M5-03/c/slow': ['You\'re right that I\'m slow. Three squid, though.', 'Admit it and you get faster. (She gives me one of her own egi. For the tournament, she says.)'],
  'M5-03/c/tournament': ['I\'ll enter the heats. I\'ll beat your record.', 'Beat it, then! I\'m going all the way to twelve! (She fetches the registration papers before I can.)'],
  'M5-04/c/guide': ['Getting someone else onto fish. It\'s unfamiliar.', 'It should be. A guide who\'s comfortable loses passengers. (He slings a guide bag over my shoulder.)'],
  'M5-04/c/first_booking': ['The first booking is someone I know.', 'Then do it better. People you know are the worst. (The first page of the register in the bag is already filled in.)'],
  'M5-05/c/undecided': ['I still don\'t know which side I\'m on.', 'That\'s an honest answer. You don\'t have to know before the vote. (She gives me one of her reporter\'s notebooks.)'],
  'M5-05/c/sea_side': ['What the sea\'s side said stayed with me longer.', '…Don\'t say that on air. You can say it to me. (She hands over the notebook, smiling.)'],
  'M5-06/c/rules': ['By the rules. That sentence was the heaviest thing at the judges\' table.', 'It should be heavy. Light it isn\'t a tournament. (He hands over a finals number bib. A low number.)'],
  'M5-06/c/ask_past': ['From a storeroom to the judges\' table — what happened?', '…After the finals. (Then he hands me the bib. His face wavers for a moment.)'],
  'M5-07/c/keep_secret': ['I won\'t tell Serin.', '…Thank you. (Serin knew anyway. The egi Mara cast was hers.)'],
  'M5-07/c/tell': ['Serin should know it was you who cast it.', '…Then you tell her. I can\'t. (That night Serin was sitting outside Mara\'s door.)'],
  'M5-08/c/go_now': ['Never mind the results. I\'m going to Sokcho.', 'Go. The results won\'t run off. (He loads the prize gear crate onto my boat. A rod and a reel, with the tournament engraving.)'],
  'M5-08/c/wait_result': ['I\'ll hear the result and go. Five minutes.', '…Five minutes. You won. Now go. (His hands are quick handing over the crate.)'],
  'M5-09/c/hyeonsu_hand': ['Do Hyeonsu raised his hand on the same side.', 'I saw. He raised it first. Looking at your side of the room. (For the first time the chief talks about the lad at length.)'],
  'M5-09/c/hospital': ['Tell me about the hospital first.', '…She collapsed. She\'s conscious. Go to her. The vote is done. (He books the crossing for me before I can ask.)'],
  'M6-01/c/rod': ['I saw Sera wiping down her rod, so I wiped mine.', '…You saw that? I do it at night, always. (She tells me about one of her own spots behind the shop.)'],
  'M6-01/c/ramen': ['I never knew cup noodles could taste like this.', 'That\'s cancelled-sailing ramyeon. It\'s the best. (She says the next cancellation is on the house.)'],
  'M6-02/c/who': ['Who was your teacher?', '…The lighthouse. The keeper. Hear that story from him. (The next chapter opens.)'],
  'M6-02/c/silence': ['Teaching without words. That\'s what stayed with me.', '…It does, doesn\'t it. (She gives me a popper. Her teacher\'s, she says.)'],
  'M6-03/c/father': ['You\'re the first person I\'ve met who remembers my father.', '…I remember him. He was a good skipper. (He hands over a lighthouse lantern. An old one. Then another envelope — for running the light, he says.)'],
  'M6-03/c/weather': ['I learned how to log the weather. And why it\'s done by hand.', 'Machines break. Hands don\'t. (With the lantern he gives me a weather logbook.)'],
  'M6-04/c/trade': ['I see now why the origin labelling matters.', 'Know that and you know half of Incheon. (The section chief has a wholesale market pass made up for me.)'],
  'M6-04/c/two_hours': ['\'Just a moment\' turned into two hours.', 'It always does. That\'s snatched fishing for you. (He calls me again on his next way home.)'],
  'M6-05/c/promise': ['I\'ll write the rest. Down to the last page.', '…Good. (She closes her eyes. Her face is easy.)'],
  'M6-05/c/cry': ['…(I couldn\'t speak.)', 'If you\'re going to cry… carry the ice first, then cry. (She laughs. In a hospital room.)'],
  'M6-06/c/understood': ['Now I know why the ice came first.', '…Took you long enough. (She laughs anyway, and gives me a second key to the stall.)'],
  'M6-06/c/wrong_price': ['I called the wrong price on the second day. A customer corrected me.', 'I know which one. Thirty years a regular. (The next day that customer carried an ice crate for me.)'],
  'M6-09/c/bow': ['I sat up at the bow. Like the first time.', '…You remember. (The skipper prises the nameboard off the boat and gives it to me.)'],
  'M6-09/c/haena': ['Haena\'s steering was smoother than yours.', '…I can\'t admit that. No — I admit it. (Haena heard that from the wheelhouse.)'],
  'M6-07/c/fuel': ['I recalculated the fuel reserve. It was short.', 'Out there that shortfall is a life. (Stamping the approval, he gives me a spare fuel can.)'],
  'M6-07/c/paper_sea': ['A sea you reach through paperwork. I understand that now.', 'Understand it and you can go to Dokdo. (His stamping hand is slow. The hand of a man checking.)'],
  'M6-08/c/last_gift': ['Your last gift. I\'ll put it to use.', 'Use it. All the way to Dokdo. (Inside the voyage bag is a copy of the guild roll. My name is on the first page.)'],
  'M6-08/c/give_back': ['From now on I\'m the one who gives. I\'ll remember that.', 'Remember it. The second floor is waiting. (He brings up the Part Seven business for the first time.)'],
  'M7-01/c/end': ['I\'ve come to the end of the sea.', 'It isn\'t the end. It\'s where you turn back. That\'s what the logbook is. (Over the radio the old man says nothing for a long while.)'],
  'M7-01/c/three_hours': ['Three hours is short.', 'It has to be. Any longer and you\'d stop wanting to go back. (The lighthouse beam blinks once.)'],
  'M7-02/c/light': ['My hand felt light letting it go.', 'That hand is a surveyor\'s hand. (He gives me a survey team badge. Provisional, he says.)'],
  'M7-02/c/record': ['I\'ll record species in the logbook, not numbers.', 'People who record it that way fill all seventeen pages. (For the first time the chief looks through the logbook himself.)'],
  'M7-03/c/opened': ['I didn\'t close the logbook. I opened it.', '…Grown-ups say the strangest things. It\'s cool, though. (The boy asks if he can write his name on the last page. I said yes.)'],
  'M7-03/c/dokgu': ['The photo you took is the last page.', 'Really? My photo? (He clutches his camera. The completion money came from the guild.)'],
  'M2-09/c/ask_hyeonsu': ['I\'ll ask Do Hyeonsu myself.', 'You should. Better than scheming behind his back. (He hands over an envelope. It\'s fatter than I expected.)'],
  'M2-09/c/ignore': ['I won\'t lose sleep over one vote against.', 'That\'s one way. Just don\'t forget whose vote it was.'],
  'M2-11/c/worry': ['What\'s wrong with your hands? Have you seen a doctor?', 'It\'s age, that\'s all. Doctors cost more than ice. …I\'ll go, since you\'re asking. (That last part takes her a long time to say.)'],
  'M2-11/c/work': ['The display\'s done. I\'ll carry the ice.', 'The ice was your job from the start. (She laughs. It\'s a face I haven\'t seen in a while.)'],
  'M2-10/c/study': ['The weather section was hard. I\'ll study more.', 'Weather ought to be hard. It\'s the most frightening thing out there. (He holds out a winter reel.)'],
  'M2-10/c/easy': ['It was easier than I expected.', 'If the written was easy, the practical will be hard. Don\'t drop that reel in the sea.'],
  'M3-01/c/seasick': ['The seasickness was rough. I\'ll go out again anyway.', 'A lad who goes out again gets over it. The tablets are on the boat. (My name goes first on the next sailing list.)'],
  'M3-01/c/horizon': ['It was the first time I saw the horizon move.', '…If you saw that, it was enough. That\'s what you get on a boat for. (Briefly, for the first time, he meets my eye.)'],
  'M3-02/c/rhythm': ['That rhythm you set for me — my arms remembered it.', 'Then it\'s done. I won\'t set it for you next time. (He passes over a jigging rod. The grip is worn smooth.)'],
  'M3-02/c/arms': ['I\'ve still got arms left. One more cast.', '…Youth. Cast, then. Use this rod. (That day\'s catch was second best on the boat.)'],
  'M3-03/c/failed_once': ['I went in the water once. Passed on the second try.', 'That\'s normal. The ones who pass first time scrape more hulls later. (The congratulations envelope is thick.)'],
  'M3-03/c/boat_dream': ['Now I want a boat of my own.', 'Save up first. You don\'t buy a boat, you endure one. (Tucked in the envelope is a price list for used hulls.)'],
  'M3-04/c/wait': ['The waiting was the hardest part.', 'That\'s why nobody manages it. You did. (The drying-yard owner wraps up a string of the cured fish for me.)'],
  'M3-04/c/change': ['When the sea changes, people have to change. I think that\'ll stay with me.', 'Let it. Somebody said it to me once, too. (He stubs out his cigarette and takes up the handcart.)'],
  'M3-05/c/return': ['I chose to turn back. The boat came before the catch.', 'That\'s a skipper. Even without a boat yet. (From that day his voice changes when he calls my name.)'],
  'M3-05/c/regret': ['I think we could have pushed a little further.', '…The ones who thought that didn\'t come back out of the fog. Think again.'],
  'M3-06/c/father': ['I think my father knew this too.', '…He likely did. (She says nothing for a long time. Then she takes my hand, once.)'],
  'M3-06/c/record': ['All three told it differently. That\'s why it should be written down.', 'You write it down because they differ. If they agreed, one person would do. (She gives me another notebook.)'],
  'M3-07/c/count': ['You told me not to count. I counted anyway. About four hundred.', '…That\'s exactly why I said not to. Still, four hundred is a good release. (He slings a bag over my shoulder.)'],
  'M3-07/c/hope': ['If even a few come back, I\'ll catch them then. The big ones.', 'It\'s for people who talk like that that we release at all. (Inside the bag is a fry-release logbook.)'],
  'M3-08/c/broken': ['My father\'s rod is broken. The sea bream is the least of it.', '…I know. Everyone on the boat saw. A break can be mended. By old Tak, anyway. (The skipper wraps the broken section in cloth.)'],
  'M3-08/c/caught': ['The sea bream made it into the net, at least.', 'That\'s an angler for you — counting fish before rods. …Take the rod with you all the same. (He gathers the pieces up, one by one.)'],
  'M3-09/c/trust': ['I\'ll leave my father\'s rod with you. Your hands will do.', '…Don\'t say \'leave it with you\' so lightly. I\'ll take it all the same. (The hand that receives the bamboo doesn\'t shake.)'],
  'M3-09/c/learn': ['I want to learn rod building. I want to mend it myself.', '…I\'ve been waiting for that. Learn it. Learn it, and you\'ll cut the next one yourself. (Rod building opens up.)'],
  'M4-01/c/half': ['I\'ll fix half and mend the rest as I sail.', 'That\'s the answer. Nobody ever fixes it all before sailing. (She writes her own name on the estimate as guarantee.)'],
  'M4-01/c/worry': ['Is it all right to take a half-mended boat out?', 'I\'ve already picked which half stays broken. This is the half that works. (She shows me the inspection sheet. The eye of a first-rate helmsman.)'],
  'M4-02/c/name_why': ['I took one syllable of the boat\'s name from my father\'s boat.', '…It\'s a good name. (She unfolds her arms and smiles for the first time.)'],
  'M4-02/c/scared': ['Honestly, I was frightened. It\'s nothing like someone else\'s boat.', 'You should be. The ones who aren\'t are the dangerous ones. (She slips a helm note into the fuel envelope.)'],
  'M4-03/c/secret': ['I\'ll keep it quiet. The net work was good.', 'See! You\'re a mate! (He writes my name first on the next lamp-boat outing.)'],
  'M4-03/c/tell': ['I should tell the skipper. Get you proper net practice.', 'Ah… that\'s fair. That\'s fair. (The next day Chaegeumja has Pado drilling with the net. Pado glares at me. Grinning.)'],
  'M4-04/c/learned': ['A day lost over one life vest. I won\'t forget it.', 'No accidents happen on the boat of a skipper who says that. (The inspector writes my boat\'s name neatly into the register.)'],
  'M4-04/c/annoyed': ['Losing a whole day over one vest feels unfair.', 'Feel it, and you won\'t lose the next one. It is unfair. (He charges me only half the inspection fee anyway.)'],
  'M4-05/c/silent': ['I won\'t ask. The hairtail were beautiful.', '…Thank you. (She gives me a night at her hotel for the next trip out.)'],
  'M4-05/c/ask': ['What happened?', '…It was the day we argued. With him. Another time. (What matters is that she started talking at all.)'],
  'M4-06/c/seasick_guest': ['I sat the passenger who\'d gone down up at the bow, and he came back to life.', 'That\'s a skipper. People before catch. (He hands over a skipper\'s reel and stamps the register.)'],
  'M4-06/c/money': ['First time I\'ve taken money to carry someone. It feels strange.', 'It should. Once it stops, passengers become cargo. (He hands the reel over and says it twice.)'],
  'M4-07/c/shoe': ['I left one shoe out on the flats.', 'The flats took it. Toll money. (The old man gives me a pair of worn boots.)'],
  'M4-07/c/tide': ['The speed the water came back at frightened me.', 'Be frightened and you\'ll live. On the west coast the water is faster than a man. (He draws me a tide table by hand.)'],
  'M4-08/c/praise': ['The rod you built beat the swell.', '…I built it, right? Not grandfather? (The boy strokes the rod once more before handing it over.)'],
  'M4-08/c/teach_me': ['Your casting\'s better than mine, too. Teach me.', 'I\'m the one who makes them, though… all right, just once. (My surf casting stance changes.)'],
  'M4-09/c/ink': ['I got covered in ink.', 'That\'s cuttlefish for you. I storyboarded that shot. (In the final cut there\'s a frame of me taking the ink.)'],
  'M4-09/c/deadline': ['What are you going to do about your deadline?', '…I drew it all on the boat. The sea finished my deadline for me. (She tears off a page and signs it for me.)'],
  'M4-11/c/full_price': ['I\'ll charge the full fare. They\'re passengers.', 'That\'s right. (The two old ones each hold out an envelope. In old Tak\'s there is a strip of bamboo.)'],
  'M4-11/c/free': ['I can\'t take money from you two.', '…Lad. A skipper who won\'t charge his passengers doesn\'t last. Still, I\'ll take the thought today. (Instead of an envelope comes a letter of introduction stamped by the guild chief.)'],
  'M1-01/c/stand': ['I stand there a long while, then slip the photo back into my pocket.', '(The wind tries to turn the photo over. I hold it tight.)'],
  'M1-01/c/look': ['I have to do something. I walk toward the lights down at the harbour.', '(One stall light is still burning in the distance. My feet go that way first.)'],
  'M1-02/c/keep': ['I\'ll take it. I\'ll start with this.', 'You should. It\'s your money — spend it carefully. The crates come tomorrow too.'],
  'M1-02/c/give_back': ['Take the ice out of it. I\'ll leave half on the stall.', '…Don\'t talk nonsense. Leave it anyway. I\'ll remember you offered. (She pulls two ten-thousand notes from the envelope and puts them in the stall drawer.)'],
  'M1-02/c/ask_more': ['Will you take me on tomorrow as well?', 'If you\'re any use. I\'ve no work for a lad who drops crates once his hands go numb. (She hands over a few more coins — tomorrow\'s ice money, she calls it.)'],
  'M1-03/c/promise': ['I\'ll get it done inside a hundred and eighty days.', 'Easy to say. You don\'t count the days — the sea does. (She presses a tackle pouch into my hand.)'],
  'M1-03/c/why': ['Why are you giving this to me?', '…Because you didn\'t drop the ice crate. That\'s reason enough. (Her eyes say: don\'t ask further.)'],
  'M1-04/c/retort': ['It\'s your hands you\'re worried about breaking, not mine.', '…Quick with the mouth. Then land one on that rod next time. I\'ll be watching. (He doesn\'t unfold his arms.)'],
  'M1-04/c/swallow': ['I\'ll take it as advice. The Saiso rod wasn\'t bad.', 'It isn\'t advice. It\'s fact. (Still, one corner of his mouth lifts for a moment.)'],
  'M1-04/c/ask': ['Why do you fish here, anyway?', '…My grandfather runs the guild. Beyond that it\'s none of your business. (Even as he turns away, he looks at my rod one more time.)'],
  'M1-05/c/thanks': ['That stance you fixed — it helped.', '…Calling it help sounds strange. You were just painful to watch. (He backs my drag off half a turn.)'],
  'M1-05/c/proud': ['Two fish. Like you said, the second one was skill.', 'Getting cocky snaps rods. Still… today you\'re right.'],
  'M1-06/c/accept_law': ['I won\'t sell anything I take on a rod. I\'ll eat it or let it go.', 'That\'s where it starts. That\'s the lesson that comes before catching. (She looks out at the sea once and nods.)'],
  'M1-06/c/grumble': ['Aren\'t the rules a bit tight? A person has to eat.', 'They\'re tight, and that\'s why there\'s still a sea. Eating is another road. Traps, bare hands, day wages. Learn them.'],
  'M1-06/c/ask_why': ['Why do you keep these rules yourself?', '…Because my husband didn\'t. Let\'s leave that. (From the stall drawer she takes out a worn measuring rule and gives it to me.)'],
  'M1-07/c/taste': ['Would you try a slice?', '…Too thick. But you cut with the grain. (He takes a butchery knife from its sheath and sets it beside the board.)'],
  'M1-07/c/humble': ['The thickness is still all over the place. I\'ll keep practising.', 'Practice is done by hands, not mouths. Use this knife. It\'s gone heavy in mine.'],
  'M1-08/c/thanks': ['It sits right in the hand. Thank you.', 'A rod ought to. A bag too. (He tosses over a spare strip of bamboo. Material for the next one.)'],
  'M1-08/c/critic': ['The shoulder strap runs a little short. Is that how the plan has it?', '…I\'ll make it longer. Next one you cut yourself. You\'ve got an eye. (He writes something in the corner of the plan.)'],
  'M1-08/c/ask_rod': ['Do you make rods out of bamboo too?', 'I do. Fifty years of it. I may have seen your father\'s rod here. …No. That\'s for later.'],
  'M1-09/c/cold': ['My hands are so cold I can\'t even hold the net.', 'That\'s the sea for you. Go inside before the chills set in. Doctors cost more than the catch. (She pushes a cup of hot water toward me.)'],
  'M1-09/c/excited': ['I never knew the sea at night was this different. I want to go out again.', '…Careful with that look. The ones the night takes are the first to slip. But if you\'re going out, use this lantern.'],
  'M1-10/c/name': ['I have a name too, you know.', 'I know it. I\'ll use it once the general meeting is done. Until then you\'re a trainee. That\'s the rule. (Still, he writes my name in the roll once.)'],
  'M1-10/c/work': ['I\'ll come out tomorrow as well.', 'Good. Tomorrow it\'s nets. Your hands will hurt.'],
  'M1-11/c/humble': ['There\'s still a lot to learn. Guild member is a heavy word.', 'The ones who say that last longest. (The chief opens the first page of the roll. Guild members — and my name under it.)'],
  'M1-11/c/proud': ['A hundred and eighty days. I filled every one.', 'You filled the days. Being a member starts now. I\'ll see you at the Busan auction hall.'],
  'M1-11/c/hyeonsu': ['I didn\'t expect Do Hyeonsu not to object.', '…The lad didn\'t withhold his vote — he couldn\'t cast it. He saw everything you did. Hear the rest from him.'],
  'M2-01/c/watch': ['I was watching the order the auctioneer raised his hand in. I think I\'ll read it better next time.', 'That eye is nerve. And nerve is something you can put into a skill now. (He hands over the envelope for the crates.)'],
  'M2-01/c/nervous': ['Seeing my own name on a crate still feels strange.', 'It should. Start worrying when it stops feeling strange. (Handing over the envelope, he adds a sample regulation crate on top.)'],
  'M2-02/c/own': ['It\'s my fault. I went short on ice.', 'A lad who says that doesn\'t lose the next crate. (He adds that the guild will cover the ice next time.)'],
  'M2-02/c/excuse': ['It was a long way to the auction hall.', 'You measured that distance. You packed that ice. Next time both are still yours.'],
  'M2-03/c/rival': ['I heard that — you said you\'d give me that much.', 'Once. Not twice yet. (And still he holds out his spare rod.)'],
  'M2-03/c/lost_rigs': ['I lost two rigs. Gamcheon is a sea that teaches more than it gives.', 'You know the sea by the rigs you leave in it. That rod\'s tuned for the wind here. Take it.'],
  'M2-04/c/steady': ['The price can come later. I\'ll keep bringing them.', 'That sentence is the contract. (She tapes a slip with my name beside the tank.)'],
  'M2-04/c/price': ['I\'d like to set the unit price now.', '…In a hurry. Well, you\'ve come three times. (She works the calculator. The first price is low.)'],
  'M2-05/c/notes': ['I compared notes with Do Hyeonsu. His were more thorough.', 'I know. That\'s the kind of lad he is. You\'ve got something else. (He hands over a letter of introduction to the lure shop.)'],
  'M2-05/c/lure': ['I want to get a lure in the water.', 'Learn the action before you cast it. With lures the bait isn\'t the bait — your hand is.'],
  'M2-06/c/camera_no': ['Please don\'t film my face.', 'Sure! Just hands and rod. Hands look better anyway, honestly. (She packs the bag for me all the same.)'],
  'M2-06/c/camera_ok': ['Film away. Nobody knows me regardless.', 'Thank you! You\'re my first guest. (My cast stays in the final cut for a long while.)'],
  'M2-07/c/coop': ['I\'ll go with the guild party. I\'d rather go with people.', 'Good. That\'s a member\'s answer. (He puts my name on the next outing.)'],
  'M2-07/c/park': ['I\'ll buy a ticket for the fishing park. I\'d rather solve it with money.', 'The easy road is a road too. And the fee\'s on you. (The guild covers half of it anyway.)'],
  'M2-07/c/boat': ['I\'ll go out on a boat. I\'ve been wanting to.', '…Boats are a later chapter. Still, I\'ll note that you asked.'],
  'M2-08/c/ask_rod': ['Why does this reel rod interest you?', '…I\'ve seen hands like that before. Another time. (He presses a lure into my hand. An old one.)'],
  'M2-08/c/just_fish': ['Three rockfish. That\'s enough for today.', 'The anglers who talk like that keep at it longest. (He gives me a little money — for the lamp battery, he says.)'],
};
