/**
 * @file StoryQuestDatabase.ts
 * @description 메인 「조행록」 65퀘 + NPC 17아크 55퀘 = 120퀘 (134차, STORY_SPEC_v3 §9·§10·§12)
 *
 * - id: 메인 `M{챕터}-{번호}` · 서브 `N{아크}-{번호}` (스펙 표기 그대로).
 * - xp: 스펙 표 값 그대로 — `validateStoryQuests()`가 챕터별 수·합계를 `STORY_CHAPTERS.contract`와 대조한다.
 * - objectives: 자동 추적기가 있는 종류(catch/release/craft/butcher/sashimi/license/gather/trap/visit/reachLevel/
 *   earn/sell/custom-이벤트)는 client 훅이 채우고, `manual: true`는 대화 패널 [완료]로 닫는다(§0.5-7).
 * - 지역 id는 WorldMap `RegionDef.id`. 하위 권역은 `JournalPages.areaKey`에만 있다.
 *
 * ⚠ 어종 id 대체(§0.5): 임연수어→도루묵 · 호래기→볼락 · 지세포 볼락→광어 · 주꾸미→갑오징어 · 돗돔→대구.
 */

import type { StoryObjective, StoryQuestDef, Season } from '../types/Story.js';
import { STORY_CHAPTERS } from './StoryChapters.js';

// ── 헬퍼 ──
const talk = (npcId: string, ko: string, en: string): StoryObjective => ({ kind: 'talk', npcId, labelKo: ko, labelEn: en, manual: true });
const man = (kind: StoryObjective['kind'], ko: string, en: string, extra: Partial<StoryObjective> = {}): StoryObjective => ({ kind, labelKo: ko, labelEn: en, manual: true, ...extra });
const auto = (kind: StoryObjective['kind'], ko: string, en: string, extra: Partial<StoryObjective> = {}): StoryObjective => ({ kind, labelKo: ko, labelEn: en, ...extra });
const fish = (speciesId: string | undefined, ko: string, en: string, extra: Partial<StoryObjective> = {}): StoryObjective =>
  ({ kind: 'catch', speciesId, selfCaught: true, target: 1, labelKo: ko, labelEn: en, ...extra });
const cull = (speciesId: string, ko: string, en: string, target = 1): StoryObjective =>
  ({ kind: 'cull', speciesId, target, labelKo: ko, labelEn: en });
const W: Season[] = ['winter']; const SU: Season[] = ['summer']; const AU: Season[] = ['autumn'];

const SOK = 'gangwon_sokcho', BUS = 'busan', ULS = 'ulsan', POH = 'gyeongbuk_pohang', GEO = 'gyeongnam_geoje',
  YEO = 'jeonnam_yeosu', TAE = 'chungnam_taean', JEJ = 'jeju', ULL = 'ulleungdo', INC = 'incheon', DOK = 'dokdo';

type MainRow = [id: string, ch: 1|2|3|4|5|6|7, lv: number, xp: number, giver: string, region: string,
  titleKo: string, titleEn: string, descKo: string, descEn: string, objectives: StoryObjective[], extra?: Partial<StoryQuestDef>];
const PART_OF: Record<number, 1|2|3|4|5> = { 1: 1, 2: 2, 3: 3, 4: 3, 5: 4, 6: 5, 7: 5 };

function mainRows(rows: MainRow[]): StoryQuestDef[] {
  const out: StoryQuestDef[] = [];
  rows.forEach((r, i) => {
    const [id, chapter, minLevel, xp, giver, region, titleKo, titleEn, descKo, descEn, objectives, extra] = r;
    const prev = i > 0 ? rows[i - 1][0] : null;
    out.push({ id, kind: 'main', part: PART_OF[chapter], chapter, titleKo, titleEn, descKo, descEn, minLevel, xp, giver, region,
      prereq: prev ? [prev] : [], objectives, ...extra });
  });
  return out;
}

// ─────────────────────────────────────────────
// 제1부 「실습생」 — Ch1 속초 · 11퀘 · 4,400 XP (튜토리얼 전담)
// ─────────────────────────────────────────────
const MAIN: StoryQuestDef[] = mainRows([
  ['M1-01', 1, 1, 240, '', SOK, '막차', 'The Last Bus',
    '산골집 문을 잠그고 돌아보지 않는다. 종점은 영금정 — 22년 전 가족사진과 같은 자리.',
    'You lock the mountain house and don\'t look back. The last stop is Yeonggeumjeong — the same spot as the family photo, 22 years ago.',
    [auto('visit', '영금정에 도착한다', 'Arrive at Yeonggeumjeong', { placeKey: 'poi:yeonggeumjeong' })],
    { teaches: ['movement', 'inventory', 'statusPanel', 'worldMap'] }],
  ['M1-02', 1, 2, 270, 'okseon', SOK, '얼음 나르기', 'Hauling Ice',
    '영금정에서 이어진 기억을 따라 정옥선의 심부름을 돕는다. 얼음 상자를 옮기며 시장의 첫 일과 첫 품삯을 배운다.',
    'The memory leads you to Ok-seon. Carrying her ice crate becomes your first market errand and your first wages.',
    [auto('custom', '정옥선에게 받은 심부름용 얼음을 경매장에 전달한다 (대화 → 일감)', 'Deliver Ok-seon\'s errand ice to the auction hall (talk → day job)', { placeKey: 'job:ice_haul' }),
      auto('visit', '직판장 상점을 열어 본다', 'Open the market shop', { placeKey: 'shop:any' })],
    { teaches: ['wages', 'shop'], rewards: { coins: 30000 }, reputation: { harbor: { gangwon_sokcho: 2 } } }],
  ['M1-03', 1, 3, 300, 'okseon', SOK, '열쇠 두 개', 'Two Keys',
    '좌판 뒤 옛 어촌계 숙소. 먼지와 곰팡내. 실습생 증을 받는 순간 D-180이 시작된다.',
    'The old co-op lodging behind the stall — dust and mildew. The moment you take the trainee card, D-180 begins.',
    [auto('visit', '홈타운(숙소)에 들어간다', 'Enter the hometown lodging', { placeKey: 'region:hometown' }),
      auto('custom', '침대에서 저장하고 쉰다', 'Save and rest in the bed', { placeKey: 'bedSave' })],
    { teaches: ['homeBase', 'save', 'placement', 'deadline'], deadline: { days: 180, onMiss: 'cost' }, unlocks: ['trainee'], rewards: { items: [{ id: 'qr_tackle_pouch', qty: 1, bound: true }] } }],
  ['M1-04', 1, 4, 330, 'hyeonsu', SOK, '사이소 영수증', 'The Saiso Receipt',
    '라이벌의 첫 시비 겸 첫 강습. "그 대는 아까우니까 여기다 쓰지 마." 저가 장비로 테트라포드 구멍치기.',
    'The rival\'s first jab and first lesson. "Don\'t waste that rod here." Budget gear, hole fishing in the tetrapods.',
    [auto('custom', '생활용품점 사이소에서 저가 릴대 구입', 'Buy a budget rod at the Saiso daily-goods store', { placeKey: 'buy:inv_rod_budget' }),
      fish(undefined, '방파제에서 물고기 1마리 낚기', 'Catch one fish at the breakwater', { spotKind: 'breakwater' })],
    { teaches: ['budgetGear', 'holeFishing', 'tetrapodSafety'] }],
  ['M1-05', 1, 5, 360, 'hyeonsu', SOK, '첫 캐스팅', 'First Cast',
    '아버지의 릴대를 처음 편다. 캐스팅 · 찌 채비 · 입질 → 챔질 → 파이팅 → 랜딩 전 구간.',
    'You extend your father\'s rod for the first time. Casting, the float rig, bite → hookset → fight → landing.',
    [fish(undefined, '캐스팅으로 물고기 2마리 낚기', 'Catch two fish by casting', { target: 2 })],
    { teaches: ['casting', 'floatRig', 'bite', 'fight'], rewards: { items: [{ id: 'qr_rod_heirloom', qty: 1, bound: true }, { id: 'qr_reel_heirloom', qty: 1, bound: true }] } }],
  ['M1-06', 1, 7, 390, 'okseon', SOK, '팔 수 없는 물고기', 'The Fish You Cannot Sell',
    '"네가 잡은 건 네가 먹어라. 그게 법이다. 계원이 돼도 낚싯대로 잡은 건 못 판다." 법 규칙 5조 · 준법 방생.',
    '"What you catch, you eat. That is the law. Even as a member, rod-caught fish cannot be sold." The five rules · lawful release.',
    [auto('release', '금지체장·금어기 개체를 준법 방생한다', 'Lawfully release an undersized or closed-season fish'),
      talk('okseon', '정옥선에게 법 규칙을 듣는다', 'Hear the rules from Ok-seon')],
    { teaches: ['law', 'measure', 'release', 'codex'], reputation: { sea: 1 } }],
  ['M1-07', 1, 9, 420, 'okseon', SOK, '부엌의 순서', 'The Order of the Kitchen',
    '2년 만에 제대로 된 밥. 손질 → 회뜨기 → 신선도·보관 → 요리.',
    'The first proper meal in two years. Butchery → sashimi → freshness → cooking.',
    [auto('butcher', '원물 1마리 손질', 'Butcher one whole fish'),
      auto('sashimi', '회뜨기 1회', 'Slice sashimi once')],
    { teaches: ['butchery', 'sashimi', 'freshness', 'cooking'], rewards: { items: [{ id: 'qr_knife_okseon', qty: 1, bound: true }], shopUnlocks: ['mart_pro_knife'] } }],
  ['M1-08', 1, 11, 450, 'tak_mansu', SOK, '간이 백팩', 'The Improvised Backpack',
    '죽간 장인의 첫 교습. "짐부터 어떻게 좀 해라." 제작대 · 도면 · 핸드크래프팅.',
    'The bamboo-rod master\'s first lesson. "Sort your baggage out first." Workbench, blueprints, hand-crafting.',
    [auto('craft', 'U 창 제작 탭에서 도면 1개 제작', 'Craft one blueprint in the U window'),
      auto('custom', '간이 백팩 제작 후 착용 (인벤 +5칸)', 'Craft and equip the improvised backpack (+5 slots)',
        { placeKey: 'equip:bag' })],
    { teaches: ['crafting', 'backpack'] }],
  ['M1-09', 1, 13, 480, 'okseon', SOK, '밤바다', 'Night Sea',
    '물때표를 처음 스스로 읽는다. 간조 · 허용 어구 · 마을어업권 · 헤드랜턴 · 오한 · 응급처치.',
    'You read the tide table yourself for the first time. Low tide, permitted gear, village fishery, headlamp, chill, first aid.',
    [auto('gather', '해루질로 2개체 채집', 'Gather two creatures on the tideland', { target: 2 })],
    { teaches: ['tideland', 'tideTable', 'lantern', 'cold', 'firstAid', 'villageFishery'], rewards: { items: [{ id: 'qr_headlamp_trainee', qty: 1, bound: true }] } }],
  ['M1-10', 1, 16, 520, 'coop', SOK, '공동작업', 'Community Work',
    '이름이 아니라 "실습생"으로 불린다. 양망 보조 · 미역 정리 · 자전거 수리·탑승 · 스킬 포인트 첫 투자.',
    'They call you "trainee", not by name. Net hauling, seaweed sorting, fixing and riding the bicycle, your first skill point.',
    [auto('communityWork', '어촌계 공동작업 1회 참여 (어촌계장 대화 → 일감)', 'Take part in one community work session (talk to the co-op head → day job)'),
      auto('custom', '자전거에 탑승한다', 'Ride the bicycle', { placeKey: 'bikeMount' })],
    { teaches: ['communityWork', 'bicycle', 'skills', 'reputation'], rewards: { coins: 50000 }, reputation: { harbor: { gangwon_sokcho: 3 } } }],
  ['M1-11', 1, 18, 640, 'coop', SOK, '총회', 'The General Meeting',
    'D-11에 통과. 서류 4종 → 신고어업 등록 → 예비계원 → 어촌계원 승낙. 처음으로 이름이 불린다.',
    'Passed at D-11. Four documents → reported fishery → candidate → accepted as a member. The first time they say your name.',
    [auto('reachLevel', '레벨 18 도달', 'Reach level 18', { target: 18 }),
      talk('coop', '어촌계 총회에 선다', 'Stand before the general meeting')],
    { teaches: ['licenseFlow', 'auction'], rewards: { licenses: ['reported_fishery', 'coop_member'] }, unlocks: ['region:busan', 'auction'],
      reputation: { harbor: { gangwon_sokcho: 5 } } }],

  // ─────────────────────────────────────────────
  // 제2부 「위판」 — Ch2 부산 · 10퀘 · 29,500
  // ─────────────────────────────────────────────
  ['M2-01', 2, 20, 1750, 'coop', BUS, '첫 위판', 'First Auction',
    '내 이름이 붙은 첫 상자. 위판 등록 · 상자 규격 · 등급 판정 — 통발 어획물로 §3 규칙 실전 적용.',
    'The first crate with your name on it. Auction registration, crate grades — the rules applied for real, with trap catch.',
    [auto('trap', '통발 1회 수거', 'Harvest one trap'), auto('sell', '통발 어획물 위판', 'Auction the trap catch')],
    { rewards: { coins: 150000, skillUnlocks: ['eco_auction'], shopUnlocks: ['market_crate_pro'] } }],
  ['M2-02', 2, 22, 2000, 'coop', BUS, '유찰', 'Unsold',
    '얼음을 아낀 대가. 경매 유찰 · 선도 관리 복기.',
    'The price of saving on ice. An unsold lot, and a freshness post-mortem.',
    [auto('sell', '선도를 다시 잡아 위판 3건을 성사시킨다', 'Fix your freshness handling and get three lots sold', { target: 3 }),
      man('custom', '유찰 복기 — 쿨러 얼음 관리', 'Post-mortem — cooler ice management')]],
  ['M2-03', 2, 24, 2250, 'hyeonsu', BUS, '감천항의 겨울', 'Winter at Gamcheon',
    '밑걸림 · 채비 유실 · 회수. 감성돔 40cm 이상.',
    'Snags, lost rigs, recovery. A black seabream over 40 cm.',
    [fish('black_seabream', '감성돔 40cm+ 자가어획 (겨울)', 'Catch a black seabream 40 cm+ (winter)', { minCm: 40, season: W })],
    { journalPage: 2, rewards: { items: [{ id: 'qr_rod_gamcheon', qty: 1, bound: true }] } }],
  ['M2-04', 2, 27, 2500, 'na_gibeom', BUS, '남의 가게', 'Someone Else\'s Shop',
    '횟집 사장은 값이 아니라 꾸준함을 산다. 납품 계약 · 단가 · 신용.',
    'The restaurant owner buys consistency, not price. Contracts, unit prices, credit.',
    [auto('trap', '통발을 3번 걷어 납품거리를 만든다', 'Haul the traps three times to build a supply', { target: 3 }),
      auto('butcher', '넘기기 전 손질 3마리', 'Butcher three before handing them over', { target: 3 })]],
  ['M2-05', 2, 30, 2750, 'coop', BUS, '품질관리 교육', 'Quality Control Course',
    '교실에서 도현수와 나란히. 위생 · 이력 표기 · 루어 개방.',
    'In the classroom, next to Hyeon-su. Hygiene, traceability, lures unlocked.',
    [auto('butcher', '배운 위생 절차대로 2마리 손질', 'Butcher two by the hygiene procedure you were taught', { target: 2 }),
      auto('sashimi', '이력을 적어 회 1접시', 'Slice one plate and write its trail'),
      man('custom', '수산물 품질관리 교육 이수', 'Complete the seafood quality course')],
    { unlocks: ['lure'], teaches: ['lure'], rewards: { skillUnlocks: ['fish_lure'], shopUnlocks: ['market_lure_starter'] } }],
  ['M2-06', 2, 33, 3000, 'seo_harin', BUS, '암남공원의 밤', 'Night at Amnam Park',
    '야간 루어 전갱이 · 통발 제작.',
    'Night lure for horse mackerel · trap crafting.',
    [fish('horse_mackerel', '전갱이 자가어획 (겨울 야간)', 'Catch a horse mackerel (winter night)', { season: W }),
      auto('craft', '통발 1개 제작', 'Craft one trap')],
    { journalPage: 3, rewards: { items: [{ id: 'qr_bag_field', qty: 1, bound: true }] } }],
  ['M2-07', 2, 36, 3250, 'coop', BUS, '통제선', 'The Control Line',
    '방파제 출입통제 → 합법 우회 3종(어촌계 동행 · 낚시공원 입장 · 선상). 몰래 넘는 선택지는 없다.',
    'The breakwater is closed → three legal ways round (co-op escort, fishing park, boat). Sneaking over is not an option.',
    [fish(undefined, '통제선을 넘지 않고 갯바위에서 2마리', 'Catch two from the rocks without crossing the line', { spotKind: 'shore', target: 2 }),
      man('custom', '합법 우회 경로 1개 선택', 'Choose one legal route')],
    { reputation: { sea: 1 } }],
  ['M2-08', 2, 39, 3500, 'jim_kang', BUS, '백운포의 볼락', 'Rockfish at Baegunpo',
    '야간 소형 어종 · 집어등. 볼락 3마리.',
    'Small fish at night under lights. Three rockfish.',
    [fish('dark_banded_rockfish', '볼락 3마리 자가어획 (겨울 야간)', 'Catch three rockfish (winter night)', { target: 3, season: W })],
    { journalPage: 4 }],
  ['M2-09', 2, 42, 3800, 'coop', BUS, '총회', 'The General Meeting',
    '계원 지위 심사 · 항구 신뢰 반영. 도현수가 반대표를 던진다. 그래도 통과.',
    'Membership review, harbour trust counts. Hyeon-su votes against. You pass anyway.',
    [auto('sell', '심사에 낼 실적 — 위판 5건', 'Your record for the review — five consigned lots', { target: 5 }),
      talk('coop', '분기 총회에 선다', 'Stand at the quarterly meeting')],
    { reputation: { harbor: { busan: 5 } }, rewards: { coins: 400000 } }],
  // 137차 — 회귀 고리 ①. 부산에서 배운 것을 속초로 되돌린다(이전 맵 재활용).
  ['M2-11', 2, 43, 2950, 'okseon', SOK, '되돌아온 상자', 'The Box That Came Back',
    '부산에서 배운 상자 규격과 등급 판정을 속초 좌판에 되돌려준다. 정옥선의 손이 예전 같지 않다 — 얼음 다루는 속도가 눈에 띄게 느려졌다.',
    'You bring the crate standards and grading you learned in Busan back to the Sokcho stall. Ok-seon\'s hands are not what they were — she is visibly slower with the ice.',
    [auto('visit', '속초 만복상회로 돌아간다', 'Return to the Manbok Store in Sokcho', { placeKey: 'region:gangwon_sokcho' }),
      man('custom', '부산 상자 규격으로 좌판 진열을 고친다', 'Rebuild the stall display to Busan crate standards')],
    { teaches: ['returnTrip', 'grading'], reputation: { harbor: { gangwon_sokcho: 3 } } }],
  ['M2-10', 2, 44, 4700, 'coop', BUS, '면허 학원', 'Licence School',
    '"배를 몰 줄 알아야 겨울 바다를 안다." 선박조종면허 필기 · 울산·포항 개방.',
    '"You don\'t know the winter sea until you can pilot a boat." Written exam · Ulsan and Pohang open.',
    [auto('sell', '학원비를 마련한다 — 위판 4건', 'Pay for the course — four consigned lots', { target: 4 }),
      man('custom', '선박조종면허 필기 합격', 'Pass the written vessel exam')],
    { unlocks: ['region:ulsan', 'region:gyeongbuk_pohang'], rewards: { items: [{ id: 'qr_reel_winter', qty: 1, bound: true }] } }],

  // ─────────────────────────────────────────────
  // 제3부 「겨울 배」 — Ch3 울산·포항 · 9퀘 · 67,950
  // ─────────────────────────────────────────────
  ['M3-01', 3, 45, 4450, 'go_manseok', ULS, '방어진 입항', 'Into Bangeojin',
    '남의 배에 얹혀 배우는 마지막 시기. 배 출조 파이프라인 전 구간.',
    'The last time you learn on someone else\'s boat. The whole boat-trip pipeline.',
    [fish('yellowtail', '고래마루가 세워 준 자리에서 방어 1마리', 'One yellowtail where the Goraemaru puts you'),
      man('boatTrip', '고래마루 승선 1회', 'One trip aboard the Goraemaru')],
    { teaches: ['boatTrip', 'seasickness'] }],
  ['M3-02', 3, 48, 5150, 'go_manseok', ULS, '지깅', 'Jigging',
    '저킹 · 폴링 · 고속 콤보. 방어 40cm 이상.',
    'Jerking, falling, fast combos. A yellowtail over 40 cm.',
    [fish('yellowtail', '방어 40cm+ 자가어획 (겨울)', 'Catch a yellowtail 40 cm+ (winter)', { minCm: 40, season: W })],
    { journalPage: 5, teaches: ['jigging'], rewards: { skillUnlocks: ['fish_jig'], items: [{ id: 'qr_rod_jig', qty: 1, bound: true }] } }],
  ['M3-03', 3, 52, 5900, 'coop', ULS, '실기 시험', 'The Practical',
    '계류 · 변침 · 인명구조. 한 번 떨어져도 된다.',
    'Mooring, course change, rescue. Failing once is allowed.',
    [auto('license', '소형선박조종사 실기 합격', 'Pass the small-vessel practical', { licenseId: 'boat_operator' })],
    { rewards: { licenses: ['boat_operator'], coins: 600000 } }],
  ['M3-04', 3, 55, 6650, 'baram', POH, '덕장', 'The Drying Racks',
    '청어가 안 든다. 건조 · 숙성 제작.',
    'The herring aren\'t coming. Drying and curing.',
    [fish(undefined, '덕장에 걸 물고기 3마리', 'Three fish for the racks', { target: 3 }),
      auto('craft', '건조·숙성 제작 1회', 'One drying/curing craft')]],
  ['M3-05', 3, 58, 7400, 'go_manseok', ULS, '해무', 'Sea Fog',
    '무리하지 않고 돌아오는 것도 실력. 기상 이벤트 생존 · 귀항 판단.',
    'Turning back without pushing it is a skill too. Weather event, the call to return.',
    [fish(undefined, '해무가 덮기 전에 2마리를 올린다', 'Land two before the fog closes in', { target: 2 }),
      man('survive', '해무 귀항 판단', 'Make the sea-fog return call')],
    { teaches: ['weather'] }],
  ['M3-06', 3, 61, 8100, 'okseon', POH, '명태를 본 적 있어요?', 'Have You Ever Seen a Pollock?',
    '노인들의 기억을 받아 적는다. 조행록의 용도를 처음 이해한다. 도감 "포획 금지" 상태.',
    'You write down the old men\'s memories. You understand what the log is for. A "no take" codex entry.',
    [auto('release', '노인들이 말한 그 물고기를 만나면 놓아준다', 'Meet the fish they spoke of, and let it go'),
      man('custom', '구술 채록 3건', 'Three oral-history entries', { target: 3 })],
    { teaches: ['oralHistory'] }],
  ['M3-07', 3, 64, 8850, 'coop', POH, '종묘방류', 'Restocking',
    '자원 회복 이벤트 · 치어 보호. 바다 평판 대폭 상승.',
    'A restocking event, protecting fry. Sea reputation climbs.',
    [auto('release', '치어를 바다로 돌려보낸다 5회', 'Return five fry to the sea', { target: 5 })],
    { reputation: { sea: 3 }, teaches: ['restocking'], rewards: { items: [{ id: 'qr_bag_expedition', qty: 1, bound: true }] } }],
  ['M3-08', 3, 67, 9600, 'go_manseok', POH, '겨울 참돔', 'Winter Red Seabream',
    '타이라바 · 대물 파이팅 · 장비 한계. 유품 릴대가 부러진다.',
    'Tai-rubber, a big fight, the limit of the gear. Your father\'s rod breaks.',
    [fish('red_seabream', '참돔 자가어획 (봄·가을 새벽/저녁)', 'Catch a red seabream (spring/autumn dawn or dusk)', { season: ['spring', 'autumn'] })],
    { journalPage: 6, unlocks: ['rodBroken'] }],
  ['M3-09', 3, 69, 11850, 'tak_mansu', POH, '배를 보러 가자', 'Let\'s Go See a Boat',
    '중고 선박 시세 · 거제 개방. 탁 노인이 새 죽간을 건넨다.',
    'Used-boat prices, Geoje opens. Old Tak hands you a new bamboo rod.',
    [auto('sell', '뱃값 밑천 — 위판 8건', 'Seed money for a boat — eight consigned lots', { target: 8 }),
      talk('tak_mansu', '탁만수에게 새 죽간을 받는다', 'Receive the new rod from Tak Man-su')],
    { unlocks: ['region:gyeongnam_geoje', 'region:jeonnam_yeosu', 'region:chungnam_taean'], rewards: { items: [{ id: 'qr_rod_bamboo', qty: 1, bound: true }], skillUnlocks: ['craft_rod'], shopUnlocks: ['daily_workshop_pro'] } }],

  // ─────────────────────────────────────────────
  // 제3부 「내 배」 — Ch4 거제·여수·태안 · 10퀘 · 147,000
  // ─────────────────────────────────────────────
  ['M4-01', 4, 70, 8700, 'chae_geumja', GEO, '지세포 조선소', 'Jisepo Shipyard',
    '돈이 모자라 절반만 고친다. 선체 검수 · 수리 견적.',
    'Not enough money — you fix half. Hull inspection, repair estimate.',
    [auto('earn', '재화 5,000,000원 보유', 'Hold 5,000,000 won', { target: 5_000_000 })]],
  ['M4-02', 4, 73, 9950, 'chae_geumja', GEO, '첫 배', 'First Boat',
    '이름을 직접 정한다. 보트 운항 개방.',
    'You name it yourself. Boat operation unlocked.',
    [fish(undefined, '내 배로 나가 첫 3마리', 'Three fish on your own boat\'s first run', { target: 3 }),
      man('boatTrip', '자기 배 첫 운항', 'First run in your own boat')],
    { teaches: ['boatOwnership'], unlocks: ['ownBoat'], rewards: { skillUnlocks: ['drv_boat'], coins: 1500000 } }],
  ['M4-03', 4, 76, 11200, 'chae_pado', GEO, '지세포의 밤', 'Night at Jisepo',
    '야간 루어 · 소형 등선. 광어(다운샷).',
    'Night lure from a small lit boat. Flatfish on a downshot.',
    [fish('flatfish', '광어 자가어획 (봄·가을 주간)', 'Catch a flatfish (spring/autumn daytime)', { season: ['spring', 'autumn'] })],
    { journalPage: 7 }],
  ['M4-04', 4, 80, 12500, 'coop', GEO, '안전 검사', 'Safety Inspection',
    '구명장비 · 검사 체크리스트. 한 항목 미달로 재검사.',
    'Life-saving gear, the checklist. One item short — re-inspection.',
    [auto('craft', '검사 항목에 모자란 장비 2점을 갖춘다', 'Make the two items the checklist is short of', { target: 2 }),
      man('custom', '선박 안전 검사 통과', 'Pass the vessel safety inspection')]],
  ['M4-05', 4, 84, 13750, 'oh_gayun', YEO, '밤바다 갈치', 'Hairtail at Night',
    '야간 원정 · 집어등. 갈치.',
    'A night expedition under lights. Hairtail.',
    [fish('hairtail', '갈치 자가어획 (초여름~가을 야간)', 'Catch a hairtail (summer–autumn night)', { season: ['summer', 'autumn'] })],
    { journalPage: 9 }],
  ['M4-06', 4, 87, 15050, 'coop', GEO, '첫 손님', 'First Passenger',
    '낚시어선업 신고 완료 · 승선 명부 · 안전교육 · 멀미 대응. 손님이 드러눕는다.',
    'Angling-boat business registered. Passenger list, safety briefing, seasickness. The guest keels over.',
    [fish(undefined, '손님 앞에서 2마리', 'Land two in front of the guest', { target: 2 }),
      auto('sashimi', '배 위에서 회 1접시', 'One plate sliced on deck'),
      man('boatTrip', '첫 손님 승선 출조', 'First paid passenger trip')],
    { rewards: { licenses: ['angling_boat_biz'], items: [{ id: 'qr_reel_captain', qty: 1, bound: true }] } }],
  ['M4-07', 4, 90, 16300, 'song_gibaek', TAE, '서해로', 'To the West Sea',
    '동해와 정반대의 바다. 조수간만 대차 · 갯벌 보행.',
    'The opposite of the East Sea. Big tidal range, walking the mudflats.',
    [auto('visit', '태안에 도착한다', 'Arrive in Taean', { placeKey: 'region:chungnam_taean' }),
      auto('gather', '갯벌 채집 3개체', 'Gather three creatures on the flats', { target: 3 })]],
  ['M4-08', 4, 93, 17550, 'tak_saebyeok', TAE, '만리포 서프', 'Mallipo Surf',
    '서프 루어 · 포말대 야간 보너스. 농어.',
    'Surf lure, surf-zone night bonus. Sea bass.',
    [fish('sea_bass', '농어 자가어획 (봄~여름 포말대 야간)', 'Catch a sea bass (spring–summer surf-zone night)', { season: ['spring', 'summer'] })],
    { journalPage: 11, teaches: ['surf'], rewards: { skillUnlocks: ['fish_surf'], items: [{ id: 'qr_rod_surf', qty: 1, bound: true }] } }],
  ['M4-09', 4, 96, 18850, 'ma_gamgi', TAE, '갑오징어', 'Cuttlefish',
    '에깅 계열 개방. 가을 주간 갑오징어.',
    'Egging unlocked. Autumn daytime cuttlefish.',
    [fish('cuttlefish', '갑오징어 자가어획 (가을 주간)', 'Catch a cuttlefish (autumn daytime)', { season: AU })],
    { journalPage: 10, teaches: ['egging'], rewards: { skillUnlocks: ['fish_egi'], shopUnlocks: ['market_egi_pro'] } }],
  // 137차 — 회귀 고리 ②. Ch1의 두 노인이 Ch4에 손님으로 돌아온다.
  ['M4-11', 4, 97, 14700, 'kang_ducheol', SOK, '속초의 손님', 'Passengers from Sokcho',
    '낚시어선업 신고를 마치고 배를 속초까지 몰고 온다. 첫 정식 손님은 강두철 조합장과 탁만수 — 채비 못 묶는 척하던 노인과, 죽간을 깎아 준 노인이 나란히 앉는다.',
    'Licensed at last, you bring the boat all the way up to Sokcho. Your first proper passengers are Kang Du-cheol and Tak Man-su — the old man who pretended he could not tie a rig, and the one who carved your rod, sitting side by side.',
    [auto('visit', '배를 속초까지 몰고 간다', 'Sail the boat up to Sokcho', { placeKey: 'region:gangwon_sokcho' }),
      man('boatTrip', '두 노인을 태우고 속초 앞바다 출조', 'Take the two old men out off Sokcho')],
    { teaches: ['returnTrip', 'guestTrip'] }],
  ['M4-10', 4, 99, 23150, 'hyeonsu', TAE, '제주 항로', 'The Jeju Route',
    '장거리 항해 준비 · 연료 · 기상. 도현수가 처음 배를 타러 온다.',
    'Preparing a long voyage — fuel, weather. Hyeon-su comes aboard for the first time.',
    [auto('craft', '장거리 항해 보급 3점을 만든다', 'Make three items of long-voyage stores', { target: 3 }),
      talk('hyeonsu', '도현수와 함께 출항 준비', 'Prepare to sail with Hyeon-su')],
    { unlocks: ['region:jeju'] }],

  // ─────────────────────────────────────────────
  // 제4부 「손님」 — Ch5 제주 · 9퀘 · 230,850
  // ─────────────────────────────────────────────
  ['M5-01', 5, 100, 15050, 'coop', JEJ, '운진항', 'Unjin Port',
    '타지 입항 절차 · 항비. 제주 방언 · 지역 규칙.',
    'Entering a foreign port — fees, dialect, local rules.',
    [auto('visit', '제주에 도착한다', 'Arrive in Jeju', { placeKey: 'region:jeju' })],
    { rewards: { coins: 3000000 } }],
  ['M5-02', 5, 103, 17550, 'baram', JEJ, '불턱', 'The Bulteok',
    '남의 바다에 들어갈 때의 예의. 마을어업권 실전 · 잠수 채집.',
    'Manners for entering someone else\'s sea. Village fishery for real, dive gathering.',
    [auto('gather', '마을어업권 밖에서 3개체 채집', 'Gather three creatures outside the village fishery', { target: 3 })],
    { teaches: ['villageFishery'], reputation: { sea: 1 } }],
  ['M5-03', 5, 107, 20050, 'oh_serin', JEJ, '도두항 한치', 'Swordtip Squid at Dodu',
    '야간 집어 · 한치 3마리.',
    'Night lights, three swordtip squid.',
    [fish('swordtip_squid', '한치 3마리 자가어획 (여름 야간)', 'Catch three swordtip squid (summer night)', { target: 3, season: SU })],
    { journalPage: 12 }],
  ['M5-04', 5, 111, 22600, 'coop', JEJ, '해양관광업 등록', 'Marine Tourism Registration',
    '손님을 받는 쪽이 된다. 가이드 영업 루프.',
    'Now you are the one taking guests. The guide loop.',
    [fish('swordtip_squid', '손님에게 보여 줄 자리를 먼저 확인한다 — 한치 2마리', 'Check the spot you will show guests — two swordtip squid', { target: 2 }),
      man('custom', '해양관광업 등록 + 안전교육', 'Register and take the safety course')],
    { teaches: ['guideBusiness'], rewards: { licenses: ['marine_tourism'], items: [{ id: 'qr_bag_guide', qty: 1, bound: true }] } }],
  ['M5-05', 5, 115, 25100, 'yu_ria', JEJ, '낚시공원 설명회', 'The Fishing Park Briefing',
    '찬반 양측 취재. 두 입장 모두 타당하게.',
    'Interview both sides. Both are right.',
    [auto('gather', '공원 예정지 조간대를 직접 훑는다 3회', 'Work the proposed park\'s tideline yourself, three times', { target: 3 }),
      talk('yu_ria', '찬성 측 취재', 'Interview the "for" side'), talk('coop', '반대 측 취재', 'Interview the "against" side')]],
  ['M5-06', 5, 119, 27600, 'namgung_hyeon', JEJ, '대회 예선', 'Tournament Qualifier',
    '참가비 · 순위 상금 · 계측 규정.',
    'Entry fee, prize ladder, measuring rules.',
    [fish(undefined, '예선 계측 어획 3마리', 'Three measured fish for the qualifier', { target: 3 })],
    { teaches: ['tournament'] }],
  ['M5-07', 5, 122, 30100, 'mara', JEJ, '서귀포 에깅', 'Seogwipo Egging',
    '무늬오징어 에깅 심화.',
    'Advanced egging for bigfin reef squid.',
    [fish('squid', '무늬오징어 자가어획 (가을 야간 얕은 곳)', 'Catch a bigfin reef squid (autumn night shallows)', { season: AU })],
    { journalPage: 14 }],
  ['M5-08', 5, 126, 32600, 'namgung_hyeon', JEJ, '결선과 전화 한 통', 'The Final and a Phone Call',
    '대회 결선 · 방어 대물 80cm 이상. 결선 중 정옥선이 쓰러졌다는 연락.',
    'The final — a yellowtail over 80 cm. Mid-final, the call: Ok-seon has collapsed.',
    [fish('yellowtail', '방어 80cm+ 자가어획 (겨울)', 'Catch a yellowtail 80 cm+ (winter)', { minCm: 80, season: W })],
    { journalPage: 13, rewards: { items: [{ id: 'qr_rod_tournament', qty: 1, bound: true }, { id: 'qr_reel_tournament', qty: 1, bound: true }] } }],
  ['M5-09', 5, 129, 40200, 'coop', JEJ, '총회 표결', 'The Vote',
    '낚시공원 안건 표결 — 누적 평판 · 참여율 반영. 도현수가 처음 같은 편에 선다.',
    'The fishing-park vote — reputation and participation count. Hyeon-su takes your side for the first time.',
    [auto('sell', '표결 전까지 참여 실적 — 위판 5건', 'Your participation record before the vote — five consigned lots', { target: 5 }),
      talk('coop', '총회 표결에 참석', 'Attend the vote')],
    { unlocks: ['region:ulleungdo', 'region:incheon', 'parkVote'] }],

  // ─────────────────────────────────────────────
  // 제5부 「먼 항로」 — Ch6 울릉·인천 · 8퀘 · 326,800
  // ─────────────────────────────────────────────
  ['M6-01', 6, 130, 23750, 'oh_sera', ULL, '막배', 'The Last Ferry',
    '돌아갈 수 없는 밤. 여객선 결항 확률 · 섬 체류 생존.',
    'A night you cannot go back. Ferry cancellations, surviving on the island.',
    [auto('visit', '울릉도에 도착한다', 'Arrive at Ulleungdo', { placeKey: 'region:ulleungdo' }),
      man('survive', '결항 하룻밤 체류', 'Stay one cancelled night')],
    { teaches: ['ferry'] }],
  ['M6-02', 6, 134, 28400, 'yeon_taeo', ULL, '부시리', 'Amberjack',
    '파핑 · 대형 청물.',
    'Popping for big pelagics.',
    [fish('amberjack', '부시리 자가어획 (여름~가을)', 'Catch an amberjack (summer–autumn)', { season: ['summer', 'autumn'] })],
    { journalPage: 16 }],
  ['M6-03', 6, 138, 33000, 'seok_daeyang', ULL, '등대', 'The Lighthouse',
    '등대 근무자 교류 · 기상 관측. 석대양 노인이 고진태 선장을 기억한다.',
    'Keeping company with the lighthouse keeper, watching the weather. Old Seok remembers Captain Go.',
    [fish('amberjack', '등대 아래에서 부시리 1마리', 'One amberjack below the lighthouse'),
      talk('seok_daeyang', '등대지기와 대화', 'Talk with the lighthouse keeper')],
    { rewards: { items: [{ id: 'qr_headlamp_keeper', qty: 1, bound: true }], coins: 5000000 } }],
  ['M6-04', 6, 142, 37650, 'dan_cheolho', INC, '연안부두', 'Yeonan Pier',
    '인천 개방 · 유통 구조 · 원산지 표기. 우럭 30cm 이상.',
    'Incheon opens — distribution, origin labelling. A rockfish over 30 cm.',
    [fish('black_rockfish', '우럭(조피볼락) 30cm+ 자가어획 (가을 야간)', 'Catch a black rockfish 30 cm+ (autumn night)', { minCm: 30, season: AU })],
    { journalPage: 15 }],
  ['M6-05', 6, 146, 42250, 'okseon', SOK, '병실', 'The Ward',
    '병원 시스템 · 간병 일정이 출조를 압박. 정옥선이 조행록 마지막 권을 건넨다.',
    'Hospital visits squeeze your trips. Ok-seon hands you the last volume of the log.',
    [auto('custom', '병원비 — 만복상회 얼음 나르기 3회', 'Hospital bills — haul ice for Manbok Store three times', { placeKey: 'job:ice_haul', target: 3 }),
      talk('okseon', '병실의 정옥선을 찾아간다', 'Visit Ok-seon in the ward')],
    { unlocks: ['journalInherited'] }],
  ['M6-06', 6, 150, 46850, 'okseon', SOK, '좌판을 맡다', 'Minding the Stall',
    '그녀의 자리에 처음 앉는다. 좌판 운영 루프(재고 · 손님 · 가격).',
    'You sit in her seat for the first time. Running the stall — stock, customers, prices.',
    [auto('sell', '좌판에 낼 물건 — 위판 3건', 'Goods for the stall — three consigned lots', { target: 3 }),
      man('custom', '만복상회 좌판 3일 운영', 'Run Manbok Store for three days', { target: 3 })],
    { teaches: ['stallOps'] }],
  // 137차 — 회귀 고리 ③. Ch3의 고래마루가 문을 닫는다.
  ['M6-09', 6, 152, 40850, 'go_manseok', ULS, '고래마루의 마지막 손님', 'Goraemaru\'s Last Fare',
    '고만석이 배를 내놓기로 했다. 마지막 출항의 손님으로 나를 부른다. "처음 탔을 때 네가 어디에 앉았는지 기억하냐." 고해나가 조타실에 선다.',
    'Go Man-seok is selling the boat, and he books you as the fare for her last trip. "Do you remember where you sat the first time?" Hae-na takes the wheel.',
    [auto('visit', '울산 방어진으로 돌아간다', 'Return to Bangeojin, Ulsan', { placeKey: 'region:ulsan' }),
      man('boatTrip', '고래마루 마지막 출항에 승선', 'Ride Goraemaru\'s final trip')],
    { teaches: ['returnTrip'] }],
  ['M6-07', 6, 155, 51500, 'coop', SOK, '항해 계획 승인', 'Voyage Plan Approval',
    '기상 · 정비 · 비상계획 서류. 마지막 자격.',
    'Weather, maintenance, contingency paperwork. The last qualification.',
    [auto('craft', '비상 보급 3점을 갖춘다', 'Put together three items of emergency stores', { target: 3 }),
      man('custom', '원거리 항해 계획 승인', 'Get the long-range voyage plan approved')],
    { teaches: ['voyagePlan'] }],
  ['M6-08', 6, 158, 63400, 'coop', SOK, '조사 동행 허가', 'Survey Escort Permit',
    '3중 게이트(Lv160 · 해양관광업 · Ch6 완료). 독도 학술조사단 동행 승인.',
    'Triple gate — Lv160, marine tourism, Ch6 done. Approved to join the Dokdo survey.',
    [auto('reachLevel', '레벨 160 도달', 'Reach level 160', { target: 160 })],
    { unlocks: ['region:dokdo'], rewards: { items: [{ id: 'qr_bag_voyage', qty: 1, bound: true }] } }],

  // ─────────────────────────────────────────────
  // 제5부 「조행록」 — Ch7 독도 · 8퀘 · 602,800
  // ─────────────────────────────────────────────
  ['M7-01', 7, 160, 43850, 'seok_daeyang', DOK, '동도 접안', 'Landing at Dongdo',
    '가장 먼 바다. 기상 게이트 · 체류 시간 제한.',
    'The farthest sea. Weather gate, limited time ashore.',
    [auto('visit', '독도에 도착한다', 'Arrive at Dokdo', { placeKey: 'region:dokdo' })]],
  ['M7-02', 7, 165, 52350, 'coop', DOK, '조사선', 'The Survey Boat',
    '잡는 게 목적이 아닌 첫 낚시. 표본 계측 → 즉시 방류.',
    'The first fishing that isn\'t about keeping. Measure, then release.',
    [auto('release', '표본 3마리 계측 후 방류', 'Measure and release three specimens', { target: 3 })],
    { reputation: { sea: 2 } }],
  ['M7-03', 7, 170, 60900, 'seok_dokgu', DOK, '열일곱 번째 장', 'The Seventeenth Page',
    '조행록 완성 판정. 돌돔 계측 후 방류.',
    'The log is judged complete. Measure and release a striped beakperch.',
    [fish('stone_beakperch', '돌돔 자가어획 후 즉시 방류 (여름~가을)', 'Catch and release a striped beakperch (summer–autumn)', { season: ['summer', 'autumn'] })],
    { journalPage: 17, teaches: ['journalComplete'], rewards: { coins: 12000000 } }],
  ['M7-04', 7, 176, 69400, 'okseon', SOK, '사진 속 천막', 'The Tent in the Photo',
    '네 살 사진의 좌판이 만복상회였다. 회상 시퀀스.',
    'The stall in the photo from age four was Manbok Store. A memory.',
    [fish('frog_flounder', '네 살 때와 같은 자리에서 도다리 1마리', 'One flounder from the same spot as when you were four'),
      talk('okseon', '정옥선과 사진을 본다', 'Look at the photo with Ok-seon')]],
  ['M7-05', 7, 182, 77950, 'coop', SOK, '2층', 'The Second Floor',
    '공동작업장 복구(자재 · 인력 · 기부).',
    'Rebuilding the workshop — materials, hands, donations.',
    [auto('earn', '재화 30,000,000원 보유 (복구 기금)', 'Hold 30,000,000 won (rebuild fund)', { target: 30_000_000 })]],
  ['M7-06', 7, 188, 86450, 'okseon', SOK, '재개관', 'Reopening',
    '자료관 겸 낚시방 개관. 정옥선이 요양을 마치고 휠체어로 참석해 테이프를 자른다.',
    'The archive and fishing room opens. Ok-seon, back from convalescence, cuts the ribbon from her wheelchair.',
    [auto('sashimi', '개관식 상에 올릴 회 3접시', 'Three plates for the opening table', { target: 3 }),
      talk('okseon', '재개관식에 참석', 'Attend the reopening')]],
  ['M7-07', 7, 194, 95000, 'tak_saebyeok', DOK, '마지막 캐스팅', 'The Last Cast',
    '전용 포인트(조사선 해역) 영구 해제. N02-4에서 되살린 유품 릴대를 던진다.',
    'The survey waters open for good. You cast the rod that Sae-byeok rebuilt.',
    [fish(undefined, '독도 전용 포인트에서 1마리', 'One fish at the Dokdo point')],
    { rewards: { items: [{ id: 'qr_rod_final', qty: 1, bound: true }, { id: 'qr_reel_final', qty: 1, bound: true }] } }],
  ['M7-08', 7, 199, 116900, '', SOK, '실습생', 'Trainee',
    '에필로그 · 수미상관. 배낭 하나 멘 스물두 살에게. "울 거면 얼음부터 나르고 울어."',
    'Epilogue, full circle. To a twenty-two-year-old with one backpack: "If you\'re going to cry, haul the ice first."',
    [auto('reachLevel', '레벨 199 도달', 'Reach level 199', { target: 199 })]],
]);

// ─────────────────────────────────────────────
// 서브 — NPC 17아크 · 55퀘 · 563,550
// ─────────────────────────────────────────────
type SubRow = [id: string, ch: 1|2|3|4|5|6|7, lv: number, xp: number, giver: string, region: string,
  titleKo: string, titleEn: string, descKo: string, descEn: string, objectives: StoryObjective[], extra?: Partial<StoryQuestDef>];

function subRows(arcId: string, rows: SubRow[]): StoryQuestDef[] {
  return rows.map((r, i) => {
    const [id, chapter, minLevel, xp, giver, region, titleKo, titleEn, descKo, descEn, objectives, extra] = r;
    return { id, kind: 'sub', part: PART_OF[chapter], chapter, arcId, titleKo, titleEn, descKo, descEn, minLevel, xp, giver, region,
      prereq: i > 0 ? [rows[i - 1][0]] : [], objectives, ...extra } as StoryQuestDef;
  });
}

const SUB: StoryQuestDef[] = [
  ...subRows('N01', [
    ['N01-1', 1, 8, 350, 'baram', SOK, '리어카', 'The Cart',
      '좌판 할머니가 손주 생일상 도다리를 못 구한다. 원투 · 체장 실습 + 리어카 도면.',
      'A stall grandmother can\'t find a flounder for her grandchild\'s birthday. Surf casting, measuring, and a cart blueprint.',
      [fish('frog_flounder', '도다리 1마리 자가어획', 'Catch one frog flounder'), talk('baram', '바람에게 리어카 도면을 받는다', 'Receive the cart blueprint from Baram')]],
    ['N01-2', 2, 28, 1450, 'baram', BUS, '다리 밑', 'Under the Bridge',
      '가출 중학생과 원양 나간 아버지. 전갱이 한 마리로 통화 버튼을 누르게 한다.',
      'A runaway and a father at sea. One horse mackerel makes him press "call".',
      [fish('horse_mackerel', '전갱이 1마리', 'One horse mackerel'), talk('baram', '다리 밑 소년을 만난다', 'Meet the boy under the bridge')]],
    ['N01-3', 3, 55, 3250, 'baram', POH, '덕장', 'The Racks',
      '청어가 안 들어와 과메기 명맥이 끊길 위기. "바다가 바뀌면 사람이 바뀌어야지."',
      'No herring — the gwamegi tradition is at risk. "When the sea changes, people must too."',
      [auto('craft', '덕장에 걸 건조품 1점을 만든다', 'Make one thing to hang on the racks'),
        talk('baram', '덕장 주인과 대화', 'Talk with the rack owner')]],
    ['N01-4', 4, 82, 5600, 'baram', GEO, '절벽', 'The Cliff',
      '갯바위 사고 후 낚시를 끊은 남자와 해금강 동행.',
      'A man who quit after a rock accident — you go to Haegeumgang together.',
      [fish('largescale_blackfish', '벵에돔 자가어획 (초여름 갯바위)', 'Catch a largescale blackfish (early summer rocks)', { season: SU })],
      { journalPage: 8 }],
    ['N01-5', 5, 112, 8350, 'baram', JEJ, '해녀의 딸', 'The Diver\'s Daughter',
      '물질을 그만두려는 딸과 어머니. 해루질과 물질의 경계.',
      'A daughter who wants to quit diving, and her mother. Where gathering ends and diving begins.',
      [auto('gather', '제주 해루질 3개체', 'Gather three creatures on Jeju', { target: 3 })]],
    ['N01-6', 6, 140, 16150, 'baram', ULL, '막배를 놓친 남자', 'The Man Who Missed the Ferry',
      '결항으로 발 묶인 출장객과 섬에서 하룻밤. "나는 이제 짐이 적어도 돼." 마운틴 백팩.',
      'Stranded with a businessman for a night. "I don\'t need much baggage anymore." The mountain backpack.',
      [fish(undefined, '섬에서 하룻밤 — 2마리', 'A night on the island — two fish', { target: 2 }),
        talk('baram', '섬에서의 하룻밤', 'A night on the island')],
      { rewards: { items: [{ id: 'inv_bag_mountain', qty: 1 }] } }],
    ['N01-7', 7, 168, 34200, 'baram', SOK, '이름', 'The Name',
      '본명 공개. 30년 전 배와 사람을 잃은 선장이었다. 재개관식에 처음 앉는다.',
      'His real name. A captain who lost his boat and crew thirty years ago. He sits down at the reopening.',
      [fish(undefined, '그가 서른 해 전 서 있던 자리에서 1마리', 'One fish where he stood thirty years ago'),
        talk('baram', '바람의 이름을 듣는다', 'Hear Baram\'s name')]],
  ]),
  ...subRows('N02', [
    ['N02-1', 1, 11, 320, 'tak_mansu', SOK, '부러진 대', 'The Broken Rod',
      '유품 릴대 점검 의뢰 → 새벽과 학공치 내기.',
      'A check-up for the heirloom rod → a halfbeak bet with Sae-byeok.',
      [fish('halfbeak', '학꽁치 1마리', 'One halfbeak'), talk('tak_saebyeok', '새벽과 내기', 'Bet with Sae-byeok')]],
    ['N02-2', 4, 78, 5600, 'tak_mansu', TAE, '왕대를 찾아서', 'Looking for Wangdae Bamboo',
      '가출한 새벽을 태안까지 쫓아간다. 왕대 채집.',
      'You chase a runaway Sae-byeok to Taean. Gathering giant bamboo.',
      [talk('tak_saebyeok', '태안에서 새벽을 찾는다', 'Find Sae-byeok in Taean'), fish('sea_bass', '농어 1마리', 'One sea bass')],
      { journalPage: 11 }],
    ['N02-3', 5, 120, 11650, 'tak_saebyeok', JEJ, '돌무덤의 주인', 'Master of the Stone Mound',
      '서귀포 심해 대물 도전. 드랙 제어 한계 시험. (돗돔 미등록 — 대구로 대체)',
      'A deep-water giant off Seogwipo. The limit of drag control. (Substitute: Pacific cod.)',
      [fish('pacific_cod', '대구 80cm+ 자가어획', 'Catch a Pacific cod 80 cm+', { minCm: 80 })]],
    ['N02-4', 7, 175, 40200, 'tak_saebyeok', SOK, '마지막 죽간', 'The Last Bamboo Rod',
      '노인이 손을 놓고 새벽이 마무리한다. 유품 릴대 부활 → 7-7에서 사용.',
      'The old man lets go; Sae-byeok finishes. The heirloom rod lives again — for 7-7.',
      [auto('craft', '새벽과 함께 대를 손본다 2회', 'Work on the rod with Sae-byeok, twice', { target: 2 }),
        talk('tak_saebyeok', '되살린 릴대를 받는다', 'Receive the rebuilt rod')],
      { unlocks: ['rodRevived'] }],
  ]),
  ...subRows('N03', [
    ['N03-1', 1, 5, 350, 'kang_ducheol', SOK, '선생님', 'Teacher',
      '엉킨 채비를 풀어주고 첫 입질을 함께 본다.',
      'You untangle his rig and watch his first bite together.',
      [talk('kang_ducheol', '채비를 풀어 준다', 'Untangle his rig'), fish(undefined, '함께 1마리', 'One fish together')]],
    ['N03-2', 2, 34, 1450, 'kang_ducheol', BUS, '조합장님', 'Mr. President',
      '부산 교육장에서 재회 · 정체 발각. 계속 가르치기/거리 두기(호감도만 분기).',
      'Reunion at the Busan course — the truth comes out. Keep teaching, or keep your distance.',
      [fish('horse_mackerel', '교육장 앞바다에서 전갱이 2마리', 'Two horse mackerel off the course', { target: 2 }),
        talk('kang_ducheol', '교육장에서 재회', 'Reunion at the course')]],
    ['N03-3', 5, 117, 9150, 'kang_ducheol', JEJ, '도장', 'The Seal',
      '총회 전, 표결에 개입하지 않겠다고 선언. "내 선생이 알아서 하겠지."',
      'Before the vote he declares he won\'t interfere. "My teacher will handle it."',
      [auto('sell', '표결 전 실적 — 위판 3건', 'Your record before the vote — three consigned lots', { target: 3 }),
        talk('kang_ducheol', '표결 전 대화', 'Talk before the vote')]],
    ['N03-4', 7, 180, 40200, 'kang_ducheol', SOK, '스승의 날', 'Teacher\'s Day',
      '은퇴하며 조합원 명부 1번을 비워 둔다. 2층 복구 자재 지원.',
      'He retires, leaving line one of the member roll empty. Materials for the second floor.',
      [auto('craft', '2층 복구 자재로 3점을 만든다', 'Make three things from the second-floor materials', { target: 3 }),
        talk('kang_ducheol', '은퇴 인사', 'The farewell')]],
  ]),
  ...subRows('N04', [
    ['N04-1', 1, 3, 280, 'bae_nuri', SOK, '입부 권유', 'Join the Club',
      '사비키 전어·학공치 + 방파제 즉석 조리. 1-7 요리와 교차.',
      'Sabiki halfbeak and an on-the-spot breakwater meal.',
      [fish('halfbeak', '학꽁치 2마리', 'Two halfbeak', { target: 2 }), talk('bae_nuri', '방파제부 입부', 'Join the breakwater club')]],
    ['N04-2', 1, 15, 450, 'bae_nuri', SOK, '부원을 낚아라', 'Reel In a Member',
      '축제 부스 "사람 낚기" 소동 — 진짜 목표는 진주의 입부. 그녀의 원투 포인트를 따라간다.',
      'The festival "fish for members" stunt — the real target is Jin-ju. You follow her surf-casting spot.',
      [fish('sandfish', '도루묵 자가어획 (겨울 새벽 방파제)', 'Catch a sandfish (winter dawn, breakwater)', { season: W }),
        talk('mo_jinju', '진주를 입부시킨다', 'Get Jin-ju to join')],
      { journalPage: 1 }],
  ]),
  ...subRows('N05', [
    ['N05-1', 2, 25, 1150, 'seo_harin', BUS, '낚아서 먹고 싶어요', 'I Want to Catch It and Eat It',
      '하린의 첫 선상, 기범의 조용한 교정. 선상 매너.',
      'Ha-rin\'s first boat trip, Gi-beom\'s quiet corrections. Boat manners.',
      [fish(undefined, '하린이 먹을 1마리', 'One fish for Ha-rin to eat'),
        auto('butcher', '그 자리에서 손질해 준다', 'Butcher it there for her'),
        talk('na_gibeom', '기범에게 선상 매너를 듣는다', 'Learn boat manners from Gi-beom')]],
    ['N05-2', 2, 40, 1450, 'seo_harin', BUS, '조회수', 'Views',
      '하린 영상에 주인공이 찍혀 논란. 촬영 동의 · 초상권.',
      'You end up in Ha-rin\'s video. Consent and image rights.',
      [fish('horse_mackerel', '전갱이 2마리 (야간 루어)', 'Two horse mackerel (night lure)', { target: 2 }), talk('seo_harin', '촬영 동의 이야기', 'Talk about filming consent')],
      { journalPage: 3 }],
    ['N05-3', 5, 124, 8350, 'na_gibeom', JEJ, '퇴사합니다', 'I Quit',
      '기범이 낚시로 살겠다고 한다. 말릴 수도, 도울 수도.',
      'Gi-beom says he\'ll live by fishing. You could stop him — or help.',
      [fish('squid', '기범과 나란히 무늬오징어 2마리', 'Two bigfin squid beside Gi-beom', { target: 2 }),
        talk('na_gibeom', '기범의 결심을 듣는다', 'Hear Gi-beom out')]],
    ['N05-4', 6, 144, 17750, 'seo_harin', INC, '두 번째 겨울', 'Second Winter',
      '인천 발령된 하린과 연안부두에서 재회.',
      'Ha-rin, transferred to Incheon — reunion at Yeonan Pier.',
      [fish('black_rockfish', '우럭 1마리', 'One black rockfish'), talk('seo_harin', '연안부두 재회', 'Reunion at the pier')],
      { journalPage: 15 }],
    ['N05-5', 7, 186, 43200, 'na_gibeom', SOK, '손님 두 명', 'Two Guests',
      '재개관식 첫 예약이 두 사람. 처음으로 돈 받고 태우는 친구.',
      'The first booking at the reopening is the two of them. Friends who pay to come aboard.',
      [fish(undefined, '손님 두 사람 몫 2마리', 'Two fish for two guests', { target: 2 }),
        auto('sashimi', '두 사람에게 회를 뜬다', 'Slice for the two of them'),
        talk('seo_harin', '첫 예약 손님을 맞는다', 'Welcome your first booked guests')]],
  ]),
  ...subRows('N06', [
    ['N06-1', 2, 21, 1150, 'go_hosu', BUS, '농구부인 줄 알았는데', 'I Thought It Was Basketball',
      '가입 착각 소동 + 첫 농어 루어. 2-5 루어 개방과 교차.',
      'A mix-up joining, and a first sea bass on lure.',
      [fish('sea_bass', '농어 1마리 (루어)', 'One sea bass (lure)', { method: 'rod' })]],
    ['N06-2', 2, 31, 1450, 'mo_taejo', BUS, '불순한 동기', 'Impure Motives',
      '하늘을 진지한 앵글러로. 상황별 루어 선택 실측.',
      'Making Ha-neul a real angler. Lure selection by situation.',
      [fish(undefined, '루어로 3마리', 'Three fish on lure', { target: 3 })]],
    ['N06-3', 2, 43, 2050, 'yeo_gangsan', BUS, '먹보', 'The Glutton',
      '태풍 뒤 탁수, 괴물 농어 3인 협공. 태클 베스트 · 주간 의뢰 \'동아리 대결\'.',
      'Murky water after the typhoon — three of you against a monster sea bass. The tackle vest.',
      [fish('sea_bass', '농어 60cm+', 'A sea bass 60 cm+', { minCm: 60 })],
      { journalPage: 2, rewards: { items: [{ id: 'inv_bag_tackle_vest', qty: 1 }] } }],
  ]),
  ...subRows('N07', [
    ['N07-1', 2, 37, 1450, 'jim_kang', BUS, '공방 터', 'The Workshop Site',
      '영도 폐공방 도면 발견 → 시험 장소인 속초로 되돌아가 대결.',
      'A blueprint in the abandoned Yeongdo workshop → back to Sokcho for a duel.',
      [fish(undefined, '짐 강과의 대결 — 3마리', 'The duel with Jim Kang — three fish', { target: 3 }),
        talk('jim_kang', '짐 강과 첫 대결', 'First duel with Jim Kang')]],
    ['N07-2', 3, 57, 3250, 'jim_kang', POH, '두 번째', 'The Second',
      '포항 앞바다 지그. 지깅 숙련 실측.',
      'Jigs off Pohang. Measuring your jigging.',
      [fish('yellowtail', '방어 1마리 (지깅)', 'One yellowtail (jigging)')]],
    ['N07-3', 4, 93, 5600, 'jim_kang', TAE, '세 번째', 'The Third',
      '만리포 서프 미노우.',
      'A minnow in the Mallipo surf.',
      [fish('sea_bass', '농어 1마리 (서프)', 'One sea bass (surf)')],
      { journalPage: 11 }],
    ['N07-4', 5, 125, 11650, 'jim_kang', JEJ, '네 번째', 'The Fourth',
      '제주 에기. 4점 완성 후 전부 주인공에게 넘긴다 — "박제하려고 찾은 게 아니야."',
      'The Jeju egi. With all four found, he hands them over — "I didn\'t collect them to mount them."',
      [fish('squid', '무늬오징어 1마리 (에기)', 'One bigfin reef squid (egi)'), talk('jim_kang', '유작 넷을 받는다', 'Receive the four lures')]],
  ]),
  ...subRows('N08', [
    ['N08-1', 3, 47, 2600, 'go_manseok', ULS, '첫 승선', 'First Boarding',
      '사관 배치 · 선상 채비 · 선상 물회. 반복 의뢰 \'승객 사연\' 개방.',
      'Seat allocation, boat rigs, mulhoe on deck. Passenger stories unlocked.',
      [fish(undefined, '선상 채비로 2마리', 'Two fish on a boat rig', { target: 2 }),
        man('boatTrip', '고래마루 승선', 'Board the Goraemaru')]],
    ['N08-2', 3, 62, 4550, 'go_haena', ULS, '해나의 칼', 'Hae-na\'s Knife',
      '요리학교에 가려는 딸과 반대하는 아버지. 겨울 방어 한 마리로 차려진 식탁.',
      'A daughter bound for culinary school, a father against it. A table set with one winter yellowtail.',
      [fish('yellowtail', '방어 1마리 (겨울)', 'One yellowtail (winter)', { season: W }), auto('sashimi', '회뜨기 1회', 'Slice sashimi once')],
      { journalPage: 5 }],
  ]),
  ...subRows('N09', [
    ['N09-1', 3, 50, 2600, 'han_bom', POH, '호미곶의 털바늘', 'Fly at Homigot',
      '갯바위에서 미끄러질 뻔한 봄을 붙잡으며 첫 만남.',
      'You catch Bom before she slips on the rocks — first meeting.',
      [fish(undefined, '봄과 함께 갯바위에서 1마리', 'One fish from the rocks with Bom', { spotKind: 'shore' }),
        talk('han_bom', '봄을 붙잡는다', 'Catch Bom')]],
    ['N09-2', 3, 59, 3250, 'han_bom', POH, '칼을 쥐면', 'Holding the Knife',
      '수연이 잡고 봄이 즉석 조리. 요리 품질 판정 심화.',
      'Su-yeon catches, Bom cooks. Cooking quality, deeper.',
      [fish(undefined, '2마리 낚아 손질', 'Catch and butcher two fish', { target: 2 }), auto('butcher', '손질 2회', 'Butcher twice', { target: 2 })]],
    ['N09-3', 3, 68, 4450, 'lee_suyeon', POH, '아빠의 패턴', 'Dad\'s Pattern',
      '털바늘 패턴 복원 → 셋의 첫 식탁. 주인공이 부모 이야기를 꺼낸다.',
      'Restoring her father\'s fly pattern → the three of you at one table. You speak of your parents.',
      [fish('red_seabream', '참돔 1마리', 'One red seabream'), talk('lee_suyeon', '첫 식탁', 'The first table')],
      { journalPage: 6 }],
  ]),
  ...subRows('N10', [
    ['N10-1', 3, 65, 3250, 'namgung_hyeon', POH, '야간 근무', 'Night Shift',
      '창고 재고 정리 아르바이트. 새벽에 그의 캐스팅을 우연히 본다.',
      'A warehouse stock job. At dawn you happen to see him cast.',
      [fish(undefined, '새벽에 그를 따라 1마리', 'One fish at dawn, following his cast'),
        talk('namgung_hyeon', '창고 야간 근무', 'Work the night shift')],
      { rewards: { coins: 80000 } }],
    ['N10-2', 5, 128, 8350, 'namgung_hyeon', JEJ, '계측 이의신청', 'The Measurement Appeal',
      '대회 계측 분쟁에서 규정대로 증언. 편들지 않는 태도.',
      'A measuring dispute — you testify by the rules, taking no side.',
      [auto('release', '규정대로 계측하고 방생한다 2회', 'Measure by the rules and release, twice', { target: 2 }),
        talk('namgung_hyeon', '규정대로 증언', 'Testify by the rules')],
      { journalPage: 13 }],
    ['N10-3', 7, 172, 37200, 'namgung_hyeon', SOK, '심판석', 'The Judge\'s Seat',
      '재개관 기념 대회 심판. 20년 만에 대회장에 선다.',
      'Judge at the reopening tournament. His first tournament in twenty years.',
      [fish(undefined, '대회 시범 — 3마리', 'The demonstration round — three fish', { target: 3 }),
        talk('namgung_hyeon', '심판을 부탁한다', 'Ask him to judge')]],
  ]),
  ...subRows('N11', [
    ['N11-1', 4, 72, 4500, 'chae_geumja', GEO, '요리 못 하는 선장', 'The Captain Who Can\'t Cook',
      '선상식을 대신 만들고 항로 판단을 배운다.',
      'You cook the boat meal and learn to read a course.',
      [fish('flatfish', '광어 1마리', 'One flatfish'), talk('chae_geumja', '항로 판단 수업', 'A lesson in navigation')],
      { journalPage: 7 }],
    ['N11-2', 4, 85, 5600, 'chae_pado', GEO, '파도의 첫 월급', 'Pa-do\'s First Pay',
      '날린 경매 물량을 새벽 긴급 조업으로 메운다. 드라이백.',
      'Making up a lost auction lot with a dawn emergency run. The dry bag.',
      [auto('trap', '통발 2회 수거', 'Harvest two traps', { target: 2 })],
      { rewards: { items: [{ id: 'inv_bag_dry', qty: 1 }] } }],
    ['N11-3', 4, 95, 7900, 'chae_geumja', GEO, '태풍 전야', 'The Night Before the Storm',
      '출항을 조르는 손님을 거절할 것인가. 배우면 4-6 사고 확률 하락.',
      'Will you refuse the guest who insists on sailing? Learn it, and 4-6 gets safer.',
      [auto('craft', '태풍 대비 결속 자재 2점을 만든다', 'Make two lashing items for the storm', { target: 2 }),
        talk('chae_geumja', '거절하는 법을 배운다', 'Learn how to refuse')],
      { reputation: { harbor: { gyeongnam_geoje: 3 } } }],
  ]),
  ...subRows('N12', [
    ['N12-1', 4, 75, 4500, 'oh_gayun', YEO, '다툰 날의 방파제', 'The Breakwater on a Bad Day',
      '조과 0이어도 완료되는 유일한 퀘 — 목표가 \'일몰까지 자리를 지키기\'.',
      'The only quest that completes with zero catch — the goal is to stay until sunset.',
      [auto('gather', '해가 넘어갈 때까지 발밑 갯가를 훑는다 2회', 'Work the shore at your feet until the sun goes down, twice', { target: 2 }),
        man('holdPosition', '일몰까지 자리를 지킨다', 'Stay until sunset')]],
    ['N12-2', 4, 91, 7350, 'jeong_umi', YEO, '잔잔함', 'Calm',
      '커플의 밤바다 가이드. 화해든 이별이든 따뜻하게.',
      'Guiding a couple on the night sea. Reconciliation or parting — warmly.',
      [fish('hairtail', '갈치 2마리 (야간)', 'Two hairtail (night)', { target: 2 })],
      { journalPage: 9 }],
  ]),
  ...subRows('N13', [
    ['N13-1', 4, 88, 4500, 'ma_gamgi', TAE, '마감 도주', 'Deadline Escape',
      'PD의 추격을 피해 갑오징어 선상. 배 위에서 콘티가 완성된다.',
      'Fleeing the producer onto a cuttlefish boat. The storyboard gets finished on deck.',
      [fish('cuttlefish', '갑오징어 2마리', 'Two cuttlefish', { target: 2 })],
      { journalPage: 10 }],
    ['N13-2', 4, 97, 7350, 'song_gibaek', TAE, '두고 온 것', 'What Was Left Behind',
      '노인이 평생 찾던 것은 방제 봉사 때 단체사진이었다. 주인공은 자기 가족사진을 떠올린다.',
      'What the old man searched for all his life was a group photo from the oil-spill cleanup. You think of your own.',
      [auto('gather', '폐어선 주변을 뒤져 채집 3회', 'Search around the hulk — forage three times', { target: 3 }),
        talk('song_gibaek', '사진 이야기', 'The photograph')]],
  ]),
  ...subRows('N14', [
    ['N14-1', 5, 102, 6650, 'yu_ria', JEJ, '첫 로케', 'First Location Shoot',
      '방송 촬영 보조. 방어 한 마리 + 방송용 구도.',
      'Helping a TV shoot. One yellowtail, framed for camera.',
      [fish('yellowtail', '방어 1마리', 'One yellowtail')]],
    ['N14-2', 5, 108, 7500, 'oh_serin', JEJ, '버린 꿈', 'The Abandoned Dream',
      '서귀포 갯바위에서 마라를 찾아낸다. 재회 거부.',
      'You find Mara on the Seogwipo rocks. She refuses the reunion.',
      [fish('squid', '무늬오징어 1마리', 'One bigfin reef squid'), talk('mara', '마라를 찾아낸다', 'Find Mara')],
      { journalPage: 14 }],
    ['N14-3', 5, 114, 8350, 'oh_serin', JEJ, '팀', 'Team',
      '청년부 팀 등록 · 합동 지깅 훈련.',
      'Registering the youth team, joint jigging drills.',
      [fish(undefined, '지깅 훈련 3마리', 'Three fish in jigging drills', { target: 3 })]],
    ['N14-4', 5, 127, 12500, 'oh_serin', JEJ, '결선', 'The Final',
      '순위와 무관하게 완주. 세 사람 각자의 결말.',
      'Finishing regardless of rank. Three endings.',
      [fish('swordtip_squid', '한치 3마리', 'Three swordtip squid', { target: 3 })],
      { journalPage: 12 }],
  ]),
  ...subRows('N15', [
    ['N15-1', 6, 136, 12900, 'oh_sera', ULL, '혼자가 좋아요', 'I Like Being Alone',
      '동행 거절. 그녀의 포인트를 침범하지 않고 조과 겨루기 — 신규 규칙 \'매너 거리\'.',
      'She refuses company. Compete without crossing into her spot — the "manner distance" rule.',
      [fish('amberjack', '부시리 1마리', 'One amberjack')]],
    ['N15-2', 6, 152, 21000, 'yeon_taeo', ULL, '들킬 뻔한 밤', 'The Night Almost Caught',
      '태오와 마주치는 코미디 → 야간 합류.',
      'A comedy of bumping into Tae-o → a night session together.',
      [fish('amberjack', '부시리 2마리 (야간)', 'Two amberjack (night)', { target: 2 })],
      { journalPage: 16 }],
  ]),
  ...subRows('N16', [
    ['N16-1', 6, 132, 12900, 'seok_dokgu', ULL, '도전장', 'The Challenge',
      '"육지 사람은 못 잡아" — 볼락 대결. 현지 조달 미끼 · 낡은 사이소 릴을 물려준다.',
      '"Mainlanders can\'t catch here" — a rockfish duel. Local bait; you hand down the old Saiso reel.',
      [fish('dark_banded_rockfish', '볼락 3마리', 'Three rockfish', { target: 3 })]],
    ['N16-2', 6, 148, 16150, 'seok_dokgu', ULL, '등대까지', 'To the Lighthouse',
      '할아버지에게 가는 편지 심부름 → 6-3 조건.',
      'A letter errand to his grandfather → the condition for 6-3.',
      [fish(undefined, '등대 밑에서 1마리', 'One fish below the lighthouse'),
        talk('seok_daeyang', '편지를 전한다', 'Deliver the letter')]],
    ['N16-3', 7, 191, 46200, 'seok_dokgu', DOK, '독구의 첫 바다', 'Dok-gu\'s First Sea',
      '보호자 동의로 조사 보조 동행. 할아버지의 마지막 근무 교대.',
      'With his guardian\'s consent he joins the survey. His grandfather\'s last shift.',
      [fish('stone_beakperch', '돌돔 계측 후 방류', 'Measure and release a striped beakperch')],
      { journalPage: 17 }],
  ]),
  ...subRows('N17', [
    ['N17-1', 6, 138, 12900, 'dan_cheolho', INC, '퇴근길 20분', 'Twenty Minutes After Work',
      '게임 내 20분 제한 짬낚시 → 단골 식당에 무상 전달(§3 준수).',
      'A twenty-minute session → delivered free to the usual restaurant (rules respected).',
      [fish(undefined, '20분 안에 1마리', 'One fish within twenty minutes'), man('deliverFree', '식당에 무상 전달', 'Deliver it free')]],
    ['N17-2', 6, 156, 21050, 'ha_minji', INC, '첼로 케이스', 'The Cello Case',
      '연주회 당일 조과 파티. 두 사람이 재개관식 연주를 자청한다.',
      'A catch party on concert day. The two of them volunteer to play at the reopening.',
      [fish('black_rockfish', '우럭 2마리', 'Two black rockfish', { target: 2 })],
      { journalPage: 15 }],
  ]),
];


// ─────────────────────────────────────────────
// 137차 증설 — **회귀 고리와 인물 연결** (서브 35편, 챕터당 5편)
//
// 왜: 챕터가 넘어가면 다음 지역이 열리는 구조라 **이전 맵이 버려지는 맹점**이 있었다(사용자 지적).
//   이 35편은 그 구멍을 메운다 —
//   ① **회귀** 13편: 새 자격·새 장비를 들고 **이전 지역으로 되돌아가** 같은 사람을 다시 만난다.
//   ② **연결** : 인물끼리 서로를 안다(강두철↔고만석 옛 동료 · 정옥선↔탁만수 오십 년 · 배누리↔오세린 진로).
//   ③ **새 아크 2종**: N18 도현수(라이벌 — 7챕터 전부) · N19 정옥선·탁만수(서로를 향한 오래된 마음).
//
// ⚠ id 번호는 **발행 순서**이고, 배열·아크 questIds 순서는 **챕터 순서**(선행 조건)다.
//   기존 id를 다시 매기지 않는다 — 세이브(`story.done`)가 id로 진행을 기억한다.
// ─────────────────────────────────────────────
type ExtraRow = [id: string, arcId: string, ch: 1|2|3|4|5|6|7, lv: number, xp: number, giver: string, region: string,
  titleKo: string, titleEn: string, descKo: string, descEn: string, objectives: StoryObjective[],
  prereq: string[], extra?: Partial<StoryQuestDef>];

function subExtra(rows: ExtraRow[]): StoryQuestDef[] {
  return rows.map((r) => {
    const [id, arcId, chapter, minLevel, xp, giver, region, titleKo, titleEn, descKo, descEn, objectives, prereq, extra] = r;
    return { id, kind: 'sub', part: PART_OF[chapter], chapter, arcId, titleKo, titleEn, descKo, descEn,
      minLevel, xp, giver, region, prereq, objectives, ...extra } as StoryQuestDef;
  });
}

const SUB_EXTRA: StoryQuestDef[] = subExtra([
  // ── Ch1 속초 — 뒤에 되돌아올 사람들을 여기서 심는다 ──
  ['N18-1', 'N18', 1, 6, 350, 'hyeonsu', SOK, '같은 대를 든 놈', 'The Boy with the Same Rod',
    '도현수가 유품 릴대를 알아본다. "그거 어디서 났어." 같은 자리에서 한 마리씩 걸어 보자고 한다 — 첫 시비이자 첫 비교.',
    'Hyeon-su recognises the inherited rod. "Where did you get that." He wants one fish each from the same spot — the first jab, and the first comparison.',
    [fish(undefined, '도현수 옆자리에서 1마리', 'Catch one beside Hyeon-su'), talk('hyeonsu', '결과를 확인한다', 'Compare the results')],
    []],
  ['N19-1', 'N19', 1, 10, 350, 'tak_mansu', SOK, '얼음과 대나무', 'Ice and Bamboo',
    '탁 노인이 대나무 얼음 받침을 깎아 놓고 전하지 못하고 있다. "지나는 길에 좀 놓고 와라. 내가 줬다고는 하지 말고."',
    'The old man has carved a bamboo ice tray and cannot bring himself to deliver it. "Drop it off on your way. Don\'t say it was me."',
    [auto('custom', '가는 길에 얼음 나르기 1회', 'Haul ice once on the way', { placeKey: 'job:ice_haul' }),
      man('custom', '대나무 받침을 만복상회에 놓고 온다', 'Leave the bamboo tray at the Manbok Store'),
      talk('okseon', '정옥선의 반응을 본다', 'See how Ok-seon reacts')],
    []],
  ['N04-3', 'N04', 1, 16, 350, 'bae_nuri', SOK, '부원 모집 전단', 'Recruitment Flyers',
    '방파제부 존폐 위기. 전단을 붙이는 대신 배누리는 "낚는 걸 보여주면 된다"고 우긴다.',
    'The club is one member short of dissolution. Instead of flyers, Nu-ri insists that showing people a catch is enough.',
    [fish(undefined, '방파제에서 2마리', 'Catch two at the breakwater', { target: 2 }),
      talk('bae_nuri', '구경 온 학생에게 대를 쥐여 준다', 'Put the rod in a curious student\'s hands')],
    ['N04-2']],
  ['N03-5', 'N03', 1, 14, 350, 'kang_ducheol', SOK, '도래 스무 개', 'Twenty Swivels',
    '"손이 기억할 때까지 묶어 봐." 초보 행세하는 노인이 스무 번을 세고 앉아 있다. 가르치는 쪽이 더 배운다.',
    '"Tie until your hands remember." The old man playing beginner sits and counts to twenty. The one teaching learns more.',
    [fish(undefined, '묶은 채비로 3마리를 낚아 보인다', 'Show him three fish caught on the rigs you tied', { target: 3 }),
      man('custom', '채비를 스무 번 묶어 보인다', 'Tie the rig twenty times')],
    ['N03-1']],
  ['N02-5', 'N02', 1, 17, 350, 'tak_mansu', SOK, '대를 고르는 눈', 'An Eye for Bamboo',
    '세워 둔 대나무 셋 중 쓸 만한 것을 고르라 한다. 두께도 색도 아니고, 마디 간격이 답이다.',
    'Three lengths of bamboo, pick the usable one. Not thickness, not colour — the answer is the spacing of the nodes.',
    [auto('gather', '쓸 만한 대를 찾아 갯가를 훑는다 2회', 'Comb the shore for usable poles, twice', { target: 2 }),
      man('custom', '쓸 만한 대나무를 고른다', 'Pick the usable pole'),
      talk('tak_mansu', '왜 그것인지 듣는다', 'Hear why it was that one')],
    ['N02-1']],

  // ── Ch2 부산 — 두 편은 속초로 되돌아간다 ──
  ['N18-2', 'N18', 2, 25, 1450, 'hyeonsu', BUS, '경매장 뒷줄', 'Back Row at the Auction',
    '도현수가 부산 경매장 뒷줄에 서 있다. 계원 아들이 아니라 한 사람의 중개인으로서. "여기선 네 이름 아무도 몰라."',
    'Hyeon-su is standing at the back of the Busan auction hall — not as the chief\'s grandson but as a broker. "Nobody here knows your name."',
    [auto('sell', '낙찰가를 직접 확인한다 — 위판 2건', 'See the hammer price yourself — two consigned lots', { target: 2 }),
      man('custom', '경매 낙찰가를 함께 읽는다', 'Read the hammer prices together')],
    ['N18-1']],
  ['N19-2', 'N19', 2, 29, 1450, 'okseon', SOK, '부고 아닌 편지', 'A Letter That Is Not an Obituary',
    '탁 노인이 앓아누웠다는 소문에 정옥선이 반찬통을 싸 놓고 망설인다. "늙은이가 늙은이 걱정하는 거, 우습나."',
    'Word comes that the old man is ill. Ok-seon packs side dishes and hesitates. "One old person worrying about another. Funny, is it?"',
    [auto('visit', '속초로 돌아간다', 'Return to Sokcho', { placeKey: 'region:gangwon_sokcho' }),
      man('custom', '반찬통을 죽간 공방에 전한다', 'Deliver the food to the workshop')],
    ['N19-1']],
  ['N04-4', 'N04', 2, 32, 1450, 'bae_nuri', BUS, '원정 도시락', 'An Away-Game Lunchbox',
    '방파제부 첫 원정. 부산까지 와서 도시락부터 까먹는다. 모진주가 말없이 제일 먼저 낚는다.',
    'The club\'s first away trip. They get to Busan and open the lunchboxes first. Jin-ju, saying nothing, catches first.',
    [fish(undefined, '학생들보다 먼저 1마리', 'Land one before the students')],
    ['N04-3']],
  ['N05-6', 'N05', 2, 41, 1450, 'seo_harin', BUS, '구독자 없는 방송', 'A Stream with No Viewers',
    '서하린의 라이브 시청자가 셋이다. 나기범은 카메라를 등지고 앉아 묵묵히 손질만 한다. "재미없어도 진짜면 돼."',
    'Ha-rin\'s live stream has three viewers. Gi-beom sits with his back to the camera and just keeps filleting. "Boring is fine if it is real."',
    [auto('butcher', '방송 중에 원물 1마리 손질', 'Butcher one fish on stream')],
    ['N05-2']],
  ['N02-6', 'N02', 2, 38, 1450, 'tak_saebyeok', SOK, '새벽의 첫 대', 'Sae-byeok\'s First Rod',
    '열두 살이 자기 손으로 처음 대를 완성했다. 할아버지는 보지도 않고 "얇다"고 한다. 그래도 그날 밤 그 대로 낚는다.',
    'The twelve-year-old finishes a rod alone. His grandfather says "too thin" without looking. That night they fish with it anyway.',
    [auto('visit', '속초 죽간 공방으로 돌아간다', 'Return to the Sokcho workshop', { placeKey: 'region:gangwon_sokcho' }),
      fish(undefined, '새벽이 만든 대로 1마리', 'Catch one with the rod he made')],
    ['N02-5']],

  // ── Ch3 울산·포항 — 옛 동료가 드러난다 ──
  ['N18-3', 'N18', 3, 50, 3400, 'hyeonsu', POH, '명태 이야기', 'Talking About Pollock',
    '구술 채록을 돕겠다며 따라온다. 노인들이 도현수를 붙잡고 놓아 주질 않는다. 받아 적는 손이 두 개가 된다.',
    'He tags along to help with the oral history. The old men will not let him go. Two hands are writing now.',
    [auto('release', '노인들이 말한 그 종을 만나 놓아준다', 'Meet the species they spoke of, and let it go'),
      man('custom', '구술 채록 1건을 함께 받아 적는다', 'Take down one account together')],
    ['N18-2']],
  ['N03-6', 'N03', 3, 54, 3400, 'kang_ducheol', ULS, '조합장과 선장', 'The Chief and the Skipper',
    '강두철이 방어진에 나타난다. 고만석과는 서른 해 전 같은 배를 탔다. 두 노인은 인사 대신 서로의 손을 본다.',
    'Kang Du-cheol turns up in Bangeojin. He and Go Man-seok shared a boat thirty years ago. Instead of greeting, the two old men look at each other\'s hands.',
    [auto('visit', '울산 방어진으로 간다', 'Go to Bangeojin, Ulsan', { placeKey: 'region:ulsan' }),
      talk('go_manseok', '두 사람의 옛 이야기를 듣는다', 'Hear the two of them talk')],
    ['N03-2']],
  ['N19-3', 'N19', 3, 58, 3400, 'tak_mansu', SOK, '대를 다시 깎는 손', 'Hands That Carve Again',
    '반찬통이 돌아온 뒤로 노인이 다시 대를 깎는다. 이번엔 자기 것이 아니라 좌판에 놓을 받침대다. 두 번째.',
    'Since the food came back, he has started carving again — not for himself, but a second tray for the stall.',
    [auto('visit', '속초로 돌아간다', 'Return to Sokcho', { placeKey: 'region:gangwon_sokcho' }),
      man('custom', '두 번째 받침을 전한다', 'Deliver the second tray')],
    ['N19-2']],
  ['N05-7', 'N05', 3, 62, 3400, 'na_gibeom', BUS, '겨울 가게', 'The Winter Shop',
    '나기범이 작은 가게를 냈다. 손님은 없고 수조만 돌아간다. 서하린은 촬영 대신 설거지를 하고 있다.',
    'Gi-beom has opened a small shop. No customers, just the tank humming. Ha-rin is washing dishes instead of filming.',
    [auto('visit', '부산으로 돌아간다', 'Return to Busan', { placeKey: 'region:busan' }),
      auto('sashimi', '가게에서 회뜨기 1회', 'Slice sashimi once in the shop')],
    ['N05-6']],
  ['N08-3', 'N08', 3, 66, 3400, 'go_haena', ULS, '조타실의 딸', 'The Daughter at the Wheel',
    '고해나가 아버지 몰래 조타 연습을 한다. 선장은 알면서 모른 척한다. 승객 하나가 그 광경을 사진으로 찍는다.',
    'Hae-na practises steering behind her father\'s back. The skipper knows and pretends not to. A passenger photographs the scene.',
    [fish('yellowtail', '해나가 세운 자리에서 방어 1마리', 'One yellowtail where Hae-na put the boat'),
      man('boatTrip', '해나의 조타로 한 항차', 'One run with Hae-na at the wheel')],
    ['N08-2']],

  // ── Ch4 거제·여수·태안 — 배를 갖고 되돌아간다 ──
  ['N18-4', 'N18', 4, 75, 5850, 'hyeonsu', GEO, '같은 배를 보는 눈', 'Looking at the Same Boat',
    '중고 선박을 같이 보러 간다. 도현수는 값을, 나는 바닥을 본다. 처음으로 서로의 시선이 쓸모 있다.',
    'You go to look at used boats together. He looks at the price, you look at the hull. For once, each other\'s eyes are useful.',
    [auto('sell', '배값을 맞춰 본다 — 위판 4건', 'Count toward the price — four consigned lots', { target: 4 }),
      man('custom', '선체 검수를 함께 본다', 'Inspect the hull together')],
    ['N18-3']],
  ['N04-5', 'N04', 4, 79, 5850, 'bae_nuri', SOK, '진로 상담', 'Career Counselling',
    '배누리가 수산고 진학을 고민한다. 어른 한 명이 필요하다고 불렀는데, 그게 나다.',
    'Nu-ri is weighing up the fisheries high school. She said she needed one adult in the room, and the adult is you.',
    [auto('visit', '속초 청초고로 간다', 'Go to Cheongcho High in Sokcho', { placeKey: 'region:gangwon_sokcho' }),
      talk('bae_nuri', '진로 이야기를 끝까지 듣는다', 'Hear her out to the end')],
    ['N04-4']],
  ['N19-4', 'N19', 4, 85, 5850, 'okseon', SOK, '같이 늙는 일', 'Growing Old Together',
    '좌판에 대나무 받침이 두 개 놓였다. 정옥선은 아무 말도 안 하고, 노인은 매일 같은 시간에 지나간다.',
    'Two bamboo trays now sit on the stall. Ok-seon says nothing, and the old man walks past at the same hour every day.',
    [auto('visit', '속초 직판장으로 돌아간다', 'Return to the Sokcho market', { placeKey: 'region:gangwon_sokcho' }),
      man('custom', '두 사람을 한자리에 앉힌다', 'Get the two of them to sit down together')],
    ['N19-3']],
  ['N09-4', 'N09', 4, 90, 5850, 'lee_suyeon', POH, '구룡포의 봄', 'Spring in Guryongpo',
    '이수연이 아버지 배를 팔았다. 한봄은 그 돈으로 식당을 하자고 한다. 상실을 지나온 자리에 부엌이 선다.',
    'Su-yeon has sold her father\'s boat. Bom wants to open a kitchen with the money. A kitchen stands where the loss was.',
    [auto('visit', '포항 구룡포로 돌아간다', 'Return to Guryongpo, Pohang', { placeKey: 'region:gyeongbuk_pohang' }),
      auto('butcher', '개업 상에 올릴 원물 1마리 손질', 'Butcher one fish for the opening table')],
    ['N09-3']],
  ['N11-4', 'N11', 4, 95, 5850, 'chae_pado', GEO, '덜렁이의 첫 손님', 'The Klutz\'s First Fare',
    '채파도가 처음으로 손님 한 팀을 혼자 맡는다. 채금자는 부두에서 등을 돌린 채 듣고만 있다.',
    'Pado takes a party out alone for the first time. Geum-ja stands on the quay with her back turned, listening.',
    [fish(undefined, '파도의 손님 몫 2마리', 'Two fish for Pado\'s party', { target: 2 }),
      man('boatTrip', '파도의 첫 단독 출조에 동승', 'Ride along on Pado\'s first solo trip')],
    ['N11-3']],

  // ── Ch5 제주 — 네 편이 이전 지역으로 돌아간다 ──
  ['N18-5', 'N18', 5, 105, 9250, 'hyeonsu', JEJ, '표결 전야', 'The Night Before the Vote',
    '낚시공원 표결을 앞두고 도현수가 반대편 자료를 들고 온다. "네 말이 맞으면 내가 진 거잖아." 그래도 들고 왔다.',
    'The night before the park vote, Hyeon-su brings the other side\'s papers. "If you\'re right, I lose." He brought them anyway.',
    [auto('gather', '자료에 붙일 조간대 표본 3점', 'Three tideline samples for the file', { target: 3 }),
      man('custom', '찬반 자료를 같이 정리한다', 'Sort the arguments together')],
    ['N18-4']],
  ['N06-4', 'N06', 5, 110, 9250, 'mo_taejo', BUS, '졸업 대결', 'The Graduation Match',
    '씨바스터즈가 해산한다. 마지막 대결 상대로 나를 지명한다. 고호수는 아직도 농구공을 들고 온다.',
    'The Seabassters are disbanding. They name you as the final opponent. Ho-su still turns up with a basketball.',
    [auto('visit', '부산으로 돌아간다', 'Return to Busan', { placeKey: 'region:busan' }),
      fish(undefined, '대결에서 2마리', 'Two fish in the match', { target: 2 })],
    ['N06-3']],
  ['N08-4', 'N08', 5, 116, 9250, 'go_manseok', ULS, '배를 내놓을까 한다', 'I Might Sell Her',
    '고만석이 처음으로 은퇴를 입에 올린다. 고해나는 아무 말도 하지 않는다. 그날 조황은 그 해 최고였다.',
    'Man-seok mentions retirement for the first time. Hae-na says nothing. The catch that day was the best of the year.',
    [auto('visit', '울산으로 돌아간다', 'Return to Ulsan', { placeKey: 'region:ulsan' }),
      talk('go_manseok', '선장의 이야기를 듣는다', 'Hear the skipper out')],
    ['N08-3']],
  ['N13-3', 'N13', 5, 122, 9250, 'song_gibaek', TAE, '폐어선의 겨울', 'Winter on the Hulk',
    '여든하나의 겨울. 난로가 고장 났는데 고쳐 달라는 말을 안 한다. 마감기가 대신 말한다.',
    'An eighty-first winter. The stove is broken and he will not ask. Ma Gam-gi asks for him.',
    [auto('visit', '태안 신진도로 돌아간다', 'Return to Sinjindo, Taean', { placeKey: 'region:chungnam_taean' }),
      man('custom', '난로를 손봐 준다', 'Fix the stove')],
    ['N13-2']],
  ['N12-3', 'N12', 5, 127, 9250, 'oh_gayun', YEO, '호텔 로비의 캠핑카', 'A Camper in the Hotel Lobby',
    '정우미의 캠핑카가 호텔 주차장에 반년째 서 있다. 오가윤은 퇴근하면 그 차 앞에 앉아 있다.',
    'U-mi\'s camper has been in the hotel car park for six months. Ga-yun sits in front of it after every shift.',
    [auto('visit', '여수로 돌아간다', 'Return to Yeosu', { placeKey: 'region:jeonnam_yeosu' }),
      talk('jeong_umi', '두 사람과 밤 낚시를 나간다', 'Go night fishing with the two of them')],
    ['N12-2']],

  // ── Ch6 울릉·인천 — 병실과 창고 ──
  ['N18-6', 'N18', 6, 135, 16350, 'hyeonsu', INC, '원산지 표기', 'Country of Origin',
    '인천 도매시장에서 도현수가 원산지 위반을 잡아낸다. 어촌계장 손자가 아니라 검사원의 눈이다.',
    'At the Incheon wholesale market Hyeon-su spots a mislabelled origin. That is an inspector\'s eye, not a chief\'s grandson\'s.',
    [auto('sell', '원산지를 적어 위판 3건', 'Three consigned lots, origin written in', { target: 3 }),
      man('custom', '표기 위반 한 건을 함께 확인한다', 'Confirm one labelling violation together')],
    ['N18-5']],
  ['N19-5', 'N19', 6, 141, 16350, 'tak_mansu', SOK, '병실 앞 복도', 'The Corridor Outside the Ward',
    '정옥선이 입원한 병원 복도. 노인은 들어가지 못하고 벽에 기대 서 있다. 손에는 세 번째 받침이 들려 있다.',
    'The hospital corridor. The old man cannot go in, so he leans on the wall. In his hands, a third tray.',
    [auto('visit', '속초 병원으로 간다', 'Go to the hospital in Sokcho', { placeKey: 'region:gangwon_sokcho' }),
      man('custom', '노인을 병실 안으로 들여보낸다', 'Get him through the door')],
    ['N19-4']],
  ['N03-7', 'N03', 6, 147, 16350, 'kang_ducheol', INC, '조합장의 출장', 'The Chief on the Road',
    '강두철이 인천 유통 현장에 나타난다. 이번엔 초보 행세를 하지 않는다. 대신 내 뒤에 서서 지켜본다.',
    'Kang Du-cheol shows up at the Incheon distribution floor. This time he does not play the beginner — he stands behind you and watches.',
    [auto('sell', '경로를 따라가 본다 — 위판 4건', 'Follow the route yourself — four consigned lots', { target: 4 }),
      man('custom', '유통 경로 한 건을 설명해 보인다', 'Walk him through one distribution route')],
    ['N03-3']],
  ['N10-4', 'N10', 6, 152, 16350, 'namgung_hyeon', POH, '야간 창고의 불빛', 'The Light in the Night Warehouse',
    '남궁현이 창고를 그만둔다. 마지막 야간 근무에 불을 끄기 전, 처음으로 자기 대를 꺼낸다.',
    'Namgung Hyeon is leaving the warehouse. On his last night shift, before the lights go out, he takes out his own rod for the first time.',
    [auto('visit', '포항으로 돌아간다', 'Return to Pohang', { placeKey: 'region:gyeongbuk_pohang' }),
      fish(undefined, '전설과 나란히 1마리', 'One fish beside the legend')],
    ['N10-2']],
  ['N17-3', 'N17', 6, 157, 16350, 'dan_cheolho', INC, '퇴근 후 30분', 'Thirty Minutes After Work',
    '부장님이 팀원 전부를 데리고 나왔다. 30분짜리 짬낚시가 열두 명이 되면 그건 회식이다.',
    'The department head has brought the whole team. A thirty-minute session with twelve people is a works outing.',
    [fish(undefined, '30분 안에 3마리', 'Three fish within thirty minutes', { target: 3 })],
    ['N17-2']],

  // ── Ch7 독도·속초 — 되돌아온 사람들 ──
  ['N18-7', 'N18', 7, 166, 40200, 'hyeonsu', SOK, '나란히 서서', 'Standing Side by Side',
    '재개관식 준비. 도현수가 의자를 나른다. "네 이름으로 여는 거 아니야. 우리 이름으로 여는 거지." 처음으로 우리라고 한다.',
    'Setting up for the reopening. Hyeon-su carries chairs. "It isn\'t opening under your name. It\'s ours." The first time he says ours.',
    [auto('craft', '재개관식에 쓸 비품 3점을 만든다', 'Make three fittings for the reopening', { target: 3 }),
      man('custom', '재개관식 준비를 함께 한다', 'Set up the reopening together')],
    ['N18-6']],
  ['N19-6', 'N19', 7, 172, 40200, 'okseon', SOK, '손을 잡는 데 오십 년', 'Fifty Years to Hold a Hand',
    '요양을 마친 정옥선이 휠체어로 좌판에 나온다. 대나무 받침 셋이 나란히 놓여 있다. 노인이 옆자리에 앉는다.',
    'Out of care, Ok-seon comes to the stall in a wheelchair. Three bamboo trays sit in a row. The old man takes the seat beside her.',
    [auto('sashimi', '두 사람 몫 회 2접시', 'Two plates for the two of them', { target: 2 }),
      talk('okseon', '두 사람의 자리를 만들어 준다', 'Make room for the two of them')],
    ['N19-5']],
  ['N04-6', 'N04', 7, 178, 40200, 'bae_nuri', SOK, '졸업한 부원들', 'The Club, Graduated',
    '배누리는 수산고 3학년, 하수아는 대학, 모진주는 배를 탄다. 셋이 재개관식에 부 깃발을 들고 온다.',
    'Nu-ri is in her final year, Su-a is at university, Jin-ju is on a boat. The three of them bring the club flag to the reopening.',
    [fish(undefined, '졸업한 부원들과 나란히 3마리', 'Three fish alongside the graduated club', { target: 3 }),
      talk('bae_nuri', '부 깃발을 2층에 건다', 'Hang the club flag upstairs')],
    ['N04-5']],
  ['N16-4', 'N16', 7, 192, 40200, 'seok_dokgu', DOK, '독구의 첫 제자', 'Dok-gu\'s First Student',
    '열두 살이 조사단 대학생에게 갯바위를 가르친다. 가르치는 얼굴이 낯익다. 내가 받은 것이 그대로 건너간다.',
    'The twelve-year-old teaches a survey student how to read the rocks. The look on his face is familiar — what you were given, passing on.',
    [auto('release', '독구와 함께 2마리 계측 후 방류', 'Measure and release two with Dok-gu', { target: 2 })],
    ['N16-3']],
  ['N14-5', 'N14', 7, 196, 40200, 'oh_serin', JEJ, '다시 제주', 'Jeju Again',
    '오세린이 대회 운영진이 됐다. 마라는 카메라를 들었고, 유리아는 해설석에 앉았다. 셋 다 다른 방식으로 남았다.',
    'Se-rin now runs the tournament. Mara holds a camera, Ri-a sits in the commentary box. All three stayed, each in their own way.',
    [auto('visit', '제주로 돌아간다', 'Return to Jeju', { placeKey: 'region:jeju' }),
      talk('oh_serin', '대회 개회 선언을 듣는다', 'Hear the opening declaration')],
    ['N14-4']],
]);


/**
 * 138차 증설 — 과증식 대응(N21) · 어종 관리(N23) · 콘텐츠 제작(N20) · 생활 기반(N22).
 *
 * 설계 원칙 3가지
 *  1. **기존 시스템에 의미를 얹는다.** 탈출 양식 광어는 133차 비만도(condition factor)를,
 *     금어기 계측은 134차 법 규칙을 판정 근거로 그대로 쓴다. 새 판정식을 만들지 않는다.
 *  2. **확률 드랍 목표 금지.** 알비노 개체는 "잡아 와라"가 아니라 조건(스팟·물때)을 맞추는
 *     퀘스트로 쓴다 — 아니면 영구 미완 퀘스트가 된다.
 *  3. **manual 목표는 챕터당 2편까지.** 농사·광질·리빙은 시스템이 아직 없어 대화로 닫지만,
 *     그런 편이 쌓이면 "대화만 하는 퀘스트"가 되어 체감이 빈다. 시스템이 붙으면 플래그만 뺀다.
 */
const SUB_138: StoryQuestDef[] = subExtra([
  // ── N21 오세찬 — 바다가 넘칠 때 (과증식 대응) ──
  ['N21-1', 'N21', 1, 12, 350, 'oh_sechan', SOK, '해안에 밀려온 별', 'Stars Washed Ashore',
    '방파제 밑에 불가사리가 널렸다. 감시원은 두 종을 가려 보라고 한다 — 팔이 짧고 넓으면 별불가사리, 길고 끝이 젖혀졌으면 아무르다.',
    'Starfish litter the foot of the breakwater. The monitor asks you to tell them apart — short broad arms for the bat star, long upturned ones for the Amur.',
    [auto('cull', '밀려온 불가사리 3개를 줍는다', 'Pick up three washed-up starfish', { speciesId: 'blue_bat_star', target: 3 }),
      talk('oh_sechan', '두 종의 차이를 확인한다', 'Learn to tell the two apart')],
    [], { teaches: ['nuisance'] }],
  ['N21-2', 'N21', 2, 30, 1450, 'oh_sechan', BUS, '여름이 오면 떠오른다', 'They Rise with the Summer',
    '만 안쪽이 보름달물해파리로 덮였다. 그물에 딸려 들어와 어획물을 상하게 하니, 눈에 띄는 대로 걷어 내라고 한다.',
    'The inner bay is carpeted with moon jellies. They foul every net they touch — clear what you can see.',
    [cull('moon_jelly', '보름달물해파리 5마리를 수거한다', 'Collect five moon jellyfish', 5)],
    ['N21-1'], { teaches: ['bloom'] }],
  ['N21-3', 'N21', 3, 58, 3400, 'oh_sechan', ULS, '수매 창구', 'The Buy-Back Window',
    '아무르불가사리는 지자체가 kg으로 사들인다. 별불가사리를 섞어 오면 창구에서 그대로 돌려보낸다.',
    'The city buys Amur seastars by the kilo. Mix in bat stars and the window sends you straight back.',
    [cull('amur_star', '아무르불가사리 8개를 수거한다', 'Collect eight Amur seastars', 8),
      talk('oh_sechan', '수매 창구에 넘긴다', 'Hand them in at the window')],
    ['N21-2'], { teaches: ['nuisance'] }],
  ['N21-4', 'N21', 4, 95, 5850, 'oh_sechan', GEO, '가두리 앞바다', 'Off the Pens',
    '양식 가두리 앞이 막혔다. 취수구까지 밀려가기 전에 걷어야 한다.',
    'The water in front of the pens is choked. Clear it before the drift reaches the intake.',
    [cull('moon_jelly', '보름달물해파리 10마리를 수거한다', 'Collect ten moon jellyfish', 10)],
    ['N21-3']],
  ['N21-5', 'N21', 5, 128, 9250, 'oh_sechan', JEJ, '실이 늘어진 그림자', 'A Shadow Trailing Threads',
    '수면 아래로 커다란 갈색 그림자가 지나간다. 노무라입깃해파리 — 한 마리가 100kg을 넘는다. 끌어오는 데만 한참 걸릴 것이다.',
    'A vast brown shadow slides past under the surface. A Nomura\'s jellyfish — one animal can top 100 kg. Hauling it will take a while.',
    [cull('nomura_jelly', '노무라입깃해파리 1마리를 끌어올린다', "Haul in one Nomura's jellyfish"),
      talk('oh_sechan', '쏘이지 않았는지 확인한다', 'Check yourself for stings')],
    ['N21-4'], { teaches: ['bloom'] }],
  ['N21-6', 'N21', 6, 160, 16350, 'oh_sechan', ULL, '그물을 찢는 것', 'What Tears the Nets',
    '울릉 앞바다에 노무라가 떼로 들어왔다. 한 마리씩 걷어 내는 것 말고는 방법이 없다.',
    'Nomura jellies have come into Ulleung waters in numbers. There is no way but one at a time.',
    [cull('nomura_jelly', '노무라입깃해파리 3마리를 수거한다', "Collect three Nomura's jellyfish", 3)],
    ['N21-5']],
  ['N21-7', 'N21', 7, 190, 40200, 'oh_sechan', DOK, '넘치는 바다', 'A Sea That Overflows',
    '감시원은 은퇴를 앞두고 마지막 기록을 남긴다. "숫자로 남겨야 다음 사람이 손을 쓴다."',
    'The monitor is retiring, and wants one last record. "Only numbers make the next person act."',
    [cull('nomura_jelly', '노무라입깃해파리 2마리', "Two Nomura's jellyfish", 2),
      cull('moon_jelly', '보름달물해파리 10마리', 'Ten moon jellyfish', 10),
      talk('oh_sechan', '관측 기록을 넘긴다', 'Hand over the survey log')],
    ['N21-6'], { teaches: ['bloom'] }],

  // ── N23 채수림 — 세는 사람 (어종 관리) ──
  ['N23-1', 'N23', 2, 34, 1450, 'chae_surim', BUS, '탈출한 광어', 'The Flounder That Got Out',
    '태풍에 가두리가 터졌다. 양식 개체는 지느러미가 닳고 **비만도가 비정상적으로 높다** — 상세보기로 가릴 수 있다.',
    'A typhoon tore the pens open. Farmed fish have worn fins and an abnormally high condition factor — the detail view will show it.',
    [fish('flatfish', '광어 3마리를 잡아 계측한다', 'Catch and measure three flounder', { target: 3 }),
      talk('chae_surim', '양식 개체를 가려낸다', 'Sort out the escapees')],
    [], { teaches: ['aquaculture', 'measure'] }],
  ['N23-2', 'N23', 3, 62, 3400, 'chae_surim', POH, '흰 그림자', 'The Pale One',
    '흰 개체를 봤다는 말이 돈다. 소문을 따라가면 결국 자리와 물때 이야기다 — 그 조건에 서 있어야 만난다.',
    'People keep saying they saw a white one. Chase the rumour far enough and it is always about a spot and a tide — stand there at that hour.',
    [auto('visit', '소문이 가리키는 자리에 선다', 'Stand where the rumour points', { placeKey: 'region:gyeongbuk_pohang' }),
      fish(undefined, '그 물때에 1마리를 건진다', 'Land one on that tide'),
      talk('chae_surim', '개체를 기록한다', 'Log the specimen')],
    ['N23-1'], { teaches: ['codex'] }],
  ['N23-3', 'N23', 4, 100, 5850, 'chae_surim', YEO, '접시 위의 증명', 'Proof on a Plate',
    '"좋은 개체였다는 걸 말로 하지 마시고요." 특급 등급으로 회를 떠 오라고 한다. 손질이 곧 증명이다.',
    '"Don\'t tell me it was a good fish." She wants it filleted at top grade. The knife is the evidence.',
    [auto('sashimi', '회를 떠서 낸다', 'Fillet and serve the sashimi'),
      talk('chae_surim', '등급을 확인받는다', 'Have the grade checked')],
    ['N23-2'], { teaches: ['grading', 'sashimi'] }],
  ['N23-4', 'N23', 5, 132, 9250, 'chae_surim', JEJ, '금어기의 자', 'The Ruler in Closed Season',
    '금어기 개체는 재고 돌려보내면 된다. 기록은 남고, 개체는 산다.',
    'A closed-season fish can be measured and returned. The record stays; the fish lives.',
    [auto('release', '금지체장·금어기 개체를 계측 후 방생한다 5회', 'Measure and release five protected fish', { target: 5 })],
    ['N23-3'], { teaches: ['law', 'release'] }],
  ['N23-5', 'N23', 6, 164, 16350, 'chae_surim', INC, '종을 세는 일', 'Counting Species',
    '"몇 마리를 잡았냐가 아니라 몇 종을 봤냐를 적어요." 도감이 곧 조사표가 된다.',
    '"Write down how many species you saw, not how many fish." The codex becomes the survey sheet.',
    [fish(undefined, '조사표에 올릴 어획 5건', 'Five catches for the survey sheet', { target: 5 }),
      man('custom', '도감에 40종 이상을 채운다', 'Fill the codex to 40 species'),
      talk('chae_surim', '조사표를 넘긴다', 'Hand in the survey sheet')],
    ['N23-4'], { teaches: ['codex'] }],
  ['N23-6', 'N23', 7, 192, 40200, 'chae_surim', DOK, '남길 것', 'What to Leave Behind',
    '조사표는 다음 사람에게 간다. 마지막 장은 비워 두라고 한다 — "당신이 본 걸 적으라고."',
    'The survey sheet goes to whoever comes next. She leaves the last page blank — "for what you saw."',
    [auto('sashimi', '기록에 남길 한 접시를 뜬다', 'Slice the one plate for the record'),
      auto('cook', '기록에 남길 한 접시를 만든다', 'Cook the one dish for the record'),   // 154차 — 불요리가 서서 auto 승격
      talk('chae_surim', '마지막 장을 받는다', 'Receive the last page')],
    ['N23-5'], { teaches: ['journalComplete'] }],

  // ── N20 유하랑 — 카메라를 든 사람 (콘텐츠 제작) ──
  ['N20-1', 'N20', 2, 32, 1450, 'yu_harang', BUS, '구독자 삼백', 'Three Hundred Subscribers',
    '삼각대를 세워 두고 혼자 떠드는 사람이 있다. "한 마리만 잡아 주시면 안 돼요? 그림이 안 나와서."',
    'Someone is talking to a tripod, alone. "Could you just catch one? I have no footage."',
    [fish(undefined, '카메라 앞에서 1마리', 'Land one on camera'),
      talk('yu_harang', '방송 끝나고 이야기한다', 'Talk after the stream ends')],
    [], { teaches: ['streaming'] }],
  ['N20-2', 'N20', 3, 60, 3400, 'yu_harang', ULS, '섬네일 각', 'The Thumbnail Shot',
    '"해 떨어지는 그림이 필요해요." 조과가 없어도 좋으니 일몰까지 자리를 지켜 달라고 한다.',
    '"I need the sunset shot." She asks you to hold the spot until dusk — catch or no catch.',
    [fish(undefined, '해질 무렵 2마리', 'Two fish at dusk', { target: 2 }),
      man('holdPosition', '일몰까지 자리를 지킨다', 'Hold the spot until sunset'),
      talk('yu_harang', '찍힌 걸 같이 본다', 'Watch the footage together')],
    ['N20-1']],
  ['N20-3', 'N20', 4, 98, 5850, 'yu_harang', GEO, '합방 요청', 'A Collab Request',
    '"같이 찍어요. 대신 그쪽 홈그라운드로 갈게요." 카메라가 속초까지 따라온다.',
    '"Let\'s film together — I\'ll come to your home ground." The camera follows you all the way back to Sokcho.',
    [auto('visit', '속초로 돌아가 합방 자리를 잡는다', 'Return to Sokcho and set up the collab', { placeKey: 'region:gangwon_sokcho' }),
      fish(undefined, '둘이 나란히 2마리', 'Two fish, side by side', { target: 2 }),
      talk('yu_harang', '편집본을 확인한다', 'Check the cut')],
    ['N20-2'], { teaches: ['returnTrip', 'streaming'] }],
  ['N20-4', 'N20', 5, 130, 9250, 'yu_harang', JEJ, '조회수와 금어기', 'Views and Closed Season',
    '금어기 개체가 걸렸다. "그거 잠깐만 들고 계세요, 각만 잡고." 들어줄 수도, 거절할 수도 있다.',
    'A closed-season fish comes up. "Just hold it a second, for the shot." You can oblige — or refuse.',
    [auto('release', '계측 후 방생한다', 'Measure it and let it go'),
      talk('yu_harang', '왜 그랬는지 말한다', 'Tell her why')],
    ['N20-3'], { teaches: ['law', 'reputation'] }],
  ['N20-5', 'N20', 6, 162, 16350, 'yu_harang', ULL, '오프라인', 'Offline',
    '구독자 몇이 울릉까지 찾아왔다. 하랑은 카메라를 껐다. "오늘은 그냥 낚시할래요."',
    'A few subscribers came all the way to Ulleung. Ha-rang switches the camera off. "Today I just want to fish."',
    [fish(undefined, '카메라 없이 3마리', 'Three fish, no camera', { target: 3 }),
      talk('yu_harang', '끝나고 같이 먹는다', 'Eat together afterwards')],
    ['N20-4']],
  ['N20-6', 'N20', 7, 188, 40200, 'yu_harang', DOK, '마지막 라이브', 'The Last Live',
    '독도에서 방송하겠다고 한다. 신호가 끊기는 자리라 아무도 안 본다는 걸 알면서도.',
    'She wants to stream from Dokdo — knowing the signal drops and no one will be watching.',
    [man('boatTrip', '독도 출조에 동행한다', 'Ride out to Dokdo with her'),
      fish(undefined, '방송 중 1마리', 'One fish, live')],
    ['N20-5']],
  ['N20-7', 'N20', 7, 194, 40200, 'yu_harang', DOK, '자막 없는 영상', 'A Video with No Subtitles',
    '편집 없이, 자막 없이 올린 영상이 제일 오래 남았다. 하랑은 다음 항구로 간다.',
    'The unedited, unsubtitled video is the one that lasted. Ha-rang leaves for the next port.',
    [fish('stone_beakperch', '자막 없이 남길 한 장면 — 돌돔 1마리', 'The one shot with no subtitles — a striped beakperch'),
      talk('yu_harang', '다음 항구 이야기를 듣는다', 'Hear where she is going next'),
      man('custom', '영상에 쓸 한 컷을 고른다', 'Pick the one frame for the video')],
    ['N20-6'], { teaches: ['streaming'] }],

  // ── N22 하늬 — 손으로 짓는 것 (제작·농사·광질·리빙) ──
  ['N22-1', 'N22', 2, 28, 1450, 'ha_nui', BUS, '작업대를 세우다', 'Setting Up a Bench',
    '"사서 쓰는 것도 방법인데, 한 번은 만들어 봐야 뭘 사야 할지 알아요."',
    '"Buying works fine — but make one once and you\'ll know what to buy."',
    [auto('craft', '도면으로 무엇이든 하나 만든다', 'Craft anything from a blueprint'),
      talk('ha_nui', '만든 걸 보여 준다', 'Show her what you made')],
    [], { teaches: ['crafting'] }],
  ['N22-2', 'N22', 3, 56, 3400, 'ha_nui', ULS, '빈 방', 'An Empty Room',
    '"자는 데랑 사는 데는 달라요." 방에 무엇을 둘지부터 정하라고 한다.',
    '"Sleeping somewhere and living somewhere are different things." Start by deciding what goes in the room.',
    [auto('craft', '방에 둘 것을 하나 만든다', 'Make one thing to put in the room'),
      man('furnish', '집에 가구를 하나 배치한다', 'Place one piece of furniture at home'),
      talk('ha_nui', '방을 보여 준다', 'Show her the room')],
    ['N22-1'], { teaches: ['living'] }],
  ['N22-3', 'N22', 3, 66, 3400, 'ha_nui', POH, '돌을 고르다', 'Picking Stone',
    '봉돌을 살 돈이 아까우면 직접 고르면 된다. 어디를 깨야 나오는지는 따로 배우는 것이다.',
    'If sinkers cost too much, pick your own. Where to break the rock is a separate lesson.',
    [auto('gather', '갯가에서 봉돌로 쓸 돌을 줍는다 3회', 'Pick sinker stones off the shore, three times', { target: 3 }),
      man('mine', '채석 자리에서 돌을 캔다', 'Quarry stone at the seam'),
      talk('ha_nui', '고른 돌을 본다', 'Show her what you picked')],
    ['N22-2'], { teaches: ['mining'] }],
  ['N22-4', 'N22', 5, 126, 9250, 'ha_nui', JEJ, '한 이랑', 'One Furrow',
    '"밑밥 재료를 매번 사 오실 거예요?" 옥수수 한 이랑이면 한 철은 간다.',
    '"Are you going to buy chum ingredients forever?" One furrow of corn lasts a season.',
    [auto('gather', '밑밥 재료를 직접 모은다 4회', 'Gather your own chum ingredients, four times', { target: 4 }),
      man('farm', '텃밭에 한 이랑을 심는다', 'Plant one furrow'),
      talk('ha_nui', '심은 것을 확인한다', 'Check what you planted')],
    ['N22-3'], { teaches: ['farming'] }],
  ['N22-5', 'N22', 5, 136, 9250, 'ha_nui', JEJ, '창가의 수조', 'The Tank by the Window',
    '관상 수조는 팔 것도, 먹을 것도 아니다. 그냥 두고 보는 것이다.',
    'An ornamental tank is not for selling or eating. It is for looking at.',
    [auto('craft', '수조 받침을 만든다', 'Make a stand for the tank'),
      fish(undefined, '수조에 넣어 둘 한 마리', 'One fish to keep in it'),
      man('furnish', '집에 수조를 놓는다', 'Install a tank at home'),
      talk('ha_nui', '무엇을 넣을지 정한다', 'Decide what goes in it')],
    ['N22-4'], { teaches: ['living'] }],
  ['N22-6', 'N22', 6, 168, 16350, 'ha_nui', INC, '광맥', 'The Seam',
    '인천 쪽 폐채석장에 쓸 만한 게 남았다는 말이 있다.',
    'Word is the old quarry near Incheon still has something worth taking.',
    [auto('gather', '폐채석장 주변에서 채집 3회', 'Forage the old quarry three times', { target: 3 }),
      man('mine', '폐채석장에서 광물을 캔다', 'Mine the abandoned quarry'),
      talk('ha_nui', '캔 것을 나눈다', 'Split what you found')],
    ['N22-5'], { teaches: ['mining'] }],
  ['N22-7', 'N22', 7, 186, 40200, 'ha_nui', DOK, '씨앗', 'Seeds',
    '하늬가 씨앗 봉투를 건넨다. "심을 데는 알아서 찾으세요."',
    'Ha-nui hands over a seed packet. "Find your own ground to put them in."',
    [auto('gather', '심을 자리를 찾아 4회 훑는다', 'Comb four times for ground to plant in', { target: 4 }),
      man('farm', '받은 씨앗을 심는다', 'Plant the seeds you were given'),
      talk('ha_nui', '수확을 약속한다', 'Promise her the harvest')],
    ['N22-6'], { teaches: ['farming'] }],
  ['N22-8', 'N22', 7, 196, 40200, 'ha_nui', DOK, '집', 'A House',
    '처음 왔을 때는 잠만 자던 방이었다. 이제는 돌아올 곳이 됐다.',
    'It was a room you only slept in. Now it is somewhere to come back to.',
    [auto('craft', '집을 마무리할 세간 5점을 만든다', 'Make five furnishings to finish the house', { target: 5 }),
      man('furnish', '집을 마무리한다', 'Finish the house'),
      talk('ha_nui', '집들이를 한다', 'Have her over')],
    ['N22-7'], { teaches: ['living', 'homeBase'] }],
]);


// ─────────────────────────────────────────────
// 141차 — 발주 정책(once / event) 후처리. 행 형식이 3종이라 조립 뒤에 입힌다.
// ─────────────────────────────────────────────
const OFFER_POLICY: Record<string, Pick<StoryQuestDef, 'offerPolicy' | 'event'>> = {
  'N12-1': { offerPolicy: 'once' },
  'N20-1': { offerPolicy: 'once' },
  'N15-1': { offerPolicy: 'once' },
  'N05-1': { offerPolicy: 'once' },
  'N13-1': { offerPolicy: 'once' },
  'N04-2': { offerPolicy: 'event', event: { seasons: ['winter'], cooldownDays: 20 } },
  'N21-2': { offerPolicy: 'event', event: { seasons: ['summer'], cooldownDays: 15 } },
  'N21-4': { offerPolicy: 'event', event: { seasons: ['summer', 'autumn'], cooldownDays: 15 } },
  'N21-5': { offerPolicy: 'event', event: { seasons: ['summer', 'autumn'], cooldownDays: 20 } },
  'N21-6': { offerPolicy: 'event', event: { seasons: ['autumn'], cooldownDays: 20 } },
  'N17-1': { offerPolicy: 'event', event: { levelBand: [138, 160], cooldownDays: 7 } },
  'N06-3': { offerPolicy: 'event', event: { seasons: ['summer', 'autumn'], cooldownDays: 10 } },
  'N16-1': { offerPolicy: 'event', event: { levelBand: [132, 150], cooldownDays: 10 } },
  'N23-1': { offerPolicy: 'event', event: { seasons: ['summer', 'autumn'], cooldownDays: 30 } },
};
for (const q of [...MAIN, ...SUB, ...SUB_EXTRA, ...SUB_138]) { const p = OFFER_POLICY[q.id]; if (p) Object.assign(q, p); }

export const STORY_QUESTS: StoryQuestDef[] = [...MAIN, ...SUB, ...SUB_EXTRA, ...SUB_138];

const BY_ID = new Map(STORY_QUESTS.map((q) => [q.id, q]));
export function getStoryQuest(id: string): StoryQuestDef | undefined { return BY_ID.get(id); }
export function storyQuestsOfChapter(ch: number, kind?: 'main' | 'sub'): StoryQuestDef[] {
  return STORY_QUESTS.filter((q) => q.chapter === ch && (!kind || q.kind === kind));
}
/** 챕터의 마지막 메인 퀘 — 다음 챕터 해금 키 */
export function lastMainQuestOfChapter(ch: number): StoryQuestDef | undefined {
  const list = storyQuestsOfChapter(ch, 'main');
  return list[list.length - 1];
}

/**
 * 무결성 검사 — §8-1 수치 계약(챕터별 수·XP 합계) · id 유일 · prereq 존재 · 조행록 17장 커버.
 * 문제 없으면 빈 배열. dev 부팅 시 `console.warn`으로 노출한다(client).
 */
export function validateStoryQuests(): string[] {
  const issues: string[] = [];
  const ids = new Set<string>();
  for (const q of STORY_QUESTS) {
    if (ids.has(q.id)) issues.push(`중복 id ${q.id}`);
    ids.add(q.id);
    for (const p of q.prereq) if (!BY_ID.has(p)) issues.push(`${q.id}: prereq ${p} 없음`);
    if (q.objectives.length === 0) issues.push(`${q.id}: 목표 없음`);
  }
  for (const c of STORY_CHAPTERS) {
    const m = storyQuestsOfChapter(c.chapter, 'main'), s = storyQuestsOfChapter(c.chapter, 'sub');
    const mx = m.reduce((a, q) => a + q.xp, 0), sx = s.reduce((a, q) => a + q.xp, 0);
    if (m.length !== c.contract.mainCount) issues.push(`Ch${c.chapter} 메인 수 ${m.length} ≠ ${c.contract.mainCount}`);
    if (mx !== c.contract.mainXp) issues.push(`Ch${c.chapter} 메인 XP ${mx} ≠ ${c.contract.mainXp}`);
    if (s.length !== c.contract.subCount) issues.push(`Ch${c.chapter} 서브 수 ${s.length} ≠ ${c.contract.subCount}`);
    if (sx !== c.contract.subXp) issues.push(`Ch${c.chapter} 서브 XP ${sx} ≠ ${c.contract.subXp}`);
  }
  // 141차 — 보상 스키마: 귀속 장비는 메인 전용 · 기술 해금은 메인 전용 · 서브는 items를 귀속으로 주지 않는다(겹침 금지)
  for (const q of STORY_QUESTS) {
    const r = q.rewards;
    if (!r) continue;
    if (q.kind === 'sub' && (r.skillUnlocks?.length || r.shopUnlocks?.length)) issues.push(`${q.id}: 서브 퀘는 기술·상점 해금을 줄 수 없다(메인 전용)`);
    if (q.kind === 'sub' && r.items?.some((i) => i.bound)) issues.push(`${q.id}: 서브 퀘는 귀속 장비를 줄 수 없다(메인 전용)`);
    if (q.kind === 'main' && r.items?.some((i) => !i.bound && i.id.startsWith('qr_'))) issues.push(`${q.id}: 메인 보상 장비(qr_)는 귀속이어야 한다`);
  }
  for (const q of STORY_QUESTS) {
    if (q.offerPolicy === 'event' && !q.event) issues.push(`${q.id}: event 정책인데 시기 조건이 없다`);
    if (q.event?.levelBand && q.event.levelBand[0] > q.event.levelBand[1]) issues.push(`${q.id}: levelBand 역순`);
  }
  const pages = new Set(STORY_QUESTS.filter((q) => q.journalPage).map((q) => q.journalPage));
  for (let p = 1; p <= 17; p++) if (!pages.has(p)) issues.push(`조행록 ${p}장을 채우는 퀘스트 없음`);
  return issues;
}
