/**
 * @file StoryQuestDatabase.ts
 * @description 메인 「조행록」 65퀘 + NPC 17아크 55퀘 = 120퀘 (134차, STORY_SPEC_v3 §9·§10·§12)
 *
 * - id: 메인 `M{챕터}-{번호}` · 서브 `N{아크}-{번호}` (스펙 표기 그대로).
 * - xp: 스펙 표 값 그대로 — `validateStoryQuests()`가 챕터별 수·합계를 `STORY_CHAPTERS.contract`와 대조한다.
 * - objectives: 자동 추적기가 있는 종류(catch/release/craft/butcher/sashimi/license/gather/trap/visit/reachLevel/
 *   earn/sell/custom-이벤트)는 client 훅이 채우고, `manual: true`는 대화 패널 [완료]로 닫는다(§0.5-7).
 * - 지역 id는 WorldMap `RegionDef.id`. 하위 권역은 `JournalPages.areaKey`에만 있다.
 *
 * ⚠ 어종 id 대체(§0.5): 임연수어→도루묵 · 호래기→볼락 · 지세포 볼락→광어 · 주꾸미→갑오징어 · 돗돔→대구.
 */

import type { StoryObjective, StoryQuestDef, Season } from '../types/Story.js';
import { STORY_CHAPTERS } from './StoryChapters.js';

// ── 헬퍼 ──
const talk = (npcId: string, ko: string, en: string): StoryObjective => ({ kind: 'talk', npcId, labelKo: ko, labelEn: en, manual: true });
const man = (kind: StoryObjective['kind'], ko: string, en: string, extra: Partial<StoryObjective> = {}): StoryObjective => ({ kind, labelKo: ko, labelEn: en, manual: true, ...extra });
const auto = (kind: StoryObjective['kind'], ko: string, en: string, extra: Partial<StoryObjective> = {}): StoryObjective => ({ kind, labelKo: ko, labelEn: en, ...extra });
const fish = (speciesId: string | undefined, ko: string, en: string, extra: Partial<StoryObjective> = {}): StoryObjective =>
  ({ kind: 'catch', speciesId, selfCaught: true, target: 1, labelKo: ko, labelEn: en, ...extra });
const W: Season[] = ['winter']; const SU: Season[] = ['summer']; const AU: Season[] = ['autumn'];

const SOK = 'gangwon_sokcho', BUS = 'busan', ULS = 'ulsan', POH = 'gyeongbuk_pohang', GEO = 'gyeongnam_geoje',
  YEO = 'jeonnam_yeosu', TAE = 'chungnam_taean', JEJ = 'jeju', ULL = 'ulleungdo', INC = 'incheon', DOK = 'dokdo';

type MainRow = [id: string, ch: 1|2|3|4|5|6|7, lv: number, xp: number, giver: string, region: string,
  titleKo: string, titleEn: string, descKo: string, descEn: string, objectives: StoryObjective[], extra?: Partial<StoryQuestDef>];
const PART_OF: Record<number, 1|2|3|4|5> = { 1: 1, 2: 2, 3: 3, 4: 3, 5: 4, 6: 5, 7: 5 };

function mainRows(rows: MainRow[]): StoryQuestDef[] {
  const out: StoryQuestDef[] = [];
  rows.forEach((r, i) => {
    const [id, chapter, minLevel, xp, giver, region, titleKo, titleEn, descKo, descEn, objectives, extra] = r;
    const prev = i > 0 ? rows[i - 1][0] : null;
    out.push({ id, kind: 'main', part: PART_OF[chapter], chapter, titleKo, titleEn, descKo, descEn, minLevel, xp, giver, region,
      prereq: prev ? [prev] : [], objectives, ...extra });
  });
  return out;
}

// ─────────────────────────────────────────────
// 제1부 「실습생」 — Ch1 속초 · 11퀘 · 4,400 XP (튜토리얼 전담)
// ─────────────────────────────────────────────
const MAIN: StoryQuestDef[] = mainRows([
  ['M1-01', 1, 1, 240, '', SOK, '막차', 'The Last Bus',
    '산골집 문을 잠그고 돌아보지 않는다. 종점은 영금정 — 22년 전 가족사진과 같은 자리.',
    'You lock the mountain house and don\'t look back. The last stop is Yeonggeumjeong — the same spot as the family photo, 22 years ago.',
    [auto('visit', '영금정에 도착한다', 'Arrive at Yeonggeumjeong', { placeKey: 'poi:yeonggeumjeong' })],
    { teaches: ['movement', 'inventory', 'statusPanel', 'worldMap'] }],
  ['M1-02', 1, 2, 270, 'okseon', SOK, '얼음 나르기', 'Hauling Ice',
    '"울 거면 얼음부터 나르고 울어." 좌판 할머니가 동정 대신 일을 준다. 첫 품삯이 기본 재화다.',
    '"If you\'re going to cry, haul the ice first." The stall grandmother gives you work instead of pity. Your first wages.',
    [man('custom', '만복상회 얼음 나르기 (대화로 진행)', 'Haul ice for Manbok Store (through dialogue)'),
      auto('visit', '직판장 상점을 열어 본다', 'Open the market shop', { placeKey: 'shop:any' })],
    { teaches: ['wages', 'shop'], rewards: { coins: 30000 }, reputation: { harbor: { gangwon_sokcho: 2 } } }],
  ['M1-03', 1, 3, 300, 'okseon', SOK, '열쇠 두 개', 'Two Keys',
    '좌판 뒤 옛 어촌계 숙소. 먼지와 곰팡내. 실습생 증을 받는 순간 D-180이 시작된다.',
    'The old co-op lodging behind the stall — dust and mildew. The moment you take the trainee card, D-180 begins.',
    [auto('visit', '홈타운(숙소)에 들어간다', 'Enter the hometown lodging', { placeKey: 'region:hometown' }),
      auto('custom', '침대에서 저장하고 쉰다', 'Save and rest in the bed', { placeKey: 'bedSave' })],
    { teaches: ['homeBase', 'save', 'placement', 'deadline'], deadline: { days: 180, onMiss: 'cost' }, unlocks: ['trainee'] }],
  ['M1-04', 1, 4, 330, 'hyeonsu', SOK, '사이소 영수증', 'The Saiso Receipt',
    '라이벌의 첫 시비 겸 첫 강습. "그 대는 아까우니까 여기다 쓰지 마." 저가 장비로 테트라포드 구멍치기.',
    'The rival\'s first jab and first lesson. "Don\'t waste that rod here." Budget gear, hole fishing in the tetrapods.',
    [man('custom', '생활용품점 저가 장비 갖추기 (사이소 — 준비 중, 대화로 완료)', 'Kit out with budget gear (Saiso — coming soon, complete via dialogue)'),
      fish(undefined, '방파제에서 물고기 1마리 낚기', 'Catch one fish at the breakwater')],
    { teaches: ['budgetGear', 'holeFishing', 'tetrapodSafety'] }],
  ['M1-05', 1, 5, 360, 'hyeonsu', SOK, '첫 캐스팅', 'First Cast',
    '아버지의 릴대를 처음 편다. 캐스팅 · 찌 채비 · 입질 → 챔질 → 파이팅 → 랜딩 전 구간.',
    'You extend your father\'s rod for the first time. Casting, the float rig, bite → hookset → fight → landing.',
    [fish(undefined, '캐스팅으로 물고기 2마리 낚기', 'Catch two fish by casting', { target: 2 })],
    { teaches: ['casting', 'floatRig', 'bite', 'fight'] }],
  ['M1-06', 1, 7, 390, 'okseon', SOK, '팔 수 없는 물고기', 'The Fish You Cannot Sell',
    '"네가 잡은 건 네가 먹어라. 그게 법이다. 계원이 돼도 낚싯대로 잡은 건 못 판다." 법 규칙 5조 · 준법 방생.',
    '"What you catch, you eat. That is the law. Even as a member, rod-caught fish cannot be sold." The five rules · lawful release.',
    [auto('release', '금지체장·금어기 개체를 준법 방생한다', 'Lawfully release an undersized or closed-season fish'),
      talk('okseon', '정옥선에게 법 규칙을 듣는다', 'Hear the rules from Ok-seon')],
    { teaches: ['law', 'measure', 'release', 'codex'], reputation: { sea: 1 } }],
  ['M1-07', 1, 9, 420, 'okseon', SOK, '부엌의 순서', 'The Order of the Kitchen',
    '2년 만에 제대로 된 밥. 손질 → 회뜨기 → 신선도·보관 → 요리.',
    'The first proper meal in two years. Butchery → sashimi → freshness → cooking.',
    [auto('butcher', '원물 1마리 손질', 'Butcher one whole fish'),
      auto('sashimi', '회뜨기 1회', 'Slice sashimi once')],
    { teaches: ['butchery', 'sashimi', 'freshness', 'cooking'] }],
  ['M1-08', 1, 11, 450, 'tak_mansu', SOK, '간이 백팩', 'The Improvised Backpack',
    '죽간 장인의 첫 교습. "짐부터 어떻게 좀 해라." 제작대 · 도면 · 핸드크래프팅.',
    'The bamboo-rod master\'s first lesson. "Sort your baggage out first." Workbench, blueprints, hand-crafting.',
    [auto('craft', 'U 창 제작 탭에서 도면 1개 제작', 'Craft one blueprint in the U window'),
      man('custom', '간이 백팩 착용 (가방 사다리 — 준비 중)', 'Equip the improvised backpack (bag ladder — coming soon)')],
    { teaches: ['crafting', 'backpack'] }],
  ['M1-09', 1, 13, 480, 'okseon', SOK, '밤바다', 'Night Sea',
    '물때표를 처음 스스로 읽는다. 간조 · 허용 어구 · 마을어업권 · 헤드랜턴 · 오한 · 응급처치.',
    'You read the tide table yourself for the first time. Low tide, permitted gear, village fishery, headlamp, chill, first aid.',
    [auto('gather', '해루질로 2개체 채집', 'Gather two creatures on the tideland', { target: 2 })],
    { teaches: ['tideland', 'tideTable', 'lantern', 'cold', 'firstAid', 'villageFishery'] }],
  ['M1-10', 1, 16, 520, 'coop', SOK, '공동작업', 'Community Work',
    '이름이 아니라 "실습생"으로 불린다. 양망 보조 · 미역 정리 · 자전거 수리·탑승 · 스킬 포인트 첫 투자.',
    'They call you "trainee", not by name. Net hauling, seaweed sorting, fixing and riding the bicycle, your first skill point.',
    [man('communityWork', '어촌계 공동작업 1회 참여 (대화로 완료)', 'Take part in one community work session (via dialogue)'),
      auto('custom', '자전거에 탑승한다', 'Ride the bicycle', { placeKey: 'bikeMount' })],
    { teaches: ['communityWork', 'bicycle', 'skills', 'reputation'], rewards: { coins: 50000 }, reputation: { harbor: { gangwon_sokcho: 3 } } }],
  ['M1-11', 1, 18, 640, 'coop', SOK, '총회', 'The General Meeting',
    'D-11에 통과. 서류 4종 → 신고어업 등록 → 예비계원 → 어촌계원 승낙. 처음으로 이름이 불린다.',
    'Passed at D-11. Four documents → reported fishery → candidate → accepted as a member. The first time they say your name.',
    [auto('reachLevel', '레벨 18 도달', 'Reach level 18', { target: 18 }),
      talk('coop', '어촌계 총회에 선다', 'Stand before the general meeting')],
    { teaches: ['licenseFlow', 'auction'], rewards: { licenses: ['reported_fishery', 'coop_member'] }, unlocks: ['region:busan', 'auction'],
      reputation: { harbor: { gangwon_sokcho: 5 } } }],

  // ─────────────────────────────────────────────
  // 제2부 「위판」 — Ch2 부산 · 10퀘 · 29,500
  // ─────────────────────────────────────────────
  ['M2-01', 2, 20, 1750, 'coop', BUS, '첫 위판', 'First Auction',
    '내 이름이 붙은 첫 상자. 위판 등록 · 상자 규격 · 등급 판정 — 통발 어획물로 §3 규칙 실전 적용.',
    'The first crate with your name on it. Auction registration, crate grades — the rules applied for real, with trap catch.',
    [auto('trap', '통발 1회 수거', 'Harvest one trap'), man('sell', '통발 어획물 위판 (위판 UI — 준비 중)', 'Auction the trap catch (auction UI — coming soon)')]],
  ['M2-02', 2, 22, 2000, 'coop', BUS, '유찰', 'Unsold',
    '얼음을 아낀 대가. 경매 유찰 · 선도 관리 복기.',
    'The price of saving on ice. An unsold lot, and a freshness post-mortem.',
    [man('custom', '유찰 복기 — 쿨러 얼음 관리 (대화로 완료)', 'Post-mortem — cooler ice management (via dialogue)')]],
  ['M2-03', 2, 24, 2250, 'hyeonsu', BUS, '감천항의 겨울', 'Winter at Gamcheon',
    '밑걸림 · 채비 유실 · 회수. 감성돔 40cm 이상.',
    'Snags, lost rigs, recovery. A black seabream over 40 cm.',
    [fish('black_seabream', '감성돔 40cm+ 자가어획 (겨울)', 'Catch a black seabream 40 cm+ (winter)', { minCm: 40, season: W })],
    { journalPage: 2 }],
  ['M2-04', 2, 27, 2500, 'na_gibeom', BUS, '남의 가게', 'Someone Else\'s Shop',
    '횟집 사장은 값이 아니라 꾸준함을 산다. 납품 계약 · 단가 · 신용.',
    'The restaurant owner buys consistency, not price. Contracts, unit prices, credit.',
    [man('deliverFree', '횟집에 통발 어획물 3회 납품 (납품 계약 — 준비 중)', 'Deliver trap catch to a restaurant 3 times (contracts — coming soon)', { target: 3 })]],
  ['M2-05', 2, 30, 2750, 'coop', BUS, '품질관리 교육', 'Quality Control Course',
    '교실에서 도현수와 나란히. 위생 · 이력 표기 · 루어 개방.',
    'In the classroom, next to Hyeon-su. Hygiene, traceability, lures unlocked.',
    [man('custom', '수산물 품질관리 교육 이수 (대화로 완료)', 'Complete the seafood quality course (via dialogue)')],
    { unlocks: ['lure'], teaches: ['lure'] }],
  ['M2-06', 2, 33, 3000, 'seo_harin', BUS, '암남공원의 밤', 'Night at Amnam Park',
    '야간 루어 전갱이 · 통발 제작.',
    'Night lure for horse mackerel · trap crafting.',
    [fish('horse_mackerel', '전갱이 자가어획 (겨울 야간)', 'Catch a horse mackerel (winter night)', { season: W }),
      auto('craft', '통발 1개 제작', 'Craft one trap')],
    { journalPage: 3 }],
  ['M2-07', 2, 36, 3250, 'coop', BUS, '통제선', 'The Control Line',
    '방파제 출입통제 → 합법 우회 3종(어촌계 동행 · 낚시공원 입장 · 선상). 몰래 넘는 선택지는 없다.',
    'The breakwater is closed → three legal ways round (co-op escort, fishing park, boat). Sneaking over is not an option.',
    [man('custom', '합법 우회 경로 1개 선택 (대화로 완료)', 'Choose one legal route (via dialogue)')],
    { reputation: { sea: 1 } }],
  ['M2-08', 2, 39, 3500, 'jim_kang', BUS, '백운포의 볼락', 'Rockfish at Baegunpo',
    '야간 소형 어종 · 집어등. 볼락 3마리.',
    'Small fish at night under lights. Three rockfish.',
    [fish('dark_banded_rockfish', '볼락 3마리 자가어획 (겨울 야간)', 'Catch three rockfish (winter night)', { target: 3, season: W })],
    { journalPage: 4 }],
  ['M2-09', 2, 42, 3800, 'coop', BUS, '총회', 'The General Meeting',
    '계원 지위 심사 · 항구 신뢰 반영. 도현수가 반대표를 던진다. 그래도 통과.',
    'Membership review, harbour trust counts. Hyeon-su votes against. You pass anyway.',
    [talk('coop', '분기 총회에 선다', 'Stand at the quarterly meeting')],
    { reputation: { harbor: { busan: 5 } } }],
  ['M2-10', 2, 44, 4700, 'coop', BUS, '면허 학원', 'Licence School',
    '"배를 몰 줄 알아야 겨울 바다를 안다." 선박조종면허 필기 · 울산·포항 개방.',
    '"You don\'t know the winter sea until you can pilot a boat." Written exam · Ulsan and Pohang open.',
    [man('custom', '선박조종면허 필기 합격 (대화로 완료)', 'Pass the written vessel exam (via dialogue)')],
    { unlocks: ['region:ulsan', 'region:gyeongbuk_pohang'] }],

  // ─────────────────────────────────────────────
  // 제3부 「겨울 배」 — Ch3 울산·포항 · 9퀘 · 67,950
  // ─────────────────────────────────────────────
  ['M3-01', 3, 45, 4450, 'go_manseok', ULS, '방어진 입항', 'Into Bangeojin',
    '남의 배에 얹혀 배우는 마지막 시기. 배 출조 파이프라인 전 구간.',
    'The last time you learn on someone else\'s boat. The whole boat-trip pipeline.',
    [man('boatTrip', '고래마루 승선 1회 (배 출조 — 준비 중)', 'One trip aboard the Goraemaru (boat trips — coming soon)')],
    { teaches: ['boatTrip', 'seasickness'] }],
  ['M3-02', 3, 48, 5150, 'go_manseok', ULS, '지깅', 'Jigging',
    '저킹 · 폴링 · 고속 콤보. 방어 40cm 이상.',
    'Jerking, falling, fast combos. A yellowtail over 40 cm.',
    [fish('yellowtail', '방어 40cm+ 자가어획 (겨울)', 'Catch a yellowtail 40 cm+ (winter)', { minCm: 40, season: W })],
    { journalPage: 5, teaches: ['jigging'] }],
  ['M3-03', 3, 52, 5900, 'coop', ULS, '실기 시험', 'The Practical',
    '계류 · 변침 · 인명구조. 한 번 떨어져도 된다.',
    'Mooring, course change, rescue. Failing once is allowed.',
    [man('license', '소형선박조종사 실기 합격 (대화로 완료)', 'Pass the small-vessel practical (via dialogue)', { licenseId: 'boat_operator' })],
    { rewards: { licenses: ['boat_operator'] } }],
  ['M3-04', 3, 55, 6650, 'baram', POH, '덕장', 'The Drying Racks',
    '청어가 안 든다. 건조 · 숙성 제작.',
    'The herring aren\'t coming. Drying and curing.',
    [man('craft', '건조·숙성 제작 1회 (불요리 — 준비 중)', 'One drying/curing craft (fire cooking — coming soon)')]],
  ['M3-05', 3, 58, 7400, 'go_manseok', ULS, '해무', 'Sea Fog',
    '무리하지 않고 돌아오는 것도 실력. 기상 이벤트 생존 · 귀항 판단.',
    'Turning back without pushing it is a skill too. Weather event, the call to return.',
    [man('survive', '해무 귀항 판단 (대화로 완료)', 'Make the sea-fog return call (via dialogue)')],
    { teaches: ['weather'] }],
  ['M3-06', 3, 61, 8100, 'okseon', POH, '명태를 본 적 있어요?', 'Have You Ever Seen a Pollock?',
    '노인들의 기억을 받아 적는다. 조행록의 용도를 처음 이해한다. 도감 "포획 금지" 상태.',
    'You write down the old men\'s memories. You understand what the log is for. A "no take" codex entry.',
    [man('custom', '구술 채록 3건 (미니 시스템 — 준비 중)', 'Three oral-history entries (mini system — coming soon)', { target: 3 })],
    { teaches: ['oralHistory'] }],
  ['M3-07', 3, 64, 8850, 'coop', POH, '종묘방류', 'Restocking',
    '자원 회복 이벤트 · 치어 보호. 바다 평판 대폭 상승.',
    'A restocking event, protecting fry. Sea reputation climbs.',
    [man('communityWork', '종묘방류 참여 (대화로 완료)', 'Join the restocking (via dialogue)')],
    { reputation: { sea: 3 }, teaches: ['restocking'] }],
  ['M3-08', 3, 67, 9600, 'go_manseok', POH, '겨울 참돔', 'Winter Red Seabream',
    '타이라바 · 대물 파이팅 · 장비 한계. 유품 릴대가 부러진다.',
    'Tai-rubber, a big fight, the limit of the gear. Your father\'s rod breaks.',
    [fish('red_seabream', '참돔 자가어획 (봄·가을 새벽/저녁)', 'Catch a red seabream (spring/autumn dawn or dusk)', { season: ['spring', 'autumn'] })],
    { journalPage: 6, unlocks: ['rodBroken'] }],
  ['M3-09', 3, 69, 11850, 'tak_mansu', POH, '배를 보러 가자', 'Let\'s Go See a Boat',
    '중고 선박 시세 · 거제 개방. 탁 노인이 새 죽간을 건넨다.',
    'Used-boat prices, Geoje opens. Old Tak hands you a new bamboo rod.',
    [talk('tak_mansu', '탁만수에게 새 죽간을 받는다', 'Receive the new rod from Tak Man-su')],
    { unlocks: ['region:gyeongnam_geoje', 'region:jeonnam_yeosu', 'region:chungnam_taean'] }],

  // ─────────────────────────────────────────────
  // 제3부 「내 배」 — Ch4 거제·여수·태안 · 10퀘 · 147,000
  // ─────────────────────────────────────────────
  ['M4-01', 4, 70, 8700, 'chae_geumja', GEO, '지세포 조선소', 'Jisepo Shipyard',
    '돈이 모자라 절반만 고친다. 선체 검수 · 수리 견적.',
    'Not enough money — you fix half. Hull inspection, repair estimate.',
    [auto('earn', '재화 5,000,000원 보유', 'Hold 5,000,000 won', { target: 5_000_000 })]],
  ['M4-02', 4, 73, 9950, 'chae_geumja', GEO, '첫 배', 'First Boat',
    '이름을 직접 정한다. 보트 운항 개방.',
    'You name it yourself. Boat operation unlocked.',
    [man('boatTrip', '자기 배 첫 운항 (보트 운항 — 준비 중)', 'First run in your own boat (boat piloting — coming soon)')],
    { teaches: ['boatOwnership'], unlocks: ['ownBoat'] }],
  ['M4-03', 4, 76, 11200, 'chae_pado', GEO, '지세포의 밤', 'Night at Jisepo',
    '야간 루어 · 소형 등선. 광어(다운샷).',
    'Night lure from a small lit boat. Flatfish on a downshot.',
    [fish('flatfish', '광어 자가어획 (봄·가을 주간)', 'Catch a flatfish (spring/autumn daytime)', { season: ['spring', 'autumn'] })],
    { journalPage: 7 }],
  ['M4-04', 4, 80, 12500, 'coop', GEO, '안전 검사', 'Safety Inspection',
    '구명장비 · 검사 체크리스트. 한 항목 미달로 재검사.',
    'Life-saving gear, the checklist. One item short — re-inspection.',
    [man('custom', '선박 안전 검사 통과 (대화로 완료)', 'Pass the vessel safety inspection (via dialogue)')]],
  ['M4-05', 4, 84, 13750, 'oh_gayun', YEO, '밤바다 갈치', 'Hairtail at Night',
    '야간 원정 · 집어등. 갈치.',
    'A night expedition under lights. Hairtail.',
    [fish('hairtail', '갈치 자가어획 (초여름~가을 야간)', 'Catch a hairtail (summer–autumn night)', { season: ['summer', 'autumn'] })],
    { journalPage: 9 }],
  ['M4-06', 4, 87, 15050, 'coop', GEO, '첫 손님', 'First Passenger',
    '낚시어선업 신고 완료 · 승선 명부 · 안전교육 · 멀미 대응. 손님이 드러눕는다.',
    'Angling-boat business registered. Passenger list, safety briefing, seasickness. The guest keels over.',
    [man('boatTrip', '첫 손님 승선 출조 (낚시어선업 — 준비 중)', 'First paid passenger trip (angling-boat business — coming soon)')],
    { rewards: { licenses: ['angling_boat_biz'] } }],
  ['M4-07', 4, 90, 16300, 'song_gibaek', TAE, '서해로', 'To the West Sea',
    '동해와 정반대의 바다. 조수간만 대차 · 갯벌 보행.',
    'The opposite of the East Sea. Big tidal range, walking the mudflats.',
    [auto('visit', '태안에 도착한다', 'Arrive in Taean', { placeKey: 'region:chungnam_taean' }),
      auto('gather', '갯벌 채집 3개체', 'Gather three creatures on the flats', { target: 3 })]],
  ['M4-08', 4, 93, 17550, 'tak_saebyeok', TAE, '만리포 서프', 'Mallipo Surf',
    '서프 루어 · 포말대 야간 보너스. 농어.',
    'Surf lure, surf-zone night bonus. Sea bass.',
    [fish('sea_bass', '농어 자가어획 (봄~여름 포말대 야간)', 'Catch a sea bass (spring–summer surf-zone night)', { season: ['spring', 'summer'] })],
    { journalPage: 11, teaches: ['surf'] }],
  ['M4-09', 4, 96, 18850, 'ma_gamgi', TAE, '갑오징어', 'Cuttlefish',
    '에깅 계열 개방. 가을 주간 갑오징어.',
    'Egging unlocked. Autumn daytime cuttlefish.',
    [fish('cuttlefish', '갑오징어 자가어획 (가을 주간)', 'Catch a cuttlefish (autumn daytime)', { season: AU })],
    { journalPage: 10, teaches: ['egging'] }],
  ['M4-10', 4, 99, 23150, 'hyeonsu', TAE, '제주 항로', 'The Jeju Route',
    '장거리 항해 준비 · 연료 · 기상. 도현수가 처음 배를 타러 온다.',
    'Preparing a long voyage — fuel, weather. Hyeon-su comes aboard for the first time.',
    [talk('hyeonsu', '도현수와 함께 출항 준비', 'Prepare to sail with Hyeon-su')],
    { unlocks: ['region:jeju'] }],

  // ─────────────────────────────────────────────
  // 제4부 「손님」 — Ch5 제주 · 9퀘 · 230,850
  // ─────────────────────────────────────────────
  ['M5-01', 5, 100, 15050, 'coop', JEJ, '운진항', 'Unjin Port',
    '타지 입항 절차 · 항비. 제주 방언 · 지역 규칙.',
    'Entering a foreign port — fees, dialect, local rules.',
    [auto('visit', '제주에 도착한다', 'Arrive in Jeju', { placeKey: 'region:jeju' })]],
  ['M5-02', 5, 103, 17550, 'baram', JEJ, '불턱', 'The Bulteok',
    '남의 바다에 들어갈 때의 예의. 마을어업권 실전 · 잠수 채집.',
    'Manners for entering someone else\'s sea. Village fishery for real, dive gathering.',
    [auto('gather', '마을어업권 밖에서 3개체 채집', 'Gather three creatures outside the village fishery', { target: 3 })],
    { teaches: ['villageFishery'], reputation: { sea: 1 } }],
  ['M5-03', 5, 107, 20050, 'oh_serin', JEJ, '도두항 한치', 'Swordtip Squid at Dodu',
    '야간 집어 · 한치 3마리.',
    'Night lights, three swordtip squid.',
    [fish('swordtip_squid', '한치 3마리 자가어획 (여름 야간)', 'Catch three swordtip squid (summer night)', { target: 3, season: SU })],
    { journalPage: 12 }],
  ['M5-04', 5, 111, 22600, 'coop', JEJ, '해양관광업 등록', 'Marine Tourism Registration',
    '손님을 받는 쪽이 된다. 가이드 영업 루프.',
    'Now you are the one taking guests. The guide loop.',
    [man('custom', '해양관광업 등록 + 안전교육 (대화로 완료)', 'Register and take the safety course (via dialogue)')],
    { rewards: { licenses: ['marine_tourism'] }, teaches: ['guideBusiness'] }],
  ['M5-05', 5, 115, 25100, 'yu_ria', JEJ, '낚시공원 설명회', 'The Fishing Park Briefing',
    '찬반 양측 취재. 두 입장 모두 타당하게.',
    'Interview both sides. Both are right.',
    [talk('yu_ria', '찬성 측 취재', 'Interview the "for" side'), talk('coop', '반대 측 취재', 'Interview the "against" side')]],
  ['M5-06', 5, 119, 27600, 'namgung_hyeon', JEJ, '대회 예선', 'Tournament Qualifier',
    '참가비 · 순위 상금 · 계측 규정.',
    'Entry fee, prize ladder, measuring rules.',
    [fish(undefined, '예선 계측 어획 3마리', 'Three measured fish for the qualifier', { target: 3 })],
    { teaches: ['tournament'] }],
  ['M5-07', 5, 122, 30100, 'mara', JEJ, '서귀포 에깅', 'Seogwipo Egging',
    '무늬오징어 에깅 심화.',
    'Advanced egging for bigfin reef squid.',
    [fish('squid', '무늬오징어 자가어획 (가을 야간 얕은 곳)', 'Catch a bigfin reef squid (autumn night shallows)', { season: AU })],
    { journalPage: 14 }],
  ['M5-08', 5, 126, 32600, 'namgung_hyeon', JEJ, '결선과 전화 한 통', 'The Final and a Phone Call',
    '대회 결선 · 방어 대물 80cm 이상. 결선 중 정옥선이 쓰러졌다는 연락.',
    'The final — a yellowtail over 80 cm. Mid-final, the call: Ok-seon has collapsed.',
    [fish('yellowtail', '방어 80cm+ 자가어획 (겨울)', 'Catch a yellowtail 80 cm+ (winter)', { minCm: 80, season: W })],
    { journalPage: 13 }],
  ['M5-09', 5, 129, 40200, 'coop', JEJ, '총회 표결', 'The Vote',
    '낚시공원 안건 표결 — 누적 평판 · 참여율 반영. 도현수가 처음 같은 편에 선다.',
    'The fishing-park vote — reputation and participation count. Hyeon-su takes your side for the first time.',
    [talk('coop', '총회 표결에 참석', 'Attend the vote')],
    { unlocks: ['region:ulleungdo', 'region:incheon', 'parkVote'] }],

  // ─────────────────────────────────────────────
  // 제5부 「먼 항로」 — Ch6 울릉·인천 · 8퀘 · 326,800
  // ─────────────────────────────────────────────
  ['M6-01', 6, 130, 23750, 'oh_sera', ULL, '막배', 'The Last Ferry',
    '돌아갈 수 없는 밤. 여객선 결항 확률 · 섬 체류 생존.',
    'A night you cannot go back. Ferry cancellations, surviving on the island.',
    [auto('visit', '울릉도에 도착한다', 'Arrive at Ulleungdo', { placeKey: 'region:ulleungdo' }),
      man('survive', '결항 하룻밤 체류 (대화로 완료)', 'Stay one cancelled night (via dialogue)')],
    { teaches: ['ferry'] }],
  ['M6-02', 6, 134, 28400, 'yeon_taeo', ULL, '부시리', 'Amberjack',
    '파핑 · 대형 청물.',
    'Popping for big pelagics.',
    [fish('amberjack', '부시리 자가어획 (여름~가을)', 'Catch an amberjack (summer–autumn)', { season: ['summer', 'autumn'] })],
    { journalPage: 16 }],
  ['M6-03', 6, 138, 33000, 'seok_daeyang', ULL, '등대', 'The Lighthouse',
    '등대 근무자 교류 · 기상 관측. 석대양 노인이 고진태 선장을 기억한다.',
    'Keeping company with the lighthouse keeper, watching the weather. Old Seok remembers Captain Go.',
    [talk('seok_daeyang', '등대지기와 대화', 'Talk with the lighthouse keeper')]],
  ['M6-04', 6, 142, 37650, 'dan_cheolho', INC, '연안부두', 'Yeonan Pier',
    '인천 개방 · 유통 구조 · 원산지 표기. 우럭 30cm 이상.',
    'Incheon opens — distribution, origin labelling. A rockfish over 30 cm.',
    [fish('black_rockfish', '우럭(조피볼락) 30cm+ 자가어획 (가을 야간)', 'Catch a black rockfish 30 cm+ (autumn night)', { minCm: 30, season: AU })],
    { journalPage: 15 }],
  ['M6-05', 6, 146, 42250, 'okseon', SOK, '병실', 'The Ward',
    '병원 시스템 · 간병 일정이 출조를 압박. 정옥선이 조행록 마지막 권을 건넨다.',
    'Hospital visits squeeze your trips. Ok-seon hands you the last volume of the log.',
    [talk('okseon', '병실의 정옥선을 찾아간다', 'Visit Ok-seon in the ward')],
    { unlocks: ['journalInherited'] }],
  ['M6-06', 6, 150, 46850, 'okseon', SOK, '좌판을 맡다', 'Minding the Stall',
    '그녀의 자리에 처음 앉는다. 좌판 운영 루프(재고 · 손님 · 가격).',
    'You sit in her seat for the first time. Running the stall — stock, customers, prices.',
    [man('custom', '만복상회 좌판 3일 운영 (좌판 운영 — 준비 중)', 'Run Manbok Store for three days (stall ops — coming soon)', { target: 3 })],
    { teaches: ['stallOps'] }],
  ['M6-07', 6, 155, 51500, 'coop', SOK, '항해 계획 승인', 'Voyage Plan Approval',
    '기상 · 정비 · 비상계획 서류. 마지막 자격.',
    'Weather, maintenance, contingency paperwork. The last qualification.',
    [man('custom', '원거리 항해 계획 승인 (대화로 완료)', 'Get the long-range voyage plan approved (via dialogue)')],
    { teaches: ['voyagePlan'] }],
  ['M6-08', 6, 158, 63400, 'coop', SOK, '조사 동행 허가', 'Survey Escort Permit',
    '3중 게이트(Lv160 · 해양관광업 · Ch6 완료). 독도 학술조사단 동행 승인.',
    'Triple gate — Lv160, marine tourism, Ch6 done. Approved to join the Dokdo survey.',
    [auto('reachLevel', '레벨 160 도달', 'Reach level 160', { target: 160 })],
    { unlocks: ['region:dokdo'] }],

  // ─────────────────────────────────────────────
  // 제5부 「조행록」 — Ch7 독도 · 8퀘 · 602,800
  // ─────────────────────────────────────────────
  ['M7-01', 7, 160, 43850, 'seok_daeyang', DOK, '동도 접안', 'Landing at Dongdo',
    '가장 먼 바다. 기상 게이트 · 체류 시간 제한.',
    'The farthest sea. Weather gate, limited time ashore.',
    [auto('visit', '독도에 도착한다', 'Arrive at Dokdo', { placeKey: 'region:dokdo' })]],
  ['M7-02', 7, 165, 52350, 'coop', DOK, '조사선', 'The Survey Boat',
    '잡는 게 목적이 아닌 첫 낚시. 표본 계측 → 즉시 방류.',
    'The first fishing that isn\'t about keeping. Measure, then release.',
    [auto('release', '표본 3마리 계측 후 방류', 'Measure and release three specimens', { target: 3 })],
    { reputation: { sea: 2 } }],
  ['M7-03', 7, 170, 60900, 'seok_dokgu', DOK, '열일곱 번째 장', 'The Seventeenth Page',
    '조행록 완성 판정. 돌돔 계측 후 방류.',
    'The log is judged complete. Measure and release a striped beakperch.',
    [fish('stone_beakperch', '돌돔 자가어획 후 즉시 방류 (여름~가을)', 'Catch and release a striped beakperch (summer–autumn)', { season: ['summer', 'autumn'] })],
    { journalPage: 17, teaches: ['journalComplete'] }],
  ['M7-04', 7, 176, 69400, 'okseon', SOK, '사진 속 천막', 'The Tent in the Photo',
    '네 살 사진의 좌판이 만복상회였다. 회상 시퀀스.',
    'The stall in the photo from age four was Manbok Store. A memory.',
    [talk('okseon', '정옥선과 사진을 본다', 'Look at the photo with Ok-seon')]],
  ['M7-05', 7, 182, 77950, 'coop', SOK, '2층', 'The Second Floor',
    '공동작업장 복구(자재 · 인력 · 기부).',
    'Rebuilding the workshop — materials, hands, donations.',
    [auto('earn', '재화 30,000,000원 보유 (복구 기금)', 'Hold 30,000,000 won (rebuild fund)', { target: 30_000_000 })]],
  ['M7-06', 7, 188, 86450, 'okseon', SOK, '재개관', 'Reopening',
    '자료관 겸 낚시방 개관. 정옥선이 요양을 마치고 휠체어로 참석해 테이프를 자른다.',
    'The archive and fishing room opens. Ok-seon, back from convalescence, cuts the ribbon from her wheelchair.',
    [talk('okseon', '재개관식에 참석', 'Attend the reopening')]],
  ['M7-07', 7, 194, 95000, 'tak_saebyeok', DOK, '마지막 캐스팅', 'The Last Cast',
    '전용 포인트(조사선 해역) 영구 해제. N02-4에서 되살린 유품 릴대를 던진다.',
    'The survey waters open for good. You cast the rod that Sae-byeok rebuilt.',
    [fish(undefined, '독도 전용 포인트에서 1마리', 'One fish at the Dokdo point')]],
  ['M7-08', 7, 199, 116900, '', SOK, '실습생', 'Trainee',
    '에필로그 · 수미상관. 배낭 하나 멘 스물두 살에게. "울 거면 얼음부터 나르고 울어."',
    'Epilogue, full circle. To a twenty-two-year-old with one backpack: "If you\'re going to cry, haul the ice first."',
    [auto('reachLevel', '레벨 199 도달', 'Reach level 199', { target: 199 })]],
]);

// ─────────────────────────────────────────────
// 서브 — NPC 17아크 · 55퀘 · 563,550
// ─────────────────────────────────────────────
type SubRow = [id: string, ch: 1|2|3|4|5|6|7, lv: number, xp: number, giver: string, region: string,
  titleKo: string, titleEn: string, descKo: string, descEn: string, objectives: StoryObjective[], extra?: Partial<StoryQuestDef>];

function subRows(arcId: string, rows: SubRow[]): StoryQuestDef[] {
  return rows.map((r, i) => {
    const [id, chapter, minLevel, xp, giver, region, titleKo, titleEn, descKo, descEn, objectives, extra] = r;
    return { id, kind: 'sub', part: PART_OF[chapter], chapter, arcId, titleKo, titleEn, descKo, descEn, minLevel, xp, giver, region,
      prereq: i > 0 ? [rows[i - 1][0]] : [], objectives, ...extra } as StoryQuestDef;
  });
}

const SUB: StoryQuestDef[] = [
  ...subRows('N01', [
    ['N01-1', 1, 8, 350, 'baram', SOK, '리어카', 'The Cart',
      '좌판 할머니가 손주 생일상 도다리를 못 구한다. 원투 · 체장 실습 + 리어카 도면.',
      'A stall grandmother can\'t find a flounder for her grandchild\'s birthday. Surf casting, measuring, and a cart blueprint.',
      [fish('frog_flounder', '도다리 1마리 자가어획', 'Catch one frog flounder'), talk('baram', '바람에게 리어카 도면을 받는다', 'Receive the cart blueprint from Baram')]],
    ['N01-2', 2, 28, 1450, 'baram', BUS, '다리 밑', 'Under the Bridge',
      '가출 중학생과 원양 나간 아버지. 전갱이 한 마리로 통화 버튼을 누르게 한다.',
      'A runaway and a father at sea. One horse mackerel makes him press "call".',
      [fish('horse_mackerel', '전갱이 1마리', 'One horse mackerel'), talk('baram', '다리 밑 소년을 만난다', 'Meet the boy under the bridge')]],
    ['N01-3', 3, 55, 3250, 'baram', POH, '덕장', 'The Racks',
      '청어가 안 들어와 과메기 명맥이 끊길 위기. "바다가 바뀌면 사람이 바뀌어야지."',
      'No herring — the gwamegi tradition is at risk. "When the sea changes, people must too."',
      [talk('baram', '덕장 주인과 대화', 'Talk with the rack owner')]],
    ['N01-4', 4, 82, 5600, 'baram', GEO, '절벽', 'The Cliff',
      '갯바위 사고 후 낚시를 끊은 남자와 해금강 동행.',
      'A man who quit after a rock accident — you go to Haegeumgang together.',
      [fish('largescale_blackfish', '벵에돔 자가어획 (초여름 갯바위)', 'Catch a largescale blackfish (early summer rocks)', { season: SU })],
      { journalPage: 8 }],
    ['N01-5', 5, 112, 8350, 'baram', JEJ, '해녀의 딸', 'The Diver\'s Daughter',
      '물질을 그만두려는 딸과 어머니. 해루질과 물질의 경계.',
      'A daughter who wants to quit diving, and her mother. Where gathering ends and diving begins.',
      [auto('gather', '제주 해루질 3개체', 'Gather three creatures on Jeju', { target: 3 })]],
    ['N01-6', 6, 140, 16150, 'baram', ULL, '막배를 놓친 남자', 'The Man Who Missed the Ferry',
      '결항으로 발 묶인 출장객과 섬에서 하룻밤. "나는 이제 짐이 적어도 돼." 마운틴 백팩.',
      'Stranded with a businessman for a night. "I don\'t need much baggage anymore." The mountain backpack.',
      [talk('baram', '섬에서의 하룻밤', 'A night on the island')],
      { rewards: { items: [{ id: 'inv_bag_mountain', qty: 1 }] } }],
    ['N01-7', 7, 168, 34200, 'baram', SOK, '이름', 'The Name',
      '본명 공개. 30년 전 배와 사람을 잃은 선장이었다. 재개관식에 처음 앉는다.',
      'His real name. A captain who lost his boat and crew thirty years ago. He sits down at the reopening.',
      [talk('baram', '바람의 이름을 듣는다', 'Hear Baram\'s name')]],
  ]),
  ...subRows('N02', [
    ['N02-1', 1, 11, 320, 'tak_mansu', SOK, '부러진 대', 'The Broken Rod',
      '유품 릴대 점검 의뢰 → 새벽과 학공치 내기.',
      'A check-up for the heirloom rod → a halfbeak bet with Sae-byeok.',
      [fish('halfbeak', '학꽁치 1마리', 'One halfbeak'), talk('tak_saebyeok', '새벽과 내기', 'Bet with Sae-byeok')]],
    ['N02-2', 4, 78, 5600, 'tak_mansu', TAE, '왕대를 찾아서', 'Looking for Wangdae Bamboo',
      '가출한 새벽을 태안까지 쫓아간다. 왕대 채집.',
      'You chase a runaway Sae-byeok to Taean. Gathering giant bamboo.',
      [talk('tak_saebyeok', '태안에서 새벽을 찾는다', 'Find Sae-byeok in Taean'), fish('sea_bass', '농어 1마리', 'One sea bass')],
      { journalPage: 11 }],
    ['N02-3', 5, 120, 11650, 'tak_saebyeok', JEJ, '돌무덤의 주인', 'Master of the Stone Mound',
      '서귀포 심해 대물 도전. 드랙 제어 한계 시험. (돗돔 미등록 — 대구로 대체)',
      'A deep-water giant off Seogwipo. The limit of drag control. (Substitute: Pacific cod.)',
      [fish('pacific_cod', '대구 80cm+ 자가어획', 'Catch a Pacific cod 80 cm+', { minCm: 80 })]],
    ['N02-4', 7, 175, 40200, 'tak_saebyeok', SOK, '마지막 죽간', 'The Last Bamboo Rod',
      '노인이 손을 놓고 새벽이 마무리한다. 유품 릴대 부활 → 7-7에서 사용.',
      'The old man lets go; Sae-byeok finishes. The heirloom rod lives again — for 7-7.',
      [talk('tak_saebyeok', '되살린 릴대를 받는다', 'Receive the rebuilt rod')],
      { unlocks: ['rodRevived'] }],
  ]),
  ...subRows('N03', [
    ['N03-1', 1, 5, 350, 'kang_ducheol', SOK, '선생님', 'Teacher',
      '엉킨 채비를 풀어주고 첫 입질을 함께 본다.',
      'You untangle his rig and watch his first bite together.',
      [talk('kang_ducheol', '채비를 풀어 준다', 'Untangle his rig'), fish(undefined, '함께 1마리', 'One fish together')]],
    ['N03-2', 2, 34, 1450, 'kang_ducheol', BUS, '조합장님', 'Mr. President',
      '부산 교육장에서 재회 · 정체 발각. 계속 가르치기/거리 두기(호감도만 분기).',
      'Reunion at the Busan course — the truth comes out. Keep teaching, or keep your distance.',
      [talk('kang_ducheol', '교육장에서 재회', 'Reunion at the course')]],
    ['N03-3', 5, 117, 9150, 'kang_ducheol', JEJ, '도장', 'The Seal',
      '총회 전, 표결에 개입하지 않겠다고 선언. "내 선생이 알아서 하겠지."',
      'Before the vote he declares he won\'t interfere. "My teacher will handle it."',
      [talk('kang_ducheol', '표결 전 대화', 'Talk before the vote')]],
    ['N03-4', 7, 180, 40200, 'kang_ducheol', SOK, '스승의 날', 'Teacher\'s Day',
      '은퇴하며 조합원 명부 1번을 비워 둔다. 2층 복구 자재 지원.',
      'He retires, leaving line one of the member roll empty. Materials for the second floor.',
      [talk('kang_ducheol', '은퇴 인사', 'The farewell')]],
  ]),
  ...subRows('N04', [
    ['N04-1', 1, 3, 280, 'bae_nuri', SOK, '입부 권유', 'Join the Club',
      '사비키 전어·학공치 + 방파제 즉석 조리. 1-7 요리와 교차.',
      'Sabiki halfbeak and an on-the-spot breakwater meal.',
      [fish('halfbeak', '학꽁치 2마리', 'Two halfbeak', { target: 2 }), talk('bae_nuri', '방파제부 입부', 'Join the breakwater club')]],
    ['N04-2', 1, 15, 450, 'bae_nuri', SOK, '부원을 낚아라', 'Reel In a Member',
      '축제 부스 "사람 낚기" 소동 — 진짜 목표는 진주의 입부. 그녀의 원투 포인트를 따라간다.',
      'The festival "fish for members" stunt — the real target is Jin-ju. You follow her surf-casting spot.',
      [fish('sandfish', '도루묵 자가어획 (겨울 새벽 방파제)', 'Catch a sandfish (winter dawn, breakwater)', { season: W }),
        talk('mo_jinju', '진주를 입부시킨다', 'Get Jin-ju to join')],
      { journalPage: 1 }],
  ]),
  ...subRows('N05', [
    ['N05-1', 2, 25, 1150, 'seo_harin', BUS, '낚아서 먹고 싶어요', 'I Want to Catch It and Eat It',
      '하린의 첫 선상, 기범의 조용한 교정. 선상 매너.',
      'Ha-rin\'s first boat trip, Gi-beom\'s quiet corrections. Boat manners.',
      [talk('na_gibeom', '기범에게 선상 매너를 듣는다', 'Learn boat manners from Gi-beom')]],
    ['N05-2', 2, 40, 1450, 'seo_harin', BUS, '조회수', 'Views',
      '하린 영상에 주인공이 찍혀 논란. 촬영 동의 · 초상권.',
      'You end up in Ha-rin\'s video. Consent and image rights.',
      [fish('horse_mackerel', '전갱이 2마리 (야간 루어)', 'Two horse mackerel (night lure)', { target: 2 }), talk('seo_harin', '촬영 동의 이야기', 'Talk about filming consent')],
      { journalPage: 3 }],
    ['N05-3', 5, 124, 8350, 'na_gibeom', JEJ, '퇴사합니다', 'I Quit',
      '기범이 낚시로 살겠다고 한다. 말릴 수도, 도울 수도.',
      'Gi-beom says he\'ll live by fishing. You could stop him — or help.',
      [talk('na_gibeom', '기범의 결심을 듣는다', 'Hear Gi-beom out')]],
    ['N05-4', 6, 144, 17750, 'seo_harin', INC, '두 번째 겨울', 'Second Winter',
      '인천 발령된 하린과 연안부두에서 재회.',
      'Ha-rin, transferred to Incheon — reunion at Yeonan Pier.',
      [fish('black_rockfish', '우럭 1마리', 'One black rockfish'), talk('seo_harin', '연안부두 재회', 'Reunion at the pier')],
      { journalPage: 15 }],
    ['N05-5', 7, 186, 43200, 'na_gibeom', SOK, '손님 두 명', 'Two Guests',
      '재개관식 첫 예약이 두 사람. 처음으로 돈 받고 태우는 친구.',
      'The first booking at the reopening is the two of them. Friends who pay to come aboard.',
      [talk('seo_harin', '첫 예약 손님을 맞는다', 'Welcome your first booked guests')]],
  ]),
  ...subRows('N06', [
    ['N06-1', 2, 21, 1150, 'go_hosu', BUS, '농구부인 줄 알았는데', 'I Thought It Was Basketball',
      '가입 착각 소동 + 첫 농어 루어. 2-5 루어 개방과 교차.',
      'A mix-up joining, and a first sea bass on lure.',
      [fish('sea_bass', '농어 1마리 (루어)', 'One sea bass (lure)', { method: 'rod' })]],
    ['N06-2', 2, 31, 1450, 'mo_taejo', BUS, '불순한 동기', 'Impure Motives',
      '하늘을 진지한 앵글러로. 상황별 루어 선택 실측.',
      'Making Ha-neul a real angler. Lure selection by situation.',
      [fish(undefined, '루어로 3마리', 'Three fish on lure', { target: 3 })]],
    ['N06-3', 2, 43, 2050, 'yeo_gangsan', BUS, '먹보', 'The Glutton',
      '태풍 뒤 탁수, 괴물 농어 3인 협공. 태클 베스트 · 주간 의뢰 \'동아리 대결\'.',
      'Murky water after the typhoon — three of you against a monster sea bass. The tackle vest.',
      [fish('sea_bass', '농어 60cm+', 'A sea bass 60 cm+', { minCm: 60 })],
      { journalPage: 2, rewards: { items: [{ id: 'inv_bag_tackle_vest', qty: 1 }] } }],
  ]),
  ...subRows('N07', [
    ['N07-1', 2, 37, 1450, 'jim_kang', BUS, '공방 터', 'The Workshop Site',
      '영도 폐공방 도면 발견 → 시험 장소인 속초로 되돌아가 대결.',
      'A blueprint in the abandoned Yeongdo workshop → back to Sokcho for a duel.',
      [talk('jim_kang', '짐 강과 첫 대결', 'First duel with Jim Kang')]],
    ['N07-2', 3, 57, 3250, 'jim_kang', POH, '두 번째', 'The Second',
      '포항 앞바다 지그. 지깅 숙련 실측.',
      'Jigs off Pohang. Measuring your jigging.',
      [fish('yellowtail', '방어 1마리 (지깅)', 'One yellowtail (jigging)')]],
    ['N07-3', 4, 93, 5600, 'jim_kang', TAE, '세 번째', 'The Third',
      '만리포 서프 미노우.',
      'A minnow in the Mallipo surf.',
      [fish('sea_bass', '농어 1마리 (서프)', 'One sea bass (surf)')],
      { journalPage: 11 }],
    ['N07-4', 5, 125, 11650, 'jim_kang', JEJ, '네 번째', 'The Fourth',
      '제주 에기. 4점 완성 후 전부 주인공에게 넘긴다 — "박제하려고 찾은 게 아니야."',
      'The Jeju egi. With all four found, he hands them over — "I didn\'t collect them to mount them."',
      [fish('squid', '무늬오징어 1마리 (에기)', 'One bigfin reef squid (egi)'), talk('jim_kang', '유작 넷을 받는다', 'Receive the four lures')]],
  ]),
  ...subRows('N08', [
    ['N08-1', 3, 47, 2600, 'go_manseok', ULS, '첫 승선', 'First Boarding',
      '사관 배치 · 선상 채비 · 선상 물회. 반복 의뢰 \'승객 사연\' 개방.',
      'Seat allocation, boat rigs, mulhoe on deck. Passenger stories unlocked.',
      [man('boatTrip', '고래마루 승선 (배 출조 — 준비 중)', 'Board the Goraemaru (boat trips — coming soon)')]],
    ['N08-2', 3, 62, 4550, 'go_haena', ULS, '해나의 칼', 'Hae-na\'s Knife',
      '요리학교에 가려는 딸과 반대하는 아버지. 겨울 방어 한 마리로 차려진 식탁.',
      'A daughter bound for culinary school, a father against it. A table set with one winter yellowtail.',
      [fish('yellowtail', '방어 1마리 (겨울)', 'One yellowtail (winter)', { season: W }), auto('sashimi', '회뜨기 1회', 'Slice sashimi once')],
      { journalPage: 5 }],
  ]),
  ...subRows('N09', [
    ['N09-1', 3, 50, 2600, 'han_bom', POH, '호미곶의 털바늘', 'Fly at Homigot',
      '갯바위에서 미끄러질 뻔한 봄을 붙잡으며 첫 만남.',
      'You catch Bom before she slips on the rocks — first meeting.',
      [talk('han_bom', '봄을 붙잡는다', 'Catch Bom')]],
    ['N09-2', 3, 59, 3250, 'lee_suyeon', POH, '칼을 쥐면', 'Holding the Knife',
      '수연이 잡고 봄이 즉석 조리. 요리 품질 판정 심화.',
      'Su-yeon catches, Bom cooks. Cooking quality, deeper.',
      [fish(undefined, '2마리 낚아 손질', 'Catch and butcher two fish', { target: 2 }), auto('butcher', '손질 2회', 'Butcher twice', { target: 2 })]],
    ['N09-3', 3, 68, 4450, 'lee_suyeon', POH, '아빠의 패턴', 'Dad\'s Pattern',
      '털바늘 패턴 복원 → 셋의 첫 식탁. 주인공이 부모 이야기를 꺼낸다.',
      'Restoring her father\'s fly pattern → the three of you at one table. You speak of your parents.',
      [fish('red_seabream', '참돔 1마리', 'One red seabream'), talk('lee_suyeon', '첫 식탁', 'The first table')],
      { journalPage: 6 }],
  ]),
  ...subRows('N10', [
    ['N10-1', 3, 65, 3250, 'namgung_hyeon', POH, '야간 근무', 'Night Shift',
      '창고 재고 정리 아르바이트. 새벽에 그의 캐스팅을 우연히 본다.',
      'A warehouse stock job. At dawn you happen to see him cast.',
      [talk('namgung_hyeon', '창고 야간 근무', 'Work the night shift')],
      { rewards: { coins: 80000 } }],
    ['N10-2', 5, 128, 8350, 'namgung_hyeon', JEJ, '계측 이의신청', 'The Measurement Appeal',
      '대회 계측 분쟁에서 규정대로 증언. 편들지 않는 태도.',
      'A measuring dispute — you testify by the rules, taking no side.',
      [talk('namgung_hyeon', '규정대로 증언', 'Testify by the rules')],
      { journalPage: 13 }],
    ['N10-3', 7, 172, 37200, 'namgung_hyeon', SOK, '심판석', 'The Judge\'s Seat',
      '재개관 기념 대회 심판. 20년 만에 대회장에 선다.',
      'Judge at the reopening tournament. His first tournament in twenty years.',
      [talk('namgung_hyeon', '심판을 부탁한다', 'Ask him to judge')]],
  ]),
  ...subRows('N11', [
    ['N11-1', 4, 72, 4500, 'chae_geumja', GEO, '요리 못 하는 선장', 'The Captain Who Can\'t Cook',
      '선상식을 대신 만들고 항로 판단을 배운다.',
      'You cook the boat meal and learn to read a course.',
      [fish('flatfish', '광어 1마리', 'One flatfish'), talk('chae_geumja', '항로 판단 수업', 'A lesson in navigation')],
      { journalPage: 7 }],
    ['N11-2', 4, 85, 5600, 'chae_pado', GEO, '파도의 첫 월급', 'Pa-do\'s First Pay',
      '날린 경매 물량을 새벽 긴급 조업으로 메운다. 드라이백.',
      'Making up a lost auction lot with a dawn emergency run. The dry bag.',
      [auto('trap', '통발 2회 수거', 'Harvest two traps', { target: 2 })],
      { rewards: { items: [{ id: 'inv_bag_dry', qty: 1 }] } }],
    ['N11-3', 4, 95, 7900, 'chae_geumja', GEO, '태풍 전야', 'The Night Before the Storm',
      '출항을 조르는 손님을 거절할 것인가. 배우면 4-6 사고 확률 하락.',
      'Will you refuse the guest who insists on sailing? Learn it, and 4-6 gets safer.',
      [talk('chae_geumja', '거절하는 법을 배운다', 'Learn how to refuse')],
      { reputation: { harbor: { gyeongnam_geoje: 3 } } }],
  ]),
  ...subRows('N12', [
    ['N12-1', 4, 75, 4500, 'oh_gayun', YEO, '다툰 날의 방파제', 'The Breakwater on a Bad Day',
      '조과 0이어도 완료되는 유일한 퀘 — 목표가 \'일몰까지 자리를 지키기\'.',
      'The only quest that completes with zero catch — the goal is to stay until sunset.',
      [man('holdPosition', '일몰까지 자리를 지킨다 (대화로 완료)', 'Stay until sunset (via dialogue)')]],
    ['N12-2', 4, 91, 7350, 'jeong_umi', YEO, '잔잔함', 'Calm',
      '커플의 밤바다 가이드. 화해든 이별이든 따뜻하게.',
      'Guiding a couple on the night sea. Reconciliation or parting — warmly.',
      [fish('hairtail', '갈치 2마리 (야간)', 'Two hairtail (night)', { target: 2 })],
      { journalPage: 9 }],
  ]),
  ...subRows('N13', [
    ['N13-1', 4, 88, 4500, 'ma_gamgi', TAE, '마감 도주', 'Deadline Escape',
      'PD의 추격을 피해 갑오징어 선상. 배 위에서 콘티가 완성된다.',
      'Fleeing the producer onto a cuttlefish boat. The storyboard gets finished on deck.',
      [fish('cuttlefish', '갑오징어 2마리', 'Two cuttlefish', { target: 2 })],
      { journalPage: 10 }],
    ['N13-2', 4, 97, 7350, 'song_gibaek', TAE, '두고 온 것', 'What Was Left Behind',
      '노인이 평생 찾던 것은 방제 봉사 때 단체사진이었다. 주인공은 자기 가족사진을 떠올린다.',
      'What the old man searched for all his life was a group photo from the oil-spill cleanup. You think of your own.',
      [talk('song_gibaek', '사진 이야기', 'The photograph')]],
  ]),
  ...subRows('N14', [
    ['N14-1', 5, 102, 6650, 'yu_ria', JEJ, '첫 로케', 'First Location Shoot',
      '방송 촬영 보조. 방어 한 마리 + 방송용 구도.',
      'Helping a TV shoot. One yellowtail, framed for camera.',
      [fish('yellowtail', '방어 1마리', 'One yellowtail')]],
    ['N14-2', 5, 108, 7500, 'oh_serin', JEJ, '버린 꿈', 'The Abandoned Dream',
      '서귀포 갯바위에서 마라를 찾아낸다. 재회 거부.',
      'You find Mara on the Seogwipo rocks. She refuses the reunion.',
      [fish('squid', '무늬오징어 1마리', 'One bigfin reef squid'), talk('mara', '마라를 찾아낸다', 'Find Mara')],
      { journalPage: 14 }],
    ['N14-3', 5, 114, 8350, 'oh_serin', JEJ, '팀', 'Team',
      '청년부 팀 등록 · 합동 지깅 훈련.',
      'Registering the youth team, joint jigging drills.',
      [fish(undefined, '지깅 훈련 3마리', 'Three fish in jigging drills', { target: 3 })]],
    ['N14-4', 5, 127, 12500, 'oh_serin', JEJ, '결선', 'The Final',
      '순위와 무관하게 완주. 세 사람 각자의 결말.',
      'Finishing regardless of rank. Three endings.',
      [fish('swordtip_squid', '한치 3마리', 'Three swordtip squid', { target: 3 })],
      { journalPage: 12 }],
  ]),
  ...subRows('N15', [
    ['N15-1', 6, 136, 12900, 'oh_sera', ULL, '혼자가 좋아요', 'I Like Being Alone',
      '동행 거절. 그녀의 포인트를 침범하지 않고 조과 겨루기 — 신규 규칙 \'매너 거리\'.',
      'She refuses company. Compete without crossing into her spot — the "manner distance" rule.',
      [fish('amberjack', '부시리 1마리', 'One amberjack')]],
    ['N15-2', 6, 152, 21000, 'yeon_taeo', ULL, '들킬 뻔한 밤', 'The Night Almost Caught',
      '태오와 마주치는 코미디 → 야간 합류.',
      'A comedy of bumping into Tae-o → a night session together.',
      [fish('amberjack', '부시리 2마리 (야간)', 'Two amberjack (night)', { target: 2 })],
      { journalPage: 16 }],
  ]),
  ...subRows('N16', [
    ['N16-1', 6, 132, 12900, 'seok_dokgu', ULL, '도전장', 'The Challenge',
      '"육지 사람은 못 잡아" — 볼락 대결. 현지 조달 미끼 · 낡은 사이소 릴을 물려준다.',
      '"Mainlanders can\'t catch here" — a rockfish duel. Local bait; you hand down the old Saiso reel.',
      [fish('dark_banded_rockfish', '볼락 3마리', 'Three rockfish', { target: 3 })]],
    ['N16-2', 6, 148, 16150, 'seok_dokgu', ULL, '등대까지', 'To the Lighthouse',
      '할아버지에게 가는 편지 심부름 → 6-3 조건.',
      'A letter errand to his grandfather → the condition for 6-3.',
      [talk('seok_daeyang', '편지를 전한다', 'Deliver the letter')]],
    ['N16-3', 7, 191, 46200, 'seok_dokgu', DOK, '독구의 첫 바다', 'Dok-gu\'s First Sea',
      '보호자 동의로 조사 보조 동행. 할아버지의 마지막 근무 교대.',
      'With his guardian\'s consent he joins the survey. His grandfather\'s last shift.',
      [fish('stone_beakperch', '돌돔 계측 후 방류', 'Measure and release a striped beakperch')],
      { journalPage: 17 }],
  ]),
  ...subRows('N17', [
    ['N17-1', 6, 138, 12900, 'dan_cheolho', INC, '퇴근길 20분', 'Twenty Minutes After Work',
      '게임 내 20분 제한 짬낚시 → 단골 식당에 무상 전달(§3 준수).',
      'A twenty-minute session → delivered free to the usual restaurant (rules respected).',
      [fish(undefined, '20분 안에 1마리', 'One fish within twenty minutes'), man('deliverFree', '식당에 무상 전달 (대화로 완료)', 'Deliver it free (via dialogue)')]],
    ['N17-2', 6, 156, 21050, 'ha_minji', INC, '첼로 케이스', 'The Cello Case',
      '연주회 당일 조과 파티. 두 사람이 재개관식 연주를 자청한다.',
      'A catch party on concert day. The two of them volunteer to play at the reopening.',
      [fish('black_rockfish', '우럭 2마리', 'Two black rockfish', { target: 2 })],
      { journalPage: 15 }],
  ]),
];

export const STORY_QUESTS: StoryQuestDef[] = [...MAIN, ...SUB];

const BY_ID = new Map(STORY_QUESTS.map((q) => [q.id, q]));
export function getStoryQuest(id: string): StoryQuestDef | undefined { return BY_ID.get(id); }
export function storyQuestsOfChapter(ch: number, kind?: 'main' | 'sub'): StoryQuestDef[] {
  return STORY_QUESTS.filter((q) => q.chapter === ch && (!kind || q.kind === kind));
}
/** 챕터의 마지막 메인 퀘 — 다음 챕터 해금 키 */
export function lastMainQuestOfChapter(ch: number): StoryQuestDef | undefined {
  const list = storyQuestsOfChapter(ch, 'main');
  return list[list.length - 1];
}

/**
 * 무결성 검사 — §8-1 수치 계약(챕터별 수·XP 합계) · id 유일 · prereq 존재 · 조행록 17장 커버.
 * 문제 없으면 빈 배열. dev 부팅 시 `console.warn`으로 노출한다(client).
 */
export function validateStoryQuests(): string[] {
  const issues: string[] = [];
  const ids = new Set<string>();
  for (const q of STORY_QUESTS) {
    if (ids.has(q.id)) issues.push(`중복 id ${q.id}`);
    ids.add(q.id);
    for (const p of q.prereq) if (!BY_ID.has(p)) issues.push(`${q.id}: prereq ${p} 없음`);
    if (q.objectives.length === 0) issues.push(`${q.id}: 목표 없음`);
  }
  for (const c of STORY_CHAPTERS) {
    const m = storyQuestsOfChapter(c.chapter, 'main'), s = storyQuestsOfChapter(c.chapter, 'sub');
    const mx = m.reduce((a, q) => a + q.xp, 0), sx = s.reduce((a, q) => a + q.xp, 0);
    if (m.length !== c.contract.mainCount) issues.push(`Ch${c.chapter} 메인 수 ${m.length} ≠ ${c.contract.mainCount}`);
    if (mx !== c.contract.mainXp) issues.push(`Ch${c.chapter} 메인 XP ${mx} ≠ ${c.contract.mainXp}`);
    if (s.length !== c.contract.subCount) issues.push(`Ch${c.chapter} 서브 수 ${s.length} ≠ ${c.contract.subCount}`);
    if (sx !== c.contract.subXp) issues.push(`Ch${c.chapter} 서브 XP ${sx} ≠ ${c.contract.subXp}`);
  }
  const pages = new Set(STORY_QUESTS.filter((q) => q.journalPage).map((q) => q.journalPage));
  for (let p = 1; p <= 17; p++) if (!pages.has(p)) issues.push(`조행록 ${p}장을 채우는 퀘스트 없음`);
  return issues;
}
