# -*- coding: utf-8 -*-
"""
@file gen_skill_icons.py
@description 스킬 트리 아이콘 아트 -> packages/client-pc/src/data/SkillIconArt.ts 자동 생성

스킬 93종(낚시·채집·경제·이동·생활·농사·제작 + 숨은 시너지 5종)을
**16x16 손그림 픽셀 매트릭스**로 보관한다. 문자 = 팔레트 키, '.' = 투명.
여기서 art를 고치고 다시 실행하면 TS가 갱신된다.

    py tools/gen_skill_icons.py

규칙 (AGENTS §4 「UI 특수문자·이모지 금지 / 픽셀 아이콘 원칙」):
  - 도형 프리미티브 조합(원+사각)이 아니라 **픽셀 단위 손그림**이다.
  - 1px 어두운 윤곽 · 좌상단 광원 · 하이라이트 픽셀 · 아이콘당 3~6색(+윤곽).
  - 글자·숫자·약어를 그려 넣지 않는다(그림으로 읽혀야 한다).
  - 가장자리 1px은 비운다(여백) — 스크립트가 검사한다.
  - 시너지(syn_*) 아이콘은 금색 테두리 엠블럼으로 일반 스킬과 구분한다.

팔레트는 공용 PAL(카테고리 간 톤 통일)에서 아이콘이 쓰는 문자만 골라 내보내고,
아이콘별로 색을 덮어쓸 수 있다(icon(..., pal={...})).
행 수·행 길이·팔레트 문자·여백·스킬 id 누락은 스크립트가 검사하므로 어긋나면 바로 에러가 난다.
"""
import io, os, sys

W = H = 16

# ── 공용 팔레트 ─────────────────────────────────────────
PAL = {
    'o': 0x1a1c24,  # 윤곽
    'w': 0xffffff,  # 하이라이트 흰색
    'G': 0xd0d8e0,  # 밝은 회색
    'g': 0x8c98a4,  # 회색
    'd': 0x4c5864,  # 어두운 회색
    'b': 0x6e4420,  # 어두운 갈색
    'B': 0xa8702e,  # 갈색
    'n': 0xdcae66,  # 황갈(나무 밝은면)
    'u': 0x2464a8,  # 짙은 파랑
    'U': 0x4aa0e0,  # 파랑
    'c': 0xa8e0f8,  # 밝은 하늘
    'r': 0xa82a22,  # 짙은 빨강
    'R': 0xe8503a,  # 빨강
    'y': 0xe8b030,  # 금색
    'Y': 0xffe486,  # 밝은 금색
    'k': 0x9a6c18,  # 짙은 금색
    'e': 0x2e7a34,  # 짙은 초록
    'E': 0x5cb84a,  # 초록
    'l': 0xb4e47a,  # 연두
    'v': 0x3a2c70,  # 남보라(밤)
    'V': 0x6c5cc0,  # 보라
    'a': 0xd86a1c,  # 주황
    'A': 0xf8b060,  # 밝은 주황
    's': 0xf2c294,  # 피부
    'S': 0xc4865a,  # 피부 그늘
    'm': 0xf0e8d0,  # 종이(크림)
    'M': 0xc8b890,  # 종이 그늘
    'p': 0xf08cb0,  # 분홍
    'P': 0xb04a78,  # 짙은 분홍
}

ICONS = {}


def icon(key, art, pal=None):
    """16x16 아이콘 등록. pal 로 공용 팔레트 문자를 덮어쓰거나 추가한다."""
    full = dict(PAL)
    full.update(pal or {})
    rows = [r for r in art.strip('\n').split('\n')]
    if len(rows) != H:
        raise SystemExit(f'{key}: 행 수 {len(rows)} != {H}')
    used = []
    for i, r in enumerate(rows):
        if len(r) != W:
            raise SystemExit(f'{key}: r{i} 길이 {len(r)} != {W} -> "{r}"')
        for j, ch in enumerate(r):
            if ch == '.':
                continue
            if ch not in full:
                raise SystemExit(f'{key}: r{i} 팔레트에 없는 문자 "{ch}"')
            if i in (0, H - 1) or j in (0, W - 1):
                raise SystemExit(f'{key}: r{i} c{j} 가장자리 1px 여백 침범 -> "{r}"')
            if ch not in used:
                used.append(ch)
    if len(used) > 8:
        raise SystemExit(f'{key}: 색 {len(used)}개 — 윤곽 포함 8색 이하로')
    if key in ICONS:
        raise SystemExit(f'{key}: 중복 등록')
    ICONS[key] = ({c: full[c] for c in sorted(used)}, rows, W, H)


# ════════════════════════════════════════════════════════
#  낚시 (fishing)
# ════════════════════════════════════════════════════════

# 롱캐스트 = 젖힌 낚싯대 + 길게 휘어 날아가는 원줄 + 찌
icon('fish_cast', """
................
.....GGGGG......
...GG.....GG....
..G.........G...
..o..........G..
..on.........o..
...oB.......oRo.
...oB.......oRo.
....oB......owo.
..oggoB.....oGo.
..ogGgoB.....o..
...oggnbo.......
......nbbo......
.......nbo......
........o.......
................
""")

# 입질 감각 = 쏙 들어가는 찌 + 물결 고리
icon('fish_bite', """
................
.......o........
......oRo.......
......oRo.......
.....oRRro......
.....owwGo......
.....oRRro......
..c..orrro..c...
...c..oro..c....
..UUcc.o..ccUU..
.U............U.
..UU........UU..
....UUUUUUUU....
................
................
................
""")


# 라인 관리 = 원줄 스풀(가지런히 감긴 줄 + 풀린 끝의 바늘)
icon('fish_line', """
................
...oooooooo.....
.ooGGGGGGGGoo...
.oGGGGooGGGgo...
..oogggggggoo...
...olEEEEEeo....
...oleeeeeeoll..
...olEEEEEeo..l.
...oleeeeeeo..l.
...olEEEEEeo..l.
..ooGGGGGGgoo.l.
.oGGGGGGGGGgo.l.
.ogggggggggdo.G.
..ooooooooooo...
................
................
""")

# 궂은날 조사 = 먹구름 + 비스듬한 빗줄기
icon('fish_weather', """
................
................
.....oooo.......
....oGGGGo.ooo..
..oooGGGGGoGGGo.
.oGGGGGGGGGGGgo.
.oGgggggggggggo.
.ogggggggggggdo.
..oooooooooooo..
................
...c...c...c....
..U...U...U.....
.....c...c...c..
....U...U...U...
................
................
""")

# 야간 눈 = 부릅뜬 눈 + 초승달 + 별
icon('fish_night', """
................
...........ooo..
..Y.......oYYo..
..........oYo...
.....Y....oYo...
..........oYYo..
...........ooo..
.....oooooo.....
...oowyyyywoo...
..owwyYYyyywwo..
.owwwyYwoyyGwwo.
.owwwyyyoyyGwwo.
..owGwyyoyyGGo..
...ooGGyyyGoo...
.....oooooo.....
................
""")

# 한 바늘에 두 미끼(193차) = 바늘 한 개에 분홍 갯지렁이 두 마리
icon('fish_double_bait', """
................
.........ooo....
........oG.Go...
.........oGo....
......ooooGoo...
....opwppppwppo.
....oPPPPPPPPPo.
.....oooooGooo..
...opwppppppwo..
...oPPPPPPPPPo..
....ooooooGoo...
.....owo.oGo....
.....oGoooGo....
......oGGgo.....
.......ooo......
................
""")

# 보관 요령 = 아이스박스(손잡이 + 눈송이)
icon('fish_fresh', """
................
................
.....oooooo.....
.....o....o.....
..oooooooooooo..
..owwwwwwwwwGo..
..oGGGGGGGGGgo..
..oooooooooooo..
..oUUUUwUUUUuo..
..oUUwUwUwUUuo..
..oUUUwwwUUUuo..
..oUUwUwUwUUuo..
..oUUUUwUUUUuo..
..ouuuuuuuuuuo..
..oooooooooooo..
................
""")

# 드랙 제어 = 원형 릴(감긴 줄 + 허브 + 손잡이 노브)
icon('fish_drag', """
................
.oooooooooooooo.
.onnnnnnnnnnnBo.
.ooooGGGgoooooo.
......oGo.......
.....oooo.......
...ooGGGGoo.....
...oGEEEEgo.....
..oGEEEEEEgo....
..oGEEooEEgoooo.
..oGEEoGGGGGGBo.
..ogEEEEEEeooBo.
...oeEEEEeo..oo.
...ooggggoo.....
.....oooo.......
................
""")

# 밑밥 감각 = 밑밥통 + 주걱 + 흩뿌려지는 밑밥
icon('fish_chum', """
................
.o..........n...
.Bo......n...n..
.oBo.....B......
..oBo..n....n...
...oBo...n......
....oBo.n.......
..ooooBoooooo...
..onBnnnBnBno...
..oGGGGGGGGgo...
...oUUUUUUUo....
...ouuuuuuuo....
...oUUUUUUUo....
...oUUUUUUuo....
....ooooooo.....
................
""")

# 루어 액션 = 미노우 루어(립 + 트레블 훅)
icon('fish_lure', """
................
................
................
....oooooo......
..ooeeeeeeoo.c..
.oeEEEElEEEEo.c.
.oEwoEEEEEEEEo..
.oEooGGGGGGGGGo.
.ooGwwwwwwwwoo..
.ccowwwwwwoo..c.
.cc.oooooo...c..
.c.....g........
......gGg.......
......g.g.......
................
................
""")

# 챔질 타이밍 = 바늘 + 위로 치켜드는 화살표
icon('fish_hook', """
................
..........G.....
..........G.....
.........ooo....
..Y..Y..oGwgo...
...Y.Y..og.Go...
.........oGgo...
.YY..o...oGgo...
....oGo..oGgo...
....oGGo.oGgo...
....oGgo.oGgo...
....oGgGooGgo...
.....ogGGGGgo...
......oggggo....
.......oooo.....
................
""")

# 조석 해석 = 물때표(사인 곡선 + 피딩 표시)
icon('fish_tide', """
................
................
.oooooooooooooo.
.ommmmmmmmmmmMo.
.ommmRRmmmmmmMo.
.ommUmmUmmmmmMo.
.omUmmmmUmmmmMo.
.oUmmmmmmUmmmMo.
.ommmmmmmmUmmUo.
.ommmmmmmmmUUMo.
.ommmmmmmmmmmMo.
.oMMMMMMMMMMMMo.
.omMmMmMmMmMmMo.
.oooooooooooooo.
................
................
""")

# 대물 운 = 큰 물고기 + 반짝임
icon('fish_bigluck', """
................
............Y...
...........YwY..
......oo....Y...
.....oUUo.......
...ooUUUUoo..oo.
..oUcccUUUUooUo.
.oUcUUUuUUUUUUo.
.oUwoUUuUUUUUo..
.ooUUUUuUUUUUo..
.oGGGGGGGGUUUUo.
..oGwwwwGGGooUo.
...ooGGGGoo..oo.
.....oooo.......
................
................
""")

# 정투 = 조준 표적(링 + 십자 눈금 + 착수점)
icon('fish_scatter', """
................
.......ww.......
......RRRR......
....RR.ww.RR....
...R.......R....
...R.......R....
..R...oooo..R...
.ww..oYYYo..ww..
.ww..oYyyo..ww..
..R...oooo..R...
...R.......R....
...R.......R....
....RR.ww.RR....
......RRRR......
.......ww.......
................
""")

# 스풀 컨트롤 = 스풀 정면 + 누르는 엄지
icon('fish_spool', """
................
......oooo......
.....osssSo.....
.....oSSSSo.....
.....oppsSo.....
.....oppsSo.....
.oo...osSo...oo.
.oGooooooooooGo.
.oGocUUcUUcUoGo.
.oGocUUcUUcUoGo.
.oGouuuuuuuuoGo.
.oGooooooooooGo.
.oGo........oGo.
..o..........o..
................
................
""")

# 원투 숙련 = 모래에 꽂은 원투대 + 멀리 나간 줄
icon('fish_surf', """
................
..........oYo...
..........odoG..
.........odo..G.
.........odo..G.
........odo...G.
........odo...G.
.......odo....G.
.......oBo....G.
......oBo.....G.
......oBBo..c.c.
......odo..UcUU.
.nnnnnndnnUUUUU.
.nBnnBnnnUUUUUU.
.nnnnnnnUUUUUUU.
................
""")

# 바람 읽기 = 바람에 펄럭이는 풍향 자루 + 바람결
icon('fish_wind', """
................
.oo...ccccc.....
.oGo............
.oGooooo........
.oGoRRwwoooo....
.oGoRRwwRRwwoo..
.oGoRRwwRRwwRRo.
.oGorrGGrrGGrro.
.oGorrGGrrGGoo..
.oGorrGGoooo....
.oGooooo........
.oGo............
.oGo...ccccc....
.oGo.cccc..ccc..
.ooo............
................
""")

# 지깅 숙련 = 메탈 지그 + 위아래 저킹 표시
icon('fish_jig', """
................
.....oo.....Y...
....oGgo...YYY..
.....oo...YYYYY.
.....oo.....Y...
....oUco....Y...
...oUcuo....Y...
...oUcuo....Y...
...oUcpo....Y...
...oUcpo....Y...
...oucpo....Y...
....ouo.....Y...
.....o....YYYYY.
....gGg....YYY..
....g.g.....Y...
................
""")

# 에깅 숙련 = 에기(새우 모양 루어 + 꼬리 갈퀴 + 깃털)
icon('fish_egi', """
................
................
................
................
...oooooooo.....
..oAAaAAaAAop.G.
.oAwoaAAaAAAopG.
.oAooaAAaAAAopG.
.oAAaAAaAAAAop..
.ogggoRRRRooopG.
..ooo.oRRRo.....
.......ooo......
................
................
................
................
""")

# 원줄 절약 = 되감기는 화살표 고리 + 회수한 봉돌
icon('fish_salvage', """
................
......llll......
....lllEEEEE....
...lEEEEEEEEE...
..lEE......EEE..
..lE........EE..
..EE...G....EE..
.lEE..oGo...EEE.
.EEE.oGgo.EEEEE.
..EE.oggo..EEE..
..EE.ogdo...E...
..EEE.oo........
...eEEEE........
....eeee........
................
................
""")


# ════════════════════════════════════════════════════════
#  채집 (gathering — 해루질·통발)
# ════════════════════════════════════════════════════════

# 채집 눈 = 돋보기 렌즈 속 조개
icon('gath_eye', """
................
....oooo........
..ooGGGGoo......
..oGccccgo......
.oGcwccccgo.....
.oGcaAAacgo.....
.oGcAaaAcgo.....
.oGccAAccgo.....
..ogccccgo......
..ooggggoo......
....oooooBo.....
........oBBo....
.........oBBo...
..........oBBo..
...........oo...
................
""")

# 매듭법 = 8자 매듭 밧줄
icon('gath_knot', """
................
...ooo....ooo...
..onnno..onnno..
.onnBnnoonnnnBo.
.onBoonnBnoonBo.
.onBo.onBo.onBo.
.onBo.onBo.onBo.
.onBoonnBnoonBo.
.onnnBnoonBnnBo.
..onnBo..onnBo..
.onnoo....oonBo.
.onBo......onBo.
.onBo......onBo.
..oo........oo..
................
................
""")

# 단단한 손 = 빨간 도트 목장갑
icon('gath_hands', """
................
........oo......
.....oooRRo.....
....oRRowwooo...
....owwowwoRRo..
....owwowwowwo..
....owwowwowwo..
..oooGwwwwwwwo..
.oRwoRwwRwwRwo..
.oRwowwRwwRwwo..
..oRoRwwRwwRwo..
...oowwwwwwwwo..
....oGGGGGGGGo..
....oGgGgGgGgo..
....oooooooooo..
................
""")

# 문어 붙잡기 = 문어(머리 + 말린 다리)
icon('gath_octo', """
................
.....oooooo.....
....opwppppo....
...opwppppppo...
...oppppppppo...
...opwoppwoPo...
...oppppppPPo...
..oopppppppPoo..
..oppPpppPppPo..
.oppoopoopooppo.
.opo.opoopo.opo.
.op..op..po..po.
..po.op..po.op..
...o..o..o..o...
................
................
""")

# 미끼 절약 = 그물 미끼망(속에 생선 토막)
icon('gath_bait', """
................
................
................
................
...ooooooooooo..
..opPoUuUUuUUuo.
.opppoUUuUUuUUo.
.opwpoUUUUUUUUo.
.opppoGGGGGGGGo.
.oPppoGwGGGGGGo.
..oPPoGGGGGGGgo.
...ooooooooooo..
................
................
................
................
""")

# 통발 운 = 통발 그물망 + 갇힌 꽃게 + 반짝임
icon('gath_trapluck', """
................
............Y...
...........YwY..
.....oooooo.Y...
...ooGvGvGvoo...
..oGvGvGvGvGvo..
.oGvGvGvGvGvGvo.
.oGGGGGGGGGGGGo.
.oGvGvaavGvGvGo.
.oGvGaAAaGvGvGo.
.oGvaaaaaavGvGo.
.oGGGGGGGGGGGGo.
.obbbbbbbbbbbbo.
.oooooooooooooo.
................
................
""")

# 물때 감각 = 빠지는 바닷물(아래 화살표) + 드러난 갯벌의 조개
icon('gath_tide', """
................
..cc....cc......
.cUUc..cUUc..cc.
.UUUUUUUUUUUUUU.
.uuuuuuwwuuuuuu.
.......ww.......
.......ww.......
.....wwwwww.....
......wwww......
.......ww.......
.bBBBBBBBBBBBBb.
.BBoBBBBBBBoBBB.
.BBBBBwGwBBBBBB.
.bBBBBGGGBBBoBb.
.bbbbbbbbbbbbbb.
................
""")

# 통발 회수 요령 = 물방울 튀는 싱싱한 꽃게
icon('gath_harvest', """
................
..c..........c..
.oo.oo....oo.oo.
.oRooRo..oRooRo.
.oRRRRo..oRRRRo.
..oRRo....oRRo..
...oRo.oo.oRo...
...oRRoRRoRRo...
..oRwRRRRRRRRo..
.ooRRrRRRRrRRoo.
.oRoRRRRRRRRoRo.
.oRorRRRRRRroRo.
..ooorrrrrrooo..
...oRo....oRo...
...oo......oo...
................
""")

# 헤드랜턴 효율 = 머리띠 랜턴 + 퍼지는 빛
icon('gath_lantern', """
................
.......YY.......
...Y...YY...Y...
....Y......Y....
.....oooooo.....
....oGGGGGgo....
.ooooGYwYYgoooo.
.dddoGYYYYgoddd.
.dddoGYYYYgoddd.
.ooooGYYYygoooo.
....ogGGGggo....
.....oooooo.....
....Y......Y....
...Y...YY...Y...
.......YY.......
................
""")

# 채집 손놀림 = 손갈퀴 + 빠른 움직임 선
icon('gath_speed', """
................
............oo..
...........oBno.
..........oBno..
.........oBno...
........oBno....
.......oBno.....
......ogoo......
.....ogo........
...ooGgo..cccc..
..oGGGgo........
.oGGGGgo..ccc...
.oGGGgo.........
..oGgo...cccc...
...oo...........
................
""")


# ════════════════════════════════════════════════════════
#  경제 (economy)
# ════════════════════════════════════════════════════════

# 흥정의 달인 = 악수 + 금화
icon('eco_haggle', """
................
.......oo.......
......oYyo......
......oyko......
.......oo.......
.oooo.oooo.oooo.
.oUUooSssSooRRo.
.oUUossssssoRRo.
.oUUossssssoRRo.
.oUUoSsSsSsoRRo.
.oUUoSsSsSsoRRo.
.oUUooSSSSSoRRo.
.oooooooooooooo.
................
................
................
""")

# 대량 구매 = 생선이 가득 담긴 어상자 + 얹은 덤 한 마리
icon('eco_bulk', """
................
................
..oo...oo...oo..
.oGGo.oUUo.oGGo.
.ooGo.ooUo.ooGo.
.oGGo.oUUo.oGGo.
.oGgo.oUuo.oGgo.
.oooooooooooooo.
.onnnnnnnnnnnBo.
.oBBBBBBBBBBBbo.
.obbbbbbbbbbbbo.
.onnnnnnnnnnnBo.
.oBBBBBBBBBBBbo.
.oooooooooooooo.
................
................
""")

# 어판장 단골 = 줄무늬 차양 좌판 + 생선
icon('eco_regular', """
................
.oooooooooooooo.
.oRRwwRRwwRRwwo.
.oRRwwRRwwRRwwo.
.oRRwwRRwwRRwwo.
.oRo.oRo.oRo.oo.
..o.b..o.b..o.b.
....b....b...b..
..ooboooooooob..
..onnnnnnnnnnBo.
..oGwGoGwGoGwGo.
..oBBBBBBBBBBbo.
..obbbbbbbbbbbo.
..oo........oo..
................
................
""")

# 시세 읽기 = 경락 시세판(빨강 상승 · 파랑 하락 봉)
icon('eco_market', """
................
.oooooooooooooo.
.oGGGGGGGGGGGgo.
.oGvvvvvvvvGvgo.
.oGvvvvvvvvRvgo.
.oGvvvvvvGvRvgo.
.oGvvvGvvRvRvgo.
.oGvGvRvvRvGvgo.
.oGvUvRvGRvvvgo.
.oGvUvGvUvvvvgo.
.oGvUvvvUvvvvgo.
.oGvGvvvGvvvvgo.
.ogggggggggggdo.
.ooooooddoooooo.
.....oddddo.....
................
""")

# 토지 거래 = 땅 한 필지 + 깃발 말뚝
icon('eco_land', """
................
.......o........
.......dRRRo....
.......drRRRo...
.......dRRo.....
.......d........
......odoo......
....ooEdEEoo....
..ooElEEEEEEoo..
.oEEEEEEEEEEEEo.
.oBBooEEEEoobbo.
.oBBBBoooobbbbo.
..ooBBBBbbbboo..
....ooBBbboo....
......oooo......
................
""")

# 주식 투자 = 우상향 꺾은선 화살표 + 축
icon('eco_stock', """
................
.G..............
.G........RRRRR.
.G.........RRRR.
.G..........RRR.
.G..........RRR.
.G.........R..R.
.G........Rr....
.G.......Rr.....
.G...R..Rr......
.G..RrR.Rr......
.G.RrrrRr.......
.GRr...r........
.Gr.............
.GGGGGGGGGGGGGG.
................
""")

# 식당 마진 = 요리 덮개(클로시) + 접시
icon('eco_restaurant', """
................
................
......oooo......
......oGgo......
....oooooooo....
...owwGGGGGgo...
..owGGGGGGGGgo..
..oGGGGGGGGGgo..
.oGGGGGGGGGGGgo.
.oggggggggggggo.
.oooooooooooooo.
.owwwwwwwwwwwGo.
..oooooooooooo..
................
................
................
""")

# 장부 정리 = 주판
icon('eco_ledger', """
................
................
..ooooooooooooo.
..oBnnnnnnnnnBo.
..oB.d.aAa.d.Bo.
..oBaAa.d.aAaBo.
..oBBBBBBBBBBBo.
..oBaAaaAa.d.Bo.
..oB.d.....d.Bo.
..oBaAa.d.aAaBo.
..oB.d.aAa.d.Bo.
..oBaAaaAaaAaBo.
..oBbbbbbbbbbBo.
..ooooooooooooo.
................
................
""")

# 경매 배짱 = 경매봉(의사봉) + 받침
icon('eco_auction', """
................
................
..oooooooooo....
..oBnnwnnnBo....
..oBnnnnnnBo....
..obBBBBBBbo....
..oooooooooo....
.....oBBo.......
......oBBo......
.......oBBo.....
.oooooo.oBBo....
.onnnnBo.oBBo...
.obbbbbo..oBBo..
.ooooooo...oBo..
............o...
................
""")

# 창고 관리 = 테이프 붙인 상자 더미
icon('eco_storage', """
................
................
....oooooooo....
....onnmmnBo....
....onnmmnBo....
....oBBmmBbo....
....oBBBBBbo....
.oooooooooooooo.
.onnmnBoonnmnBo.
.onnmnBoonnmnBo.
.oBBmBbooBBmBbo.
.oBBBBbooBBBBbo.
.oBBBBbooBBBBbo.
.oooooooooooooo.
................
................
""")


# ════════════════════════════════════════════════════════
#  이동 (driving — 달리기·자전거·자동차·보트)
# ════════════════════════════════════════════════════════

# 달리기 = 운동화 + 속도선
icon('drv_run', """
................
................
................
......oooo......
.....oRRRRo.....
.cc..oRwRRo.....
.....oRRwRRo....
.ccc.oRRRwRRoo..
....oRRRRRwRRRo.
.cc.oRRRRRRRRRo.
....owwwwwwwwwo.
....oGGGGGGGGGo.
.....ooooooooo..
................
................
................
""")

# 맨발 달리기 = 맨발 발자국 두 개
icon('drv_barefoot', """
................
................
...oooo.........
...osSo.........
...osSo.........
...osSo.........
..ossSo.........
..osssSoo.......
.osssssssoo.....
.osssssssssoooo.
.osssssssssSsSo.
.oSSSSSSSSSSSSo.
..oooooooooooo..
.nnBnnnnBnnnnBn.
..nnnn..nnn..n..
................
""")

# 자전거 숙련 = 자전거
icon('drv_bike', """
................
................
................
...........gg...
..........g.....
.....bbb..g.....
......RRRRR.....
......R..RR.....
..gggRR..RgRgg..
.g...RgRRg.R..g.
.g.ddRgRRg.dd.g.
.g.dd.RR.g.dd.g.
.g....g..g....g.
..gggg....gggg..
................
................
""")

# 자전거 지구력 = 바퀴 + 하트
icon('drv_bikefat', """
................
..........RR.RR.
..........RwRRr.
..........RRRRr.
....dddd...RRr..
..ddggggdd..r...
..dgG...Ggd.....
.dg.G...G.gd....
.dg...dd..gd....
.dg...dd..gd....
.dg.G...G.gd....
..dgG...Ggd.....
..ddggggdd......
....dddd........
................
................
""")

# 자동차 운전 = 승용차 옆모습
icon('drv_car', """
................
................
................
....oooooo......
...oUccUccco....
..oUcccUccccoo..
.oUUUUUUUUUUUUo.
.oUwUUUUUUUUUAo.
.ouUUUUUUUUUUuo.
.oooddooooddooo.
..odGdo..odGdo..
..odddo..odddo..
...ooo....ooo...
................
................
................
""")

# 보트 조종 = 모터보트 + 물결
icon('drv_boat', """
................
................
................
................
......ooo.......
.....occo.......
....occco..oo...
.ooooooooooodo..
.owwwwwwwwwwodo.
..oRRRRRRRRRodo.
...owwwwwwwoodo.
....ooooooo.oo..
.UUcUUUUcUUUUcU.
..UUU..UUU..UU..
................
................
""")

# 야간 주행 = 달밤의 곧은 길
icon('drv_nightride', """
................
.oooooooooooooo.
.ovvvvvvvvYYvvo.
.ovYvvvvvYYvvvo.
.ovvvvvvvYYvvvo.
.ovvvvvvvvYYvvo.
.ovvvYvvvvvvvvo.
.oeeeeeggeeeeeo.
.oeeeeggggeeeeo.
.oeeeggYYggeeeo.
.oeeggggggggeeo.
.oeggggYYggggeo.
.oggggggggggggo.
.oggggggYYggggo.
.oooooooooooooo.
................
""")

# 짐받이 확장 = 자전거 뒷바퀴 짐받이 + 묶은 상자
icon('drv_cargo', """
................
..ooooooooo.....
..onnnRnnBo.bbb.
..oBBBRBBbo..g..
..onnnRnnBo..g..
..oBBBRBBbo..g..
.GGGGGGGGGGGGG..
....gggG........
...g...Gg.......
..g...G..g......
..g..dd..g......
..g..dd..g......
..g......g......
...g....g.......
....gggg........
................
""")

# 멀미 내성 = 위장 + 흔들리는 물결
icon('drv_motion', """
................
.........ooo....
........owwwo...
.......owwwwGo..
......owwwwwGo..
.....owwwwwGGo..
....oRwwwwGGo...
...oRRRwwGGo....
..oRpRRRGGo.....
.oRpRRRRro......
.oRRRRRro.......
.oRRRRro..cc.cc.
..orrro..cUUcUU.
...ooo..UU..UU..
................
................
""")

# 운전 이론 = 신호등
icon('drv_theory', """
................
....oooooooo....
....oddRRddo....
....odRwRRdo....
....oddRRddo....
....oddyyddo....
....odywyydo....
....oddyyddo....
....oddEEddo....
....odEwEEdo....
....oddEEddo....
....oooooooo....
.......gg.......
.......gg.......
......oooo......
................
""")


# ════════════════════════════════════════════════════════
#  생활 (life — 체력·근력·피로·평형·손질·요리)
# ════════════════════════════════════════════════════════

# 체력 = 붉은 하트
icon('life_stamina', """
................
................
................
...oooo..oooo...
..oRwRRooRRRRo..
..oRwRRRRRRRro..
..oRRRRRRRRRro..
..oRRRRRRRRRro..
...oRRRRRRRro...
....oRRRRRro....
.....oRRRro.....
......oRro......
.......oo.......
................
................
................
""")

# 힘 = 아령
icon('life_strength', """
................
................
................
.oooo......oooo.
.oGdoo....ooGdo.
.oGdogo..ogoGdo.
.oGdogoooogoGdo.
.oGdogwGGGgoGdo.
.oGdoggggggoGdo.
.oGdogoooogoGdo.
.oGdogo..ogoGdo.
.oGdoo....ooGdo.
.oooo......oooo.
................
................
................
""")

# 회복력 = 충전 중인 배터리
icon('life_recover', """
................
................
................
.oooooooooooo...
.oGGGGGGGGGGo...
.oGlEEEEEYEGo...
.oGlEEEEYYEGoo..
.oGlEEEYYEEGogo.
.oGlEEYYYYYGogo.
.oGlEEEEYYEGogo.
.oGlEEEYYEEGoo..
.oGlEEEYEEEGo...
.oGGGGGGGGGGo...
.oooooooooooo...
................
................
""")

# 평형감각 = 수평계(가운데 기포)
icon('life_balance', """
................
................
................
................
.oooooooooooooo.
.oYYYooooooYYYo.
.oyyyoEwwEoyyyo.
.okkkooooookkko.
.oooooooooooooo.
.......oo.......
......oGGo......
.....oGGggo.....
....oGGggggo....
...oooooooooo...
................
................
""")

# 추위 내성 = 방울 털모자
icon('life_cold', """
................
......oooo......
.....owwwGo.....
.....owGGgo.....
....oooooooo....
...oRRrRRrRRo...
..oRRRrRRrRRro..
..oRRRrRRrRRro..
..oRRRrRRrRRro..
.oooooooooooooo.
.owwGwwGwwGwwGo.
.owGwwGwwGwwGgo.
.oooooooooooooo.
................
................
................
""")

# 손질 손 = 회칼
icon('life_fillet', """
................
............oo..
...........owGo.
..........owGgo.
.........owGgo..
........owGgo...
.......owGgo....
......owGgo.....
.....owGgo......
....owGgo.......
...odddo........
..oBnBo.........
.oBnBo..........
.onBo...........
..oo............
................
""")

# 요리 손 = 김 오르는 양은냄비
icon('life_cook', """
................
.....G...G......
......G...G.....
.....G...G......
.......oo.......
....oooGgooo....
...oGGGGGGGgo...
..oooooooooooo..
..oYYYYYYYYyyo..
.ooyyyyyyyyykoo.
..oyyyyyyyyyko..
..oyyyyyyyyyko..
...okkkkkkkko...
....oooooooo....
................
................
""")

# 소식가 = 김 두른 주먹밥 한 개
icon('life_hunger', """
................
................
......oooo......
.....owwwwo.....
.....owwwwo.....
....owwwwwGo....
....owwGwwGo....
...owwwwwwwGo...
...owGwwwwwGo...
..owwwNNNNwwGo..
..owwNNNNNNwGo..
.owwwNNNNNNwwGo.
.owwwNNNNNNwGGo.
..oooooooooooo..
................
................
""", pal={'N': 0x1f3a2a})

# 수분 관리 = 물 담긴 유리잔
icon('life_thirst', """
................
................
...oooooooooo...
...ow......co...
...ow......co...
...owccccccco...
...owUUUUUUUo...
...owUUUUUUUo...
...owUUUUUUuo...
...owUUUUUUuo...
...owUUUUUuuo...
...oGuuuuuuuo...
...oGGGGGGGGo...
...oooooooooo...
................
................
""")

# 쾌면 = 푹신한 베개 + 초승달
icon('life_sleep', """
................
...........ooo..
..Y.......oYYo..
..........oYo...
......Y...oYo...
..........oYYo..
...........ooo..
...oooooooooo...
..owwwwwwwwwwo..
.owwwwwwwwwwwco.
.owwwwwccwwwwco.
.owwwwwwwwwwcco.
..occcccccccco..
...oooooooooo...
................
................
""")

# 면역력 = 방패 + 새잎
icon('life_immune', """
................
..oooooooooooo..
..oGGGGGGGGGGo..
..oGUUUUUUUUgo..
..oGUUUUUUEUgo..
..oGUUUUElEUgo..
..oGUUUElEEUgo..
..oGUUElEEUUgo..
..oGUElEEUUUgo..
..oGUeEEUUUUgo..
..oGUeUUUUUugo..
...oGUUUUUugo...
....oGUUUugo....
.....oGuugo.....
......oooo......
................
""")

# 응급처치 = 반창고
icon('life_firstaid', """
................
..........oo....
.........onno...
........onBnBo..
.......onnnBnno.
......omnnBnBno.
.....ommmnnnno..
....omMmMmnno...
...onnmMmMmo....
..onnnnmmmo.....
.onBnBnnmo......
.onnBnBno.......
..onBnno........
...onno.........
....oo..........
................
""")

# 위생 관념 = 비누 + 거품 방울
icon('life_hygiene', """
................
..........cc....
.........cw.c...
....cc...c..c...
...cw.c...cc....
...c..c......c..
....cc......cwc.
...oooooooooo.c.
..owwppppppppo..
.oppppppppppppo.
.oPPPPPPPPPPPPo.
.oPPPPPPPPPPPPo.
..oPPPPPPPPPPo..
...oooooooooo...
................
................
""")

# 대식가 = 고봉으로 담은 큰 밥그릇
icon('life_belly', """
................
......oooo......
.....owwwGo.....
....owwwwwGo....
...owwGwwwwGo...
..owwwwwwGwwGo..
.owwwGwwwwwwGGo.
.oooooooooooooo.
.oUcUUUUUUUUuuo.
..oUUcUUUUUUuo..
...oUUUUUUUuo...
....ouuuuuuo....
.....oUUUUo.....
.....oooooo.....
................
................
""")

# 큰 물통 = 둥근 수통(마개)
icon('life_canteen', """
................
......oooo......
......oddo......
......oddo......
.....oGGGGo.....
...ooEEEEEEoo...
..oElEEEEEEEeo..
.oElEEEcEEEEEeo.
.oEEEEcwcEEEEeo.
.oEEEEcccEEEeeo.
.oEEEEEcEEEEeeo.
..oeEEEEEEEeeo..
...ooeeeeeeoo...
.....oooooo.....
................
................
""")

# 강단 = 불끈 쥔 주먹 + 땀방울
icon('life_grit', """
................
.c..............
.c..............
...oo.oo.oo.oo..
..osSosSosSosSo.
..osSosSosSosSo.
..osSosSosSosSo.
..oooooooooosSo.
..osssssssSosSo.
..oSSSSSSSSosSo.
...oooooooooSSo.
....osssssssso..
....oSSSSSSSSo..
....oooooooooo..
................
................
""")

# 요령 = 반짝 켜진 전구
icon('life_efficiency', """
................
......oooo......
.Y..ooYYYYoo..Y.
...oYwYYYYYYo...
...oYwYYYYYyo...
...oYYYaaYYyo...
.Y.oYYaYYaYyo.Y.
....oYYaaYyo....
.....oYYYyo.....
.....oGGGGo.....
.....ogggdo.....
.....oGGGGo.....
.....ogggdo.....
......oddo......
.......oo.......
................
""")


# ════════════════════════════════════════════════════════
#  농사 (farming)
# ════════════════════════════════════════════════════════

# 개간 = 괭이 + 갈아엎은 이랑
icon('farm_till', """
................
............oo..
...........onBo.
..........onBo..
.........onBo...
........onBo....
.......onBo.....
..oooooonBo.....
..oGGGGGgo......
..oGgggggo......
...oGggo........
..nn...nn...nn..
.nBBn.nBBn.nBBn.
.BBBBBBBBBBBBBB.
.bbbbbbbbbbbbbb.
................
""")

# 물주기 = 물뿌리개 + 쏟아지는 물방울
icon('farm_water', """
................
................
................
...ooooo........
..oo...oo...ooo.
..o.....o..oUUo.
.oooooooo.oUUo..
.oUUUUUUUooUo.c.
.oUcUUUUUUUo.c..
.oUcUUUUUUo...c.
.oUUUUUUUUo..c..
.oUUUUUUUuo...c.
.ouuuuuuuuo.....
.oooooooooo.....
................
................
""")

# 수확량 = 소복이 담긴 수확 바구니
icon('farm_yield', """
................
.......ee.......
.....oo.e.oo....
....oEEo.oaao...
...oEeEEooaaaao.
..oEEEEoRRoaaao.
..oEEEoRwRRoaao.
..oEEEoRRRRooo..
.oooooooooooooo.
.onBnBnBnBnBnBo.
..oBnBnBnBnBno..
..onBnBnBnBnBo..
...oBnBnBnBno...
....oooooooo....
................
................
""")

# 씨앗 회수 = 끈으로 묶은 씨앗 주머니 + 쏟아진 씨앗
icon('farm_seed', """
................
.....o..o.......
......oo........
.....onno.......
....oRRRRo......
...onnnnnBo.....
..onnnnnnnBo....
..onnnEnnnBo....
..onnElEnnBo....
..onnnEnnnBo....
..oBnnnnnBBo.b..
...oBBBBBBo.b.b.
....oooooo.b.b..
............b...
................
................
""")

# 비료 효율 = 잎 그림이 찍힌 비료 포대
icon('farm_fert', """
................
..oo........oo..
..omoooooooomo..
..omMmMmMmMmmo..
..ommmmmmmmmMo..
.ommmmmEEmmmMMo.
.ommmmElEEmmmMo.
.ommmEElEmmmmMo.
.ommmEEEmmmmmMo.
.ommmmemmmmmmMo.
.ommmmmmmmmmMMo.
..oMmmmmmmmMMo..
..oMMMMMMMMMMo..
...oooooooooo...
................
................
""")

# 온실 = 비닐하우스 + 안의 작물
icon('farm_green', """
................
................
................
.....oooooo.....
...oocGcGcGoo...
..ocGcGcGcGcGo..
.ocGcGcGcGcGcGo.
.oGcGcGcGcGcGco.
.ocGEcGcEGcGEco.
.oGElGcElGcElco.
.ocEEcGEEcGEEco.
.oGcGcGcGcGcGco.
.oooooooooooooo.
.bbbbbbbbbbbbbb.
................
................
""")

# 파종 감각 = 흙 둔덕에서 돋아난 새싹
icon('farm_sprout', """
................
................
................
...ooo....ooo...
..olEEo..oEEeo..
..oElEEooEEEeo..
...oEEEooEEeo...
....ooeEEeoo....
......oEeo......
......oEeo......
......oEeo......
....ooonBooo....
..oonnnnnBBBoo..
.onnBnnnnnBBBBo.
.oooooooooooooo.
................
""")

# 해충 방제 = 분무기 + 쫓겨나는 벌레
icon('farm_pest', """
................
...ooooo...c.c..
..oGGGGGoo.c....
..oGGGGGGo..c.c.
...ooGGoo.......
...oGGo.........
..oEEEEo........
.oElEEEEo.o..o..
.oElEEEEo..oo...
.oEEEEEEoooRRoo.
.oElEEEEo.oRro..
.oEEEEEeoooRroo.
.oeeeeeeo..oo...
..oooooo........
................
................
""")

# 절기 독해 = 고리 달력 + 표시한 파종일
icon('farm_season', """
................
...o..o..o..o...
..oooooooooooo..
..oRgRRgRRgRRo..
..oRRRRRRRRRRo..
..oooooooooooo..
..omMmMmMmMmmo..
..oMmMmMmMmMmo..
..omMmEEmMmMmo..
..oMmMElmMmMmo..
..omMmMmMmMmmo..
..oMmMmMmMmMmo..
..oMMMMMMMMMMo..
..oooooooooooo..
................
................
""")


# ════════════════════════════════════════════════════════
#  제작 (crafting)
# ════════════════════════════════════════════════════════

# 매듭 숙련 = 바늘 귀에 감아 묶은 낚싯줄 매듭
icon('craft_knot', """
................
.........l......
.........l......
.......oooo.l...
.......oGlo.l...
......ollllo....
......oeeeeo....
......ollllo....
......oeeeeo....
..o....oGgo.....
.oGo...oGgo.....
.oGGo..oGgo.....
.oGgGooGGgo.....
..ogGGGGgo......
...oooooo.......
................
""")

# 공구 관리 = 빨간 공구함
icon('craft_tools', """
................
................
................
.....oooooo.....
.....o....o.....
..oooooooooooo..
..oRwRRRRRRRro..
..oRRRRRRRRRro..
.oooooooooooooo.
.oRRRRRggRRRRro.
.oRRRRRRRRRRRro.
.oRRRRRRRRRRRro.
.orrrrrrrrrrrro.
.oooooooooooooo.
................
................
""")

# 봉돌 주조 = 쇳물 국자 + 봉돌 거푸집
icon('craft_sinker', """
................
.ooooo..........
.oAaAoooooooo...
.oggggoBBBBBBo..
..oggo.ooooooo..
...oAo..........
....A...........
....A...........
.oooAoooooooooo.
.oGGAGGGGGGGGGo.
.oggAgggdgggGgo.
.ogAAAgdddgGwGo.
.ogAAAgdddgGGGo.
.oggAgggdgggGgo.
.oooooooooooooo.
................
""")

# 밑밥 블렌딩 = 배합 통 + 젓는 막대 + 소용돌이
icon('craft_chum', """
................
...........oo...
..........obo...
.........obo....
........obo.....
..oooooobooooo..
.oBnnnnbnnnnBo..
.oBnBBBbBBBnBo..
.oBnBnnnnnBnBo..
.oBnBnBBBnBnBo..
.oBnnnBnnnBnBo..
..oGGGGGGGGGo...
..ogggggggggo...
...ogggggggo....
....ooooooo.....
................
""")

# 루어 도색 = 붓 + 반쯤 칠한 루어
icon('craft_paint', """
................
.oo.............
.oBo............
..oBo...........
...oBo..........
....oGo.........
.....oGo........
.....oRRo.......
......oRRo......
.......oRo......
....oooooooooo..
...oRRRRwwwwwGo.
..oRoRRRwwwwwGo.
...oRRRRwwwwgo..
....ooooooooo...
................
""")

# 구급품 제작 = 구급상자
icon('craft_medic', """
................
................
......oooo......
......o..o......
..oooooooooooo..
..owwwwRRwwwGo..
..owwwwRRwwwGo..
..owwRRRRRRwGo..
..owwRRRRRRwGo..
..owwwwRRwwwGo..
..owwwwRRwwwGo..
..oGGGGGGGGGgo..
..oooooooooooo..
................
................
................
""")

# 에기 튜닝 = 에기 + 조정 드라이버
icon('craft_egi', """
................
...oooooooo.....
..oAAaAAaAAop.G.
.oAwoaAAaAAAopG.
.oAooaAAaAAAopG.
.oAAaAAaAAAAop..
.ogggoRRRRooopG.
..ooo.oRRRo.....
.......oGo......
........oGo.....
.........oGo....
..........oRRo..
...........oRRo.
............oRo.
.............o..
................
""")

# 통발 제작 = 짜고 있는 통발 + 망치
icon('craft_trap', """
................
....oooooo......
..ooGvGvGvoo....
.oGvGvGvGvGvo...
.oGGGGGGGGGGo...
.oGvGvGvGvGvo...
.oGvGvGvGvGvo...
.oGGGGGGGGGGo...
.obbbbbbbbbbo...
.oooooooooooooo.
.........oGGGgo.
.........oooBoo.
...........oBo..
...........oBo..
............o...
................
""")

# 도면 독해 = 청사진(격자 + 바늘 설계선)
icon('craft_bp', """
................
................
.ooooooooooo....
.ouUuuUuuUucoo..
.oUUUUUUUUUccco.
.ouUuuUwwUuuUuo.
.ouUuuwuUwuuUuo.
.oUUUUUwwUUUUUo.
.ouUuuUwUuuuUuo.
.ouUwuUwUuuuUuo.
.oUUwUUwUUUUUUo.
.ouUuwwwuuuuUuo.
.ouUuuUuuUuuUuo.
.oooooooooooooo.
................
................
""")

# 인내심 = 모래시계
icon('craft_batch', """
................
..oooooooooooo..
..oBnnnnnnnnBo..
..oooooooooooo..
...ow......co...
....ownnnnco....
.....onnnno.....
......onno......
......o.no......
.....ow.nco.....
....ow..n.co....
...ow.nnnn.co...
..oooooooooooo..
..oBnnnnnnnnBo..
..oooooooooooo..
................
""")

# 로드 빌딩 = 가이드를 실로 감아 다는 낚싯대 블랭크
icon('craft_rod', """
................
................
......G....oUuo.
.....G.G..oUuo..
......Gg.oUuo...
...G....oRRo....
..G.G..oUuo.....
...Gg.oUuo......
.....oRRo.......
....oUuo........
...oggo.........
..onBo..........
.onBo...........
.ooo............
................
................
""")

# 릴 커스텀 = 맞물린 톱니바퀴 두 개
icon('craft_reel', """
................
...........o....
.........ooGoo..
.........oGGGo..
.....ooooGGoGGo.
...o.oyo.oGGgo..
..oyoyYyoyogoo..
...oyYyyyo.o....
.ooyYyoyyyoo....
.oyyyo.oyyko....
.ooyyyoyykoo....
...oyyyyko......
..oyoyyyoko.....
...o.oko.o......
.....ooo........
................
""")


# ════════════════════════════════════════════════════════
#  숨은 시너지 (syn_*) — 금색 팔각 엠블럼 + 두 스킬을 합친 그림
# ════════════════════════════════════════════════════════
# 테두리는 다섯 시너지가 공유한다(일반 스킬과 한눈에 구분되도록).
# motif 의 '.' 자리는 테두리/바탕을 그대로 두고, 그 외 문자만 덮어쓴다.

SYN_FRAME = """
................
....oooooooo....
...oYYYYYYYyo...
..oYvvvvvvvvko..
.oYvvvvvvvvvvko.
.oYvvvvvvvvvvko.
.oYvvvvvvvvvvko.
.oYvvvvvvvvvvko.
.oYvvvvvvvvvvko.
.oYvvvvvvvvvvko.
.oYvvvvvvvvvvko.
.oyvvvvvvvvvvko.
..oyvvvvvvvvko..
...okkkkkkkko...
....oooooooo....
................
"""


def syn(key, motif, pal=None):
    """시너지 엠블럼: 공용 금테 위에 motif 를 얹어 16x16 아트를 만든다."""
    frame = SYN_FRAME.strip('\n').split('\n')
    mrows = motif.strip('\n').split('\n')
    if len(mrows) != H:
        raise SystemExit(f'{key}: motif 행 수 {len(mrows)} != {H}')
    out = []
    for i, (fr, mr) in enumerate(zip(frame, mrows)):
        if len(mr) != W:
            raise SystemExit(f'{key}: motif r{i} 길이 {len(mr)} != {W} -> "{mr}"')
        out.append(''.join(m if m != '.' else f for f, m in zip(fr, mr)))
    icon(key, '\n'.join(out), pal)


# 물때를 읽는 손 (조석 해석 + 입질 감각) = 물결 위에 선 찌
syn('syn_tidewalker', """
................
................
................
.......ww.......
......oRRo......
.....oRRRRo.....
.....owwwwo.....
.....oRRRRo.....
......oRRo......
...ww..oo..ww...
...UUww..wwUU...
...UUUUwwUUUU...
....UUUUUUUU....
................
................
................
""")

# 달빛 눈 (헤드랜턴 + 채집 눈) = 초승달 아래 빛나는 눈
syn('syn_moonlit', """
................
................
................
.....wcc........
....wc......Y...
....wc..........
....wc......c...
.....wcc........
................
.......www......
.....wwUoUww....
.......www......
................
................
................
................
""")

# 시세의 직관 (흥정 + 시세 읽기) = 엽전 + 오르는 화살표
syn('syn_broker', """
................
................
................
.........EE.....
........EllE....
.......EEllEE...
.........lE.....
....kkkk.lE.....
...kYYyyklE.....
...kYvvyklE.....
...kyvvyklE.....
...kyyykk.......
....kkkk........
................
................
................
""")

# 무쇠 몸 (체력 + 회복력 + 면역) = 강철 하트
syn('syn_ironbody', """
................
................
................
................
....GGg..Ggg....
...GwGGgGGggo...
...GGGGGGGggo...
...GGwGGGgggo...
....GGGGgggo....
.....GGgggo.....
......Gggo......
.......go.......
................
................
................
................
""")

# 장인의 손 (매듭 숙련 + 공구 관리) = 망치 + 반짝임
syn('syn_artisan', """
................
................
................
...........Y....
...oooooooYY....
...GGGGGGGo.Y...
...gggggggo.....
......BB........
......BB........
......BB........
......BB........
......BB........
................
................
................
................
""")


# ════════════════════════════════════════════════════════
#  검증 + 출력
# ════════════════════════════════════════════════════════

# 스킬 트리 전체 id (core SkillTree 와 1:1 — 하나라도 빠지면 에러)
SKILL_IDS = [
    'fish_cast', 'fish_bite', 'fish_line', 'fish_weather', 'fish_night', 'fish_fresh', 'fish_drag',
    'fish_chum', 'fish_lure', 'fish_hook', 'fish_tide', 'fish_bigluck', 'fish_scatter', 'fish_spool',
    'fish_surf', 'fish_wind', 'fish_jig', 'fish_egi', 'fish_salvage', 'fish_double_bait',
    'gath_eye', 'gath_knot', 'gath_hands', 'gath_octo', 'gath_bait', 'gath_trapluck', 'gath_tide',
    'gath_harvest', 'gath_lantern', 'gath_speed',
    'eco_haggle', 'eco_bulk', 'eco_regular', 'eco_market', 'eco_land', 'eco_stock', 'eco_restaurant',
    'eco_ledger', 'eco_auction', 'eco_storage',
    'drv_run', 'drv_barefoot', 'drv_bike', 'drv_bikefat', 'drv_car', 'drv_boat', 'drv_nightride',
    'drv_cargo', 'drv_motion', 'drv_theory',
    'life_stamina', 'life_strength', 'life_recover', 'life_balance', 'life_cold', 'life_fillet',
    'life_cook', 'life_hunger', 'life_thirst', 'life_sleep', 'life_immune', 'life_firstaid',
    'life_hygiene', 'life_belly', 'life_canteen', 'life_grit', 'life_efficiency',
    'farm_till', 'farm_water', 'farm_yield', 'farm_seed', 'farm_fert', 'farm_green', 'farm_sprout',
    'farm_pest', 'farm_season',
    'craft_knot', 'craft_tools', 'craft_sinker', 'craft_chum', 'craft_paint', 'craft_medic',
    'craft_egi', 'craft_trap', 'craft_bp', 'craft_batch', 'craft_rod', 'craft_reel',
    'syn_tidewalker', 'syn_moonlit', 'syn_broker', 'syn_ironbody', 'syn_artisan',
]

if len(SKILL_IDS) != len(set(SKILL_IDS)):
    raise SystemExit('SKILL_IDS 중복')
missing = [k for k in SKILL_IDS if k not in ICONS]
extra = [k for k in ICONS if k not in SKILL_IDS]
if missing or extra:
    raise SystemExit(f'스킬 id 불일치 — 누락 {missing} / 미등록 {extra}')

# 선택: `--ids <목록 파일>`(행 = id | 분류 | 이름 ...)을 주면 그 id 집합과도 대조한다.
if __name__ == '__main__' and '--ids' in sys.argv:
    with open(sys.argv[sys.argv.index('--ids') + 1], encoding='utf-8') as f:
        listed = [ln.split('|')[0].strip() for ln in f if '|' in ln]
    diff = set(listed) ^ set(SKILL_IDS)
    if diff:
        raise SystemExit(f'목록 파일과 id 불일치: {sorted(diff)}')

# 서로 똑같은 아이콘이 없는지(복붙 실수 방지)
_seen = {}
for _k, (_p, _rows, _w, _h) in ICONS.items():
    _sig = (tuple(_rows), tuple(sorted(_p.items())))
    if _sig in _seen:
        raise SystemExit(f'{_k}: {_seen[_sig]} 와 픽셀이 완전히 같다')
    _seen[_sig] = _k


def build_ts():
    out = io.StringIO()
    out.write('/**\n')
    out.write(' * @file SkillIconArt.ts\n')
    out.write(' * @description 스킬 트리 아이콘 아트 (자동 생성 — 수동 편집 금지)\n')
    out.write(' *\n')
    out.write(' * 생성기: `py tools/gen_skill_icons.py` (아트 원본도 그 안에 있다)\n')
    out.write(f' * 스킬 {len(ICONS)}종 × 16x16 손그림 매트릭스 — 키 = 스킬 id, 문자 = 팔레트 키, `.` = 투명.\n')
    out.write(' * 숨은 시너지(syn_*)는 공용 금테 엠블럼 위에 그림을 얹는다.\n')
    out.write(' * 굽기·렌더는 `ui/PixelIcon.ts`와 같은 방식으로 한다(여기는 순수 데이터).\n')
    out.write(' */\n\n')
    out.write("import type { PixelIconArt } from './PixelIconArt.js';\n\n")
    out.write('/** 스킬 id → 16x16 픽셀 아이콘 */\n')
    out.write('export const SKILL_ICON_ART: Record<string, PixelIconArt> = {\n')
    for key in SKILL_IDS:
        pal, rows, w, h = ICONS[key]
        out.write(f"  {key}: {{\n    w: {w}, h: {h},\n    pal: {{ ")
        out.write(', '.join(f"'{c}': 0x{v:06x}" for c, v in pal.items()))
        out.write(' },\n    rows: [\n')
        for r in rows:
            out.write(f"      '{r}',\n")
        out.write('    ],\n  },\n')
    out.write('};\n')
    return out.getvalue()


if __name__ == '__main__':
    here = os.path.dirname(os.path.abspath(__file__))
    dst = os.path.join(here, '..', 'packages', 'client-pc', 'src', 'data', 'SkillIconArt.ts')
    with open(dst, 'w', encoding='utf-8', newline='\n') as f:
        f.write(build_ts())
    print(f'생성: {os.path.normpath(dst)} — 아이콘 {len(ICONS)}종')
